### ISSUE TITLE
PyPI source (sdist) ships compiled libblosc2.so

### ISSUE THREAD

**Issue by bnavigator** [PyTables/PyTables#1001]
The currently published source distribution on PyPI ships the compiled Unix library `tables-3.8.0/tables/libblosc2.so`.

**Comment by avalentino** [comment]
Thanks for reporting.
I will try to address it ASAP.

**Comment by avalentino** [comment]
The issue seems to be already fixed in the current master branch.

**Comment by bnavigator** [comment]
Are you sure? The current master branch CI still has the following output when creating the sdist:

```
  * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
 ```

So it seems to be intentional. It should not be. Sdists are for sources, not for platform dependent libraries.

**Comment by avalentino** [comment]
I can confirm that, despite the message, no ".so" file is include din the source distribution now generated with `make dist`.
The "libblosc2.so" file is in the local source tree after the build but not included in the sdist.
