### ISSUE TITLE
tables how to retrieve using SQL such as group by columns

### ISSUE THREAD

**Issue by hengaini2055** [PyTables/PyTables#1005]
Does pytables have functions like SQL to retrieve data from dataset in hdf5?
If so, we can retrieve complex data and use pushdown like polars.

**Comment by hengaini2055** [comment]
How to difference the hdf5 and pyarrow too?

**Comment by hengaini2055** [comment]
I want to make a huge multidimensional dataset (tables not NDarray),  pivot the cubes like microsoft power pivot table.

**Comment by FrancescAlted** [comment]
> Does pytables have functions like SQL to retrieve data from dataset in hdf5?
> If so, we can retrieve complex data and use pushdown like polars.

No, PyTables is rather meant to be used as a complement to SQL.  Having said this, you can still do quite a few things similar to SQL; see https://www.pytables.org/cookbook/hints_for_sql_users.html.

**Comment by FrancescAlted** [comment]
> How to difference the hdf5 and pyarrow too?

Not really familiar with pyarrow, but my guess is that they are quite different beasts, with pyarrow emphasizing dealing with data in memory, whereas HDF5 is more for on-disk data.

**Comment by FrancescAlted** [comment]
> I want to make a huge multidimensional dataset (tables not NDarray), pivot the cubes like microsoft power pivot table.

Again, not really familiar with microsoft power pivot table, but it looks like this is meant for small datasets, whereas PyTables/HDF5 is more meant to data that does not necessarily fit in-memory.  For more info, you are invited to read the docs.

**Comment by hengaini2055** [comment]
Thank you! I read all doc once again. When I use numexpr retrieve some dataset, that dataset may larger than memory, how can I process it?  And the doc has so many invalid links to hdgroup.org such as [bibliography](http://www.pytables.org/usersguide/bibliography.html) ,  the benchmark almost based on pytables 2.1.
As you mentioned above, pytables  is rather meant to be used as a complement to SQL. The main feature is to manage so many datasets in a hierarchical structure, and the dataset can huge to many billion rows.
Where is practice examples for pytables especially from the third teams?
