### ISSUE TITLE
Unable to Import HDF5 Library

### ISSUE THREAD

**Issue by sanssecours** [PyTables/PyTables#1020]
# Description

It looks like the current wheels of PyTables (`3.8.0`) tries to load an incorrect (old) version of the HDF5 library on my machine (`libhdf5.200.dylib` instead of `libhdf5.310.dylib`).

# Steps to Reproduce the Problem

1. Install `tables`

   ```sh
   pip install tables
   ```

2. Try to import `tables`:

   ```sh
   python -c "import tables"
   ```

# Expected Result

The code in step 2 runs without any problems.

# Actual Result

The import statement raises an `ImportError`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rene/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tables/__init__.py", line 32, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: dlopen(/Users/rene/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tables/utilsextension.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib
  Referenced from: <5D62F17A-4934-3FA0-8E84-A3C6931FF187> /Users/rene/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tables/utilsextension.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/hdf5/1.14.1/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/hdf5/1.14.1/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/Cellar/hdf5/1.14.1/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache)
```

The directory `/opt/homebrew/opt/hdf5/lib` contains the following files on my machine:

```
libhdf5.310.dylib
libhdf5.a
libhdf5.dylib@ -> libhdf5.310.dylib
libhdf5_cpp.310.dylib
libhdf5_cpp.a
libhdf5_cpp.dylib@ -> libhdf5_cpp.310.dylib
libhdf5_fortran.310.dylib
libhdf5_fortran.a
libhdf5_fortran.dylib@ -> libhdf5_fortran.310.dylib
libhdf5_hl.310.dylib
libhdf5_hl.a
libhdf5_hl.dylib@ -> libhdf5_hl.310.dylib
libhdf5_hl_cpp.310.dylib
libhdf5_hl_cpp.a
libhdf5_hl_cpp.dylib@ -> libhdf5_hl_cpp.310.dylib
libhdf5_hl_fortran.a@ -> libhdf5hl_fortran.a
libhdf5hl_fortran.310.dylib
libhdf5hl_fortran.a
libhdf5hl_fortran.dylib@ -> libhdf5hl_fortran.310.dylib
```

# Workaround

I was able to fix the problem using the following commands:

```sh
pip uninstall tables -y
brew install hdf5 c-blosc lzo bzip2
export HDF5_DIR=/opt/homebrew/opt/hdf5
export BLOSC_DIR=/opt/homebrew/opt/c-blosc
pip install --no-binary :all: git+https://github.com/PyTables/PyTables.git@v3.8.0
```

# System Information

- macOS `13.4` (`arm64`)
- Python `3.11.4`

**Comment by avalentino** [comment]
Dear @sanssecours 
this is strange indeed.
PyTables should use the dylib bundled in the Python Wheel.
Could you please confirm that the library is actually provided?
It should be in`/Users/rene/.pyenv/versions/3.11.4/lib` in your case.

**Comment by sanssecours** [comment]
Hi Antonio,

thank you for the quick response.

> Could you please confirm that the library is actually provided?
> It should be in`/Users/rene/.pyenv/versions/3.11.4/lib` in your case.

Looks like the package contains a library for `blosc`, but not for `hdf5`. At least the command:

```sh
find "$HOME/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tables/" -name '*.dylib'
```

only prints the following line on my computer:

```
/Users/rene/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tables//libblosc2.dylib
```

**Comment by avalentino** [comment]
Hi @sanssecours,
I have just checked the available wheels in PyPI.
We do not provide a wheel for OSX on ARM so (unless for some reason you are using the intel ones) PyTables should only build form sources.
In this case the solution is the one that you have already found: to set the environment variables to point to the correct version of the libraries.

**Comment by sanssecours** [comment]
> We do not provide a wheel for OSX on ARM so (unless for some reason you are using the intel ones) PyTables should only build form sources.

Ah, that makes sense. Seems I built the package once before using an older version of the HDF5 library. pip then used this old version, when I tried to install the package again:

```
> pip install tables
Collecting tables
  Using cached tables-3.8.0-cp311-cp311-macosx_13_0_arm64.whl
…
```

If I install `tables` using `--no-cache-dir`:

```sh
pip install --no-cache-dir tables
```

the installation fails (as expected):

```
Collecting tables
…
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
…
```

Thank you for your help 💖 and **sorry for the spurious bug report**.
