### ISSUE TITLE
Library not loaded: @rpath/libhdf5.310.dylib

### ISSUE THREAD

**Issue by windemut** [PyTables/PyTables#1022]
I can't get tables to work at all on Mac M1 Ventura 13.4. It can't find the hdf5 dynamic library, it seems. I installed like this:
```
brew install hdf5 c-blosc lzo bzip2
export HDF5_DIR="$(brew --prefix hdf5)"
pip3 install tables
```

```
% python3 -m tables.tests.test_all
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tables/__init__.py", line 32, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tables/utilsextension.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libhdf5.310.dylib
  Referenced from: <97D08AE0-CC5C-35AA-AC56-C45460DE5186> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tables/utilsextension.cpython-311-darwin.so
  Reason: tried: '/usr/lib/libhdf5.310.dylib' (no such file, not in dyld cache)
```
Any ideas?

**Comment by avalentino** [comment]
Dear @windemut 
It would be nice to understand that is `$(brew --prefix hdf5)` to have a better picture of what is happening.
Moreover, could you please clarify if you are using a native PyTables build or if you are working with x86 emulation?

As a general comment I can say that many users reported strange behaviours related with `brew` used on M1 HW. Maybe you could try to give a look to some of the old tickets (many of them already closed) to understand is a solution to your problem has been already found.
We try to label these issues with `osx` or `osx-arm64`. Maybe it will help you in the search.

**Comment by windemut** [comment]
Thank you for your response, @avalentino! The hdf5 path expands to ‘/opt/homebrew/opt/hdf5’, and libhdf5.310.dylib is found in the ‘lib’ subdirectory thereof. I don’t know about emulation, I just used ‘pip3 install tables’. I will search some more, but I have already done a lot. The problem seems to be related with @rpath, and I have little understanding of that.

**Comment by avalentino** [comment]
hmm, I don't think that the `rpath` link flag is used in the PyTables build process, but I could be wrong.
Unfortunately I do not have access to a Mac M1 to reproduce the issue.
Is it possible for you to attach the full build log of PyTables?

You could also try to set `DYLD_LIBRARY_PATH` to point to the installation path of HDF5.
I'm not sure that it will work if `rpath` is set, but this is something easy to try.

**Comment by avalentino** [comment]
Dear @windemut , did you manage to solve the issue?

**Comment by windemut** [comment]
No, I had to move on to other things. If I try again and get results I’ll come back here. Thanks for your help!

**Comment by avalentino** [comment]
Dear @windemut, we didn't heard from you for a while.
I assume that you managed to solve the issue.
In any case is seems most probably linked to an environment issue rather than PyTables itself.
We are now in the process of releasing a new version of PyTables that will also include wheel packages for osx-amd64.
We assume that the new release will make this issue no longer relevant so I'm closing it.
Please feel free to re-open should you have more information about the issue pointing in the direction of a bug in PyTables.
