### ISSUE TITLE
Google Colab Failed building wheel for tables

### ISSUE THREAD

**Issue by swagluke** [PyTables/PyTables#1037]
#### Description of the bug
Trying to install pandana on Google Colab but running into issue with "Building wheels for collected packages: tables"
tables is one of the dependent package that pandana uses.

I've tried following command to fix the issue but without any luck.
1. I've confirmed that tables is installed properly. (3.8.1.dev0) - `!pip install tables --upgrade`
2. Upgrading wheel and setuptools - `!pip install wheel setuptools pip --upgrade`
3. Upgrading cmake - `!pip install cmake --upgrade`

#### Environment 

- Operating system: Linux 9e7b8fb3f067 5.15.109+ #1 SMP Fri Jun 9 10:57:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Python version: Python 3.10.6

- Pandana version: pandana-0.6.1

#### Paste the code that reproduces the issue here:

```python
`!pip install pandana`
```

#### Paste the error message (if applicable):
```python
Building wheels for collected packages: tables, pandana
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tables (setup.py) ... error
  ERROR: Failed building wheel for tables
  Running setup.py clean for tables
  Building wheel for pandana (setup.py) ... done
  Created wheel for pandana: filename=pandana-0.6.1-cp310-cp310-linux_x86_64.whl size=1851091 sha256=29eca75859973cf1c66bbac86430ff4686e547df5a2f8bf719e25e53c1729a9f
  Stored in directory: /root/.cache/pip/wheels/e7/4b/71/360fe3ffe9d5822e4d35b07a9938f0b074056b43a0040b373a
Successfully built pandana
Failed to build tables
ERROR: Could not build wheels for tables, which is required to install pyproject.toml-based projects
```

**Comment by avalentino** [comment]
Dear @swagluke,
could you please provide more info about your system?
In principle we have pre-built wheels for GNU/Linux (manylinux) and Python 3.10 (see https://pypi.org/project/tables/#files).
This means that `pip` should not attempt to build PyTables from sources.

In any case, If you need to build from sources please refer to the [PyTables documentation](https://www.pytables.org/usersguide/installation.html).
PyTables has binary dependencies that are not available on PyPI, they need to be installed on the machine before trying to run `pip`.
