### ISSUE TITLE
Compilation fails for Tables 3.8.0 with Cython 3.0.0

### ISSUE THREAD

**Issue by alexhermida** [PyTables/PyTables#1040]
Hi! first of all thank you for the project, great work!

I noticed that recently PyTables installation from the latest release (3.8.0) started to fail for me, at least for Mac M1 whereas was working a few months ago.

HDF5 and C-BLOSC are installed and environment variables correctly set. The new error is:

```
  tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'
```

Installling from `main` in this repository works well for me.

Investigating a bit I saw [this commit](https://github.com/PyTables/PyTables/commit/a70e36f0b0d4fb15b0b50e7ca513c4e4452767cc) and also, I noticed that the new stable version 3.0.0 of Cython  has been released [last Jul 17](https://pypi.org/project/Cython/#history). 
So my understanding is that the current stable release for PyTables is  broken for compilation in Mac M1 at least due to the recent Cython package release.

I think a patch or bugfix release for PyTables would be enough.

Thank you!

**Comment by avalentino** [comment]
Compatibility with cython 3.0 has been fixed in the master branch (#1008).
It will be included in the next release.

If you wan you can give it a try just using the following command for tehe installation:
```
$ pip install git+https://github.com/PyTables/PyTables
```

**Comment by alexhermida** [comment]
Hey @avalentino thank you for your answer. As I mentioned in my comment I know it's been fixed and it works installing from Git. 

My point was that since Cython version 3.0.0 was released last Jul 17 any pip install that doesn't use the wheels for the current PyTables release it's failing.  I was suggesting that rather waiting for a new stable release to create a patch/bugfix release meantime.

Thanks anyway.

**Comment by avalentino** [comment]
@alexhermida accordint to [this post](https://groups.google.com/g/pytables-dev/c/3FlbDwmJrVg/m/LZX06S8ABQAJ) we should have a new release of PyTables relatively soon.
AFAIK there are no plans for a patch release at the moment.

**Comment by alexhermida** [comment]
Thank you both, sounds good.
