### ISSUE TITLE
ython.Compiler.Errors.CompileError: tables/utilsextension.pyx

### ISSUE THREAD

**Issue by guowj163** [PyTables/PyTables#1055]
I have tried many ways to install the package of tables in macOS. Can anyone help me? Please
PyTables-master % python3 setup.py install
/Users/g/software/PyTables-master/setup.py:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
cpuinfo failed, assuming no CPU features: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
* Using Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
* Found cython 3.0.2
* USE_PKGCONFIG: True
* Found HDF5 headers at ``/opt/homebrew/Cellar/hdf5/1.14.2/include``, library at ``/opt/homebrew/Cellar/hdf5/1.14.2/lib``.
* Found LZO 2 headers at ``/opt/homebrew/Cellar/lzo/2.10/include``, library at ``/opt/homebrew/Cellar/lzo/2.10/lib``.
* Skipping detection of LZO 1 since LZO 2 has already been found.
* Could not find bzip2 headers and library; disabling support for it.
* pkg-config header dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.5/include
* pkg-config library dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.5/lib
* Found blosc headers at ``/opt/homebrew/Cellar/c-blosc/1.21.5/include``, library at ``/opt/homebrew/Cellar/c-blosc/1.21.5/lib``.
Compiling tables/utilsextension.pyx because it changed.
[1/1] Cythonizing tables/utilsextension.pyx

Error compiling Cython file:
------------------------------------------------------------
...

def _dump_h5_backtrace():
    cdef object bt = []

    if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                               ^
------------------------------------------------------------

tables/utilsextension.pyx:367:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil'.
Traceback (most recent call last):
  File "/Users/g/software/PyTables-master/setup.py", line 834, in <module>
    cython_extfiles = get_cython_extfiles(cython_extnames)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g/software/PyTables-master/setup.py", line 829, in get_cython_extfiles
    cythonize(str(extpfile), language_level="2")
  File "/opt/homebrew/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/opt/homebrew/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx

**Comment by david-lin-09** [comment]
Have you tried this ?
https://github.com/PyTables/PyTables/issues/1040

**Comment by avalentino** [comment]
This should be fixed in PyTables 3.10.
Please feel free to re-open if it is not the case.
