### ISSUE TITLE
installing tables (3.9.1) from pypi fails on mac arm64

### ISSUE THREAD

**Issue by alpae** [PyTables/PyTables#1074]
Dear all,

I can no longer install pytables 3.9.1 on a mac with arm64. 
the command `pip install tables==3.9.1` fails with following error message:

    Collecting tables==3.9.1
      Using cached tables-3.9.1.tar.gz (4.7 MB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error
    
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [20 lines of output]
          ld: library not found for -lblosc2
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          cpuinfo failed, assuming no CPU features: 'flags'
          * Using Python 3.11.1 (main, Jan  4 2023, 11:04:27) [Clang 14.0.0 (clang-1400.0.29.202)]
          * Found cython 3.0.5
          * USE_PKGCONFIG: True
          * Found HDF5 headers at ``/usr/local/include``, library at ``/usr/local/lib``.
          * Found LZO 2 headers at ``/usr/local/include``, library at ``/usr/local/lib``.
          * Skipping detection of LZO 1 since LZO 2 has already been found.
          * Could not find bzip2 headers and library; disabling support for it.
          * pkg-config header dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.4/include
          * pkg-config library dirs for blosc: /opt/homebrew/Cellar/c-blosc/1.21.4/lib
          * Found blosc headers at ``/opt/homebrew/Cellar/c-blosc/1.21.4/include``, library at ``/opt/homebrew/Cellar/c-blosc/1.21.4/lib``.
          * pkg-config header dirs for blosc2: /Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install/include
          * pkg-config library dirs for blosc2: /Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install/lib
          * Run 'blosc2_find_directories_hook'
          .. ERROR:: Could not find a local blosc2 installation.
             You may need to explicitly state where your local blosc2 headers
             and library can be found by setting the ``BLOSC2_DIR`` environment
             variable or by using the ``--blosc2`` command-line option.
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip. 

Pytables version 3.8.0 could be installed. From the error, it seems that the blosc2 paths point somewhere into the github runners?

**Comment by avalentino** [comment]
The pkg-config paths look strange:

```
* pkg-config header dirs for blosc2: /Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install/include
* pkg-config library dirs for blosc2: /Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install/lib
```

Could you please confirm that the expected files (`blosc2.h` and `libblosc2.dylib`) are indeed present in those paths?

**Comment by alpae** [comment]
Hi @avalentino 

thanks for the hint. no, these files were not there, but pkg-config reported them to be there. It turned out that I had messed up my global environment earlier without realizing it. The python-blosc2 package exposed these paths (probably from the build on the CI). 

cleaning up my environment solved it! Cheers Adrian

**Comment by avalentino** [comment]
@alpae. happy to hear that the problem is solved now!
Thanks anway for reporting.
