### ISSUE TITLE
Bug in __init()__

### ISSUE THREAD

**Issue by martinowitsch** [PyTables/PyTables#1100]
There seems to be a bug in line 41 in the  `__init()__.py`  file.

The join() function will crash: 
`    raise RuntimeError("Blosc2 library not found. "
                       f"I looked for \"{', '.join(blosc2_search_paths)}\"")`

If the list blosc2_search_paths conatins a 'None', i.e.:
['libblosc2.dll', 'c:\\Somewhere\\libblosc2.dll', None]
```
Traceback (most recent call last):
  File "c:\IniTest.py", line 34, in <module>
    f"I looked for \"{', '.join(blosc2_search_paths)}\"")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, NoneType found
```

This may happen, when the list is generated in line 27:
```
blosc2_search_paths = [blosc2_lib_hardcoded,
                       os.path.join(current_dir, blosc2_lib_hardcoded),
                       find_library("blosc2")]
```

And the function find_library("blosc2") returns 'None' if no lib was found.

I've encountered this error while generating an executable via PyInstaller and forgot to link the libblosc2.dll.

**Comment by avalentino** [comment]
Dear @martinowitsch 
thanks a lot for reporting.
It seems that you made already a very good analysis!
Would you like to submit a PR to fix this issue?

**Comment by martinowitsch** [comment]
Sure, however since I am new to git, whats a PR? 😄 
I would propose to typecast the return value of find_library("blosc2") call in line 43:
`str(find_library("blosc2"))`

**Comment by RitikaxShakya** [comment]
May I know if this issue is taken? if not may i take this issue?

**Comment by avalentino** [comment]
Hi @RitikaxShakya 
you are more than welcome to take in charge this issue.
Thanks a lot

**Comment by RitikaxShakya** [comment]
Yes i would like to pick this issue.

**Comment by jtc42** [comment]
I'm seeing the same thing when packaging using Nuitka. Has anything happened on this yet?

**Comment by padraic-padraic** [comment]
From checking the source on the main branch, it seems like this should be marked as fixed. Rather than appending the result of `find_library` directly, it's only appended if it returns a Truth-y value https://github.com/PyTables/PyTables/blob/7732c897be81372b16c9950f57b7c4cfe5b4be93/tables/__init__.py#L27-L34

**Comment by avalentino** [comment]
Thanks @padraic-padraic ,
Indeed the code looks correct now.
Closing
