### ISSUE TITLE
Uploading nightly wheels (for testing and better cross-project integration)

### ISSUE THREAD

**Issue by jarrodmillman** [PyTables/PyTables#1115]
Would you be interested/willing to upload nightly wheels to:
https://anaconda.org/scientific-python-nightly-wheels/

It would also be great if you would testing against nightly wheels that you depend on (i.e., numpy).

You can read more about why and how we are building / testing against nightly wheels here:
https://scientific-python.org/specs/spec-0004/

We provide a GitHub action to upload nightly builds to the [scientific-python nightly channel](https://anaconda.org/scientific-python-nightly-wheels):
https://github.com/scientific-python/upload-nightly-action/

We @matthewfeickert, @larsoner, @tupui are happy to help.

**Comment by avalentino** [comment]
Dear @jarrodmillman, deal al,
I think that it would be nice nightly wheels to in https://anaconda.org/scientific-python-nightly-wheels/, even if, at the moment there is no big evolution planned for PyTables, only basic maintenance, 

Currently we have problems with numpy-2.0-dev.
I have a preliminary patch (see also #1083), but, unfortunately, the job is not progressing due to lack of time.

How would you like to proceed?

**Comment by matthewfeickert** [comment]
@avalentino We have the approval (https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960037619) to add `pytables` to the nightly wheels Anaconda Cloud org https://anaconda.org/scientific-python-nightly-wheels/!

To get started on this please do the following:

## Steps to gain upload access to https://anaconda.org/scientific-python-nightly-wheels/

* [ ] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [ ] Reply here with the link to your account
* [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

* [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [ ] Direct me (@matthewfeickert) to a `tables` nightly wheel for me to upload to create the package in the registry
* [ ] Verify that I have added you to the [`pytables` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pytables) on https://anaconda.org/scientific-python-nightly-wheels
* [ ] Verify that I have added the package `scientific-python-nightly-wheels/tables` to the [`pytables` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pytables)

If you'd also like to use the [`scientific/upload-nightly-action` GitHub Action](https://github.com/scientific-python/upload-nightly-action) please check out [this repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

If you have any questions please just ask here!

**Comment by avalentino** [comment]
OK, I have created the TOKEN and added it to the secrets of the repository.
I have also crated a new workflow for nightly build of wheels:
https://github.com/PyTables/PyTables/actions/workflows/nightly-wheels.yml

For the time being it only produces wheels on amd64 and runs once per week (the first run should be today at 13:12).
It still does not include the step for [scientific/upload-nightly-action GitHub Action](https://github.com/scientific-python/upload-nightly-action). I will set it up ASAP the next week.

**Comment by matthewfeickert** [comment]
> I have also crated a new workflow for nightly build of wheels: https://github.com/PyTables/PyTables/actions/workflows/nightly-wheels.yml

Great. I've used that to create https://anaconda.org/scientific-python-nightly-wheels/tables which you have admin access over now.

> For the time being it only produces wheels on amd64 and runs once per week (the first run should be today at 13:12). It still does not include the step for [scientific/upload-nightly-action GitHub Action](https://github.com/scientific-python/upload-nightly-action). I will set it up ASAP the next week.

Sounds good! Just let us know if you have any questions. :+1:

**Comment by avalentino** [comment]
[scientific/upload-nightly-action GitHub Action](https://github.com/scientific-python/upload-nightly-action) is now enabled.

**Comment by larsoner** [comment]
I no longer see any `tables` wheels at https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ , looks like the workflow is broken:

https://github.com/PyTables/PyTables/actions/runs/13355404326

@avalentino would it help for me to take a look?
