### ISSUE TITLE
PyTables broken via conda-forge install - libblosc2.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by Justin-J-Miller** [PyTables/PyTables#1154]
Hello,

It appears something recent has broken installing the tables binaries with mamba/conda from conda-forge. This appears to have happened in the past ~30h as this install method was working for me yesterday morning. I can reproduce this on several different Ubuntu systems across several mamba versions.

Steps to reproduce

Create a brand new environment and import tables:

```
mamba create -n tables -c conda-forge tables
mamba activate tables
python -c 'import tables'
```

Yields:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jjmiller/miniconda3/envs/tables/lib/python3.12/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: libblosc2.so.2: cannot open shared object file: No such file or directory```

**Comment by avalentino** [comment]
Yesterday a new version of blosc2 was released with the soversion bumped to 3 due to an API change.
This requires a rebuild of the downstream SW to link the new soversion.
This is being done right now.
By the way the old blosc2 binaries (the ones with soversion = 2) should still be available in the archive so you just need to install c-blosc2 < 2.14.4 and the issue should be solved.

**Comment by avalentino** [comment]
By the https://github.com/conda-forge/pytables-feedstock/ is a more appropriate place to report this kind of issues.
I'm closing this issue.
Please refer to:
* https://github.com/conda-forge/pytables-feedstock/issues/97
* https://github.com/conda-forge/pytables-feedstock/issues/98
* https://github.com/conda-forge/pytables-feedstock/pull/99

**Comment by Justin-J-Miller** [comment]
Thanks!On Apr 10, 2024, at 5:43 PM, Antonio Valentino ***@***.***> wrote:﻿
By the https://github.com/conda-forge/pytables-feedstock/ is a more appropriate place to report this kind of issues.
I'm closing this issue.
Please refer to:

conda-forge/pytables-feedstock#97
conda-forge/pytables-feedstock#98
conda-forge/pytables-feedstock#99
