### ISSUE TITLE
Why both blosc and blosc2?

### ISSUE THREAD

**Issue by 0-wiz-0** [PyTables/PyTables#1170]
According to [the blosc2 README](https://github.com/Blosc/c-blosc2/blob/8f8d931fbda982820f5db71619072b696d5daf56/README.rst?plain=1#L36) blosc2 is backwards compatible with blosc(1). However, PyTables uses both blosc and blosc2.
Why is that necessary?

**Comment by avalentino** [comment]
I thin that the key point is

> However, the reverse thing is generally not true for the format; buffers generated with C-Blosc2 are not format-compatible with C-Blosc1

@FrancescAlted is there a way to generate blosc1 compatible data with libblosc2?

**Comment by FrancescAlted** [comment]
> I thin that the key point is
> 
> > However, the reverse thing is generally not true for the format; buffers generated with C-Blosc2 are not format-compatible with C-Blosc1
> 
> @FrancescAlted is there a way to generate blosc1 compatible data with libblosc2?

No, there is not, and there are not plans for doing that.

**Comment by avalentino** [comment]
Thanks Francesc.
So I would say that this iis a very good reason for keeping both blosc1 and blosc2 in PyTables.
Closing.
