### ISSUE TITLE
Broken with NumPy 2.0.0

### ISSUE THREAD

**Issue by Glacier2930** [PyTables/PyTables#1172]
PyTables appears to be broken with the recently released NumPy version 2.0.0.

From a fresh python 3.10 virtual environment, after `pip install tables`

`python3 -m tables.tests.test_all` gives:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/.venv2/lib/python3.10/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
``` 
`pip freeze` gives:
```python
blosc2==2.6.2
msgpack==1.0.8
ndindex==1.8
numexpr==2.10.0
numpy==2.0.0
packaging==24.1
py-cpuinfo==9.0.0
tables==3.9.2
``` 
Downgrading numpy to < 2.0.0 (e.g. 1.26.4) fixes this

**Comment by alpae** [comment]
indeed, this breaks quite a few of our libraries that depend on PyTables. would be great if this could be fixed.

**Comment by larsoner** [comment]
I am currently working on this and will open a PR once #1175 lands

**Comment by maxnoe** [comment]
What is remaining for a new release containing these fixes? Anything we can do to help?

**Comment by avalentino** [comment]
Hi @maxnoe there is a remaining issue that is related to numpy 2: https://github.com/PyTables/PyTables/issues/1185
Moreover in the next version we will probably have some new feature related to direct chunking that is still under development.

**Comment by maxnoe** [comment]
I really think we should publish a new version asap and not wait for any new features. 

Doing a new version quickly after that once the new features are ready is fine, but many users are currently having issues with just installing the package

**Comment by axelande** [comment]
Totally in favor of releasing an updated version that are compatible with Numpy2.
