### ISSUE TITLE
Bug with NumPy 2.0 and index updates

### ISSUE THREAD

**Issue by larsoner** [PyTables/PyTables#1185]
See https://github.com/PyTables/PyTables/pull/1183/files#r1682253262, it's unclear why the index needs to be updated manually.

**Comment by ivilata** [comment]
As a summary, removing the forced reindexing [here](https://github.com/PyTables/PyTables/blob/46c7364cbebca7e5ad7bcf6bc7b2aad5c7d67c59/tables/tests/test_indexvalues.py#L2302) causes `FINSV2aTestCase.test12a` to fail, but only with NumPy 2.
