### ISSUE TITLE
Binary incompatibility with numpy v2.0.1

### ISSUE THREAD

**Issue by sjfleming** [PyTables/PyTables#1199]
Hello!  Thanks for the great package.  Since numpy updated to v2.0.1, I think there is a problem with pip installation of pytables.

Here's the example:

```console
conda create -n test python=3.9
conda activate test
pip install tables
python
```
and in python
```python
>>> import tables
```
throws an error.  On my mac, the terminal just dies with 
```
zsh: illegal hardware instruction  python
```

Colleagues have seen more descriptive messages including
```
import tables
  File "/opt/miniconda3/envs/pkg/lib/python3.9/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I have seen this happen in other packages as well since the numpy update.

**Comment by avalentino** [comment]
Dear @sjfleming,
thanks for reporting but this is clearly a conda packaging issue and you should report it in https://github.com/conda-forge/pytables-feedstock.

The current stable version of PyTables, v3.9.2, is not compatible with numpy >= 2.

**Comment by sjfleming** [comment]
Hi @avalentino , I think my example may have been misleading.  I was just using `conda` to create a blank-slate python environment.  I used `pip` to install pytables, not `conda`.

Okay, I did not realize that pytables was not compatible with numpy >= 2.

Does there need to be a change here for pip installs to work in future?
https://github.com/PyTables/PyTables/blob/7732c897be81372b16c9950f57b7c4cfe5b4be93/pyproject.toml#L8

**Comment by sjfleming** [comment]
Or maybe here?
https://github.com/PyTables/PyTables/blob/ae689fd5b05d73cd9558fbf9a865d13a4082dc2d/requirements.txt#L3

Not sure which one the PyPI build is using

**Comment by avalentino** [comment]
Yes you are right.
PyTables v3.9.2 was released before numpy 2 and we didn't think about putting an upper version limit.
By the way the development version is now compatible with numpy 2 and we should have a new release pretty soon.

**Comment by sjfleming** [comment]
Awesome, thank you very much!

**Comment by avalentino** [comment]
Good, I consider the issue closed then.
Thanks a lot
