### ISSUE TITLE
Bug – Error when copying a table with createparents=True

### ISSUE THREAD

**Issue by 153957** [PyTables/PyTables#1208]
In our project some tests are failing since updating to Tables 3.10:
https://github.com/HiSPARC/publicdb/actions/runs/10441065453/job/28911737318?pr=389#step:6:23

(This might be related to the fixes with correctly passing `createparents` in copy methods).

Here is the relevant traceback:
```
  …
    node.copy(esd_group, createparents=True, overwrite=True)
  File "/opt/miniconda/lib/python3.10/site-packages/tables/table.py", line 2970, in copy
    return super().copy(
  File "/opt/miniconda/lib/python3.10/site-packages/tables/leaf.py", line 786, in copy
    return self._f_copy(
  File "/opt/miniconda/lib/python3.10/site-packages/tables/node.py", line 789, in _f_copy
    dstparent = srcfile._get_or_create_path(dstparent, createparents)
  File "/opt/miniconda/lib/python3.10/site-packages/tables/file.py", line 846, in _get_or_create_path
    return self._create_path(path)
  File "/opt/miniconda/lib/python3.10/site-packages/tables/file.py", line 858, in _create_path
    raise TypeError("when creating parents, parent must be a path")
TypeError: when creating parents, parent must be a path
```

We pass a Group (`/hisparc/cluster_amsterdam/station_501 (Group) ''`) as first argument to `node.copy`, node here is a Table (`/events (Table(168,)) ''`).
This appears to be expected behavior and argument types: https://github.com/PyTables/PyTables/blob/v3.10.1/tables/table.py#L2941

However, on the `Node` the `newparent` can also be a `str`, but if the `newparent` is a `Group` is does not appear to be converted to a `str`: https://github.com/PyTables/PyTables/blob/v3.10.1/tables/node.py#L709

And in the `_create_path` method a `str` is expected: https://github.com/PyTables/PyTables/blob/v3.10.1/tables/file.py#L850
Which is where the error happens.

This might be fixed by adding the conversion (i.e getting the path from the `Group`) at the correct place. I've not looked closely yet at exactly since which commit in PyTables this became an issues.

**Comment by avalentino** [comment]
Dear @153957,
Thanks for reporting.
The change in the behaviour could be linked to the following commit: bfe03a04ac4ea60615f5cd956a7299c0891b29a9.
By the way, it is strange that the issue is not captured by our test suite.
Could you please provide a minimal and self-standing example to reproduce the issue?
The change that you suggest makes sense to me.
If you already have an implementation of the fix, then a PR would be more than welcome.

**Comment by 153957** [comment]
Unfortunately I don't have time this week, but next week I can try to create a small reproducing example. If he is available @tomkooij might be able to create it in the mean time, since he is also familiar with the project where the error happened.

**Comment by avalentino** [comment]
Thanks @153957
