### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by mayrholu** [PyTables/PyTables#1217]
Is there a plan to provide the wheels for Python 3.13 via PyPi and if so, when will they be available?

**Comment by avalentino** [comment]
Dear @mayrholu I have recently enabled the build of wheels in the main branch.
I do not have time in this period to make a new release but I could back port the CI changes on a 3.10.1post branch and upload just the missing wheels.
This will still take some time (a couple of weeks max) but I think it could work

**Comment by mayrholu** [comment]
@avalentino Thanks for your response, the suggestion sound good!

**Comment by avalentino** [comment]
Unfortunately I had some issue in building wheels for windows.
The ones for macosx and GNU/Linux have been uploaded.

**Comment by mayrholu** [comment]
Thank you very much for the quick solution! 
(Sorry for my late response)

**Comment by jetuk** [comment]
Is there any update on the Windows wheels for Python 3.13?

**Comment by davidbossanyi** [comment]
Could this be reopened? Windows wheels are still missing from PyPI. Thanks
