### ISSUE TITLE
Error writing cpu_info

### ISSUE THREAD

**Issue by alpae** [PyTables/PyTables#1221]
Hi,

I was running into an error when I tried to write a pytables file in a singularity container that does not have the user's home folder mounted. The problem is actually very minor: 
when trying to cache the cpu info, the `~/.pytables-cpuinfo.json` can not be written:

https://github.com/PyTables/PyTables/blob/8f5ad6042a9024e803053bedccaf5c9a105d5133/tables/leaf.py#L63

I suggest to ignore any IOErrors writing that file, as the functionailty would still remain the same. It would simply need to be computed for every process once, but within a process, because of the LRU cache,  the function would still be fast.

If you agree, I can submit a PR. 

Cheers Adrian

**Comment by avalentino** [comment]
Hi @alpae 
thanks for reporting.
A PR would be very appreciated indeed.
Thanks a lot.

**Comment by avalentino** [comment]
Closed via #1222
