### ISSUE TITLE
Querying and Indexes

### ISSUE THREAD

**Issue by scopatz** [PyTables/PyTables#186]
If a query has a non-zero start value and the table is indexed, the query seems to report the wrong value.  For example:

```python
>>> table.readWhere("id == 'ceec536a-394e-4dd7-a182-eea557f3bb93'", start=3257, stop=table.nrows)[0]['id']
'7f589d3e-a0e1-4882-b69b-0223a7de3801'

>>> table.where("id == 'ceec536a-394e-4dd7-a182-eea557f3bb93'", start=3257, stop=table.nrows).next()['id']
'7f589d3e-a0e1-4882-b69b-0223a7de3801'
```

See user's mailing list thread entitled "where() with start/stop args returning incorrect result set"

A sample data set has been sent to the dev list, tagged with this issue number.

**Comment by FrancescAlted** [comment]
This has been probably [fixed here](https://github.com/PyTables/PyTables/commit/035dbd5473f17af91f2e4ca489099520f64f96e0).

With that patch here it is the output:

```
 ------- Unindexed ---------
(0, 0, 1, 1)
(1, 1, 1, 2)
(2, 2, 1, 3)
(3, 3, 1, 4)
(4, 4, 1, 5)
(5, 5, 1, 6)
(6, 6, 1, 7)
(7, 7, 1, 8)
(8, 8, 1, 9)
(9, 9, 1, 10)
(10, 10, 0, 10)
 -------- Indexed --------
 This should look the same as above
(0, 0, 1, 1)
(1, 1, 1, 2)
(2, 2, 1, 3)
(3, 3, 1, 4)
(4, 4, 1, 5)
(5, 5, 1, 6)
(6, 6, 1, 7)
(7, 7, 1, 8)
(8, 8, 1, 9)
(9, 9, 1, 10)
(10, 10, 0, 10)
Closing remaining open files:test.h5...done
```

So closing.
