### ISSUE TITLE
String query on indexed column gives incorrect output if `.where` previously used in non-iterator context

### ISSUE THREAD

**Issue by ihaque** [PyTables/PyTables#250]
Simple program to reproduce this error at https://gist.github.com/ihaque/5530731.

If `tables.Table.where` is used in a non-iterator context, subsequent inequality queries against an indexed string column can give the wrong result.

The linked demonstration program creates a table of one column and ten rows, containing "S_00000", "S_00001", .... It then checks a comparison of the form `table.where('col < S_00000')` for `<`, `<=`, and `==`. When the column is not indexed, all the comparisons return the correct result set. If the column is indexed, the `<` comparison returns 0 rows, but the other comparisons are correct.

This error does not occur if the out-of-context call to `Table.where` at line 25 is removed.

Tested against PyTables @ e439637.

**Comment by FrancescAlted** [comment]
This was probably solved in 035dbd5.  With that, this is the output that I am getting:

```
 ------- Unindexed ---------
(0, 0, 1, 1)
(1, 1, 1, 2)
(2, 2, 1, 3)
(3, 3, 1, 4)
(4, 4, 1, 5)
(5, 5, 1, 6)
(6, 6, 1, 7)
(7, 7, 1, 8)
(8, 8, 1, 9)
(9, 9, 1, 10)
(10, 10, 0, 10)
 -------- Indexed --------
 This should look the same as above
(0, 0, 1, 1)
(1, 1, 1, 2)
(2, 2, 1, 3)
(3, 3, 1, 4)
(4, 4, 1, 5)
(5, 5, 1, 6)
(6, 6, 1, 7)
(7, 7, 1, 8)
(8, 8, 1, 9)
(9, 9, 1, 10)
(10, 10, 0, 10)
```
