### ISSUE TITLE
Unicode, python 3

### ISSUE THREAD

**Issue by potyt** [PyTables/PyTables#268]
Python 3.3.2
PyTables 3.0.0
NumPy 1.7.1

It seems that it isn't possible to create a table to store numpy.str dtypes, where this worked before in Python 2.x. Guessing this is because the default python string is now unicode and numpy.str types have a 'kind' of U.

I don't declare table types using the XXXCol method, they are created dynamically by calling create_table, passing an appropriate description object. Using this method I am not sure how it I can create a table to store strings - all the NumPy string types ultimately resolve to unicode as far as I can see.

Just a bit surprised that this doesn't work out of the box (or isn't handled somehow). Am I missing a numpy.old_str type or something that gets around this? I think I might be able to declare manually things as dtype('S', 10) and have support, but in my case the dtype is being constructed 'naturally' from the Python object by NumPy.

I saw a discussion earlier that said that unicode support was targetted for PyTables v3. Any obvious solutions I am missing?

**Comment by andreabedini** [comment]
Re reading this discussion it seems it went off track at some point. The original problem doesn't seem about supporting unicode as table columns but more like a python2/3 issue. Perhaps we should close this and open another issue.
