### ISSUE TITLE
tables.group.Group class should have __getitem__ attribute

### ISSUE THREAD

**Issue by vshkolyar** [PyTables/PyTables#270]
Reason for bugs or in other words inconsistency with DRY (don't repeat yourself), SSOT (Single Source of Truth) or whatever it's called software principles:
If developer creates some object, property, in his code that he can refer to it latter in his code, he wand there will be only one generic way to do that. In case of the group, if I create for example root group in HDF by using string value, I will create some static field that I will use to creation and retrieving of the group/table. Or for some generic use the name could be passed to me as var by user of my method and I in my code should not know what is the name, I only will want to pass the name to root group and retrieve the son node by name. Or for example in refactoring of some large code base: I will want to change only the name of the node in the static string field value and not to remember to seek in code for places where the string used as code and not the string.
Sorry if the description is not the best, English is not my mother tongue :)

**Comment by FrancescAlted** [comment]
Closing as I don't understand that very well either.
