### ISSUE TITLE
record array is made up of numpy.void, not numpy.record

### ISSUE THREAD

**Issue by potyt** [PyTables/PyTables#271]
If I manually create a record array, from say, a list of tuples, I can individually pull out "rows" of this and they are of type numpy.record. This means I can do things, such as:

    arr[0].price

and it works.

If I get an array from table.read, or read_where, and then do a .view(np.recarray) I get a record array that looks correct at first glance, but is actually made up of numpy.void objects. And the above code fails because arr[0] is a numpy.void and I cannot call .price on it.

From a users perspective, you shouldn't have seemingly identical looking objects (np.recarray) that behave differently depending on how they were created. I suspect this is a NumPy bug, but interested in your thoughts seeing as it is a fairly common use-case for PyTables.

Thanks

**Comment by FrancescAlted** [comment]
Out of scope of PyTables.
