### ISSUE TITLE
ValueError on table.append when chunksize > certain threshold

### ISSUE THREAD

**Issue by smartexpert** [PyTables/PyTables#279]
The problem seems to be related to the chunksize. 

Please see http://stackoverflow.com/questions/18380139/pytables-valueerror-rows-parameter-cannot-be-converted-into-a-recarray-object-c for context.

I have successfully written the entire dataset using chunksizes of 100000. However when the chunksize is increased to anything above 200000, in the following case 250000, the initial create table flows smoothly, however upon the second or third append the error is raised.

```python
Traceback (most recent call last):
  File "D:\BigData\csvtohdf2.py", line 148, in <module>
    f.get_node('/','df').append(df)
  File "C:\Python27\lib\site-packages\tables\table.py", line 2229, in append
    "The error was: <%s>" % (str(self), exc))
ValueError: rows parameter cannot be converted into a recarray object compliant with table '/df (Table(250000,), shuffle, blosc(4)) '''. The error was: <>
'''

**Comment by FrancescAlted** [comment]
Closing this because we lack the self-contained example.
