### ISSUE TITLE
Fix for gh-206 makes false assumption about table shape

### ISSUE THREAD

**Issue by dhinds** [PyTables/PyTables#285]
`_calc_nrowsinbuf()` in `leaf.py` does this:

    if nrowsinbuf < chunksize:
        nrowsinbuf = chunksize

This sets the number of *rows* to buffer to be (for an array) at least the number of *elements* in a chunk, which is very bad if the number of elements per row is not small.

For example, I've got a 2-D array with ~1 million columns and 400,000 rows, and a chunkshape of (1,131072), so this tries to buffer 131072 rows, which requires 128GB of memory.

I think maybe this should instead be:

    if nrowsinbuf < chunkshape[0]:
        nrowsinbuf = chunkshape[0]

Or, maybe this should only be done when `len(chunkshape)==1`?

**Comment by FrancescAlted** [comment]
Although I wanted to address this for 3.2.0, this needs more attention, so pushing this to another milestone again.

**Comment by FrancescAlted** [comment]
Fixed using you initial suggestion of only increasing the `nrowsinbuf` value only for tables (rev b073c2b)
