### ISSUE TITLE
ValueError: too many inputs

### ISSUE THREAD

**Issue by iamdionysus** [PyTables/PyTables#286]
When I call table.where('(x=value1) | (x=value2) | (x==value3) ...'), it's working if the condition x=value n is small ( n < 30?) but if it's big, it raises ValueError: too many input
When I followed the error on debugger it's causing error below at return compiled_ex(_arguments, *_kwargs)

numexpr/necompiler.py

def evaluate(...)
    try:
        compiled_ex = _numexpr_cache[numexpr_key]
    except KeyError:
        compiled_ex = _numexpr_cache[numexpr_key] = \
                      NumExpr(ex, signature, *_context)
    kwargs = {'out': out, 'order': order, 'casting': casting,
              'ex_uses_vml': ex_uses_vml}
    return compiled_ex(_arguments, **kwargs)

**Comment by ronkiker** [comment]
doesn't look like this has changed. anyone find a workaround?

**Comment by andriimazur93** [comment]
i had the same issue with pandas this was throwing ValueError: too many inputs
df.eval(some_expression_to_evaluate)

changing it to 
df.eval(some_expression_to_evaluate, engine="python")
solved a problem :)
