### ISSUE TITLE
remove_rows(0) tries to remove all rows

### ISSUE THREAD

**Issue by hillierdani** [PyTables/PyTables#304]
When calling table.remove_rows(0) the following line in leaf.py
start, stop, step = utilsextension.get_indices(start, stop, step, long(nrows))
converts start=0,stop=None,step=None (the defaults of remove_rows) to start=0,stop=nrows,step=1.
The documentation string of remove_rows says that providing 0 will remove the first row.

**Comment by FrancescAlted** [comment]
I don't see this in documentation anymore, so maybe anyone else fixed it?
