### ISSUE TITLE
Remove the old API

### ISSUE THREAD

**Issue by avalentino** [PyTables/PyTables#320]
Complete the transition to the new ([PEP8](http://www.python.org/dev/peps/pep-0008) compliant) API.

- [ ] remove warnings
- [x] remove previous_api()
- [x] remove `_past.py`
- [x] keep pt2to3

See also #224.

**Comment by andreabedini** [comment]
This is a first stab, it removes `_past.py` and all occurrences of `previous_api` and `previous_api_property`. What's left?

PS: sorry for the mess above, I had to rebase the PR to the top of develop.
