### ISSUE TITLE
BUG: can fileno() return -1?

### ISSUE THREAD

**Issue by jreback** [PyTables/PyTables#328]
https://github.com/pydata/pandas/issues/5999

we have this 'feature' where a user can manually call fsync

I can't repro this but I think this is happening with 3.1rc1 (which Debian guys are testing with)

I am working around but not sure if this is a valid return code?

**Comment by FrancescAlted** [comment]
Uh, not sure that we have enough resources to further investigate on the s390x platform, so closing.  Feel free to reopen if needed.
