### ISSUE TITLE
Current "pip install tables" breaks with newer version of Cython (0.21)

### ISSUE THREAD

**Issue by EricR86** [PyTables/PyTables#394]
Hello,
This is a bug specifically to the current pip release of PyTables. As of Cython version 0.21 the setup.py in the current PyPi release of PyTables breaks on a thrown ImportError.

```
$ cython --version
Cython version 0.21
$ pip install tables
Downloading/unpacking tables
  Running setup.py egg_info for package tables
    * Using Python 2.7.3 (default, Apr 10 2013, 06:20:15)
    * Found numpy 1.9.0 package installed.
    * Found numexpr 2.4 package installed.
    .. ERROR:: You need Cython 0.13 or greater to compile PyTables!
    Complete output from command python setup.py egg_info:
    * Using Python 2.7.3 (default, Apr 10 2013, 06:20:15)
```

Notably the previous version 0.20.2 does not have this issue (presumably because the python module still existed for that version).

As far as I can tell though the current source release works fine for version checking in setup.py with newer versions of Cython. This bug is only for the current PyPi release.

It would be great to get a minor point release (for setup.py strictly) to fix the installation process.

Thank you for your time.

**Comment by andreabedini** [comment]
@EricR86, if you are still affected by this @FrancescAlted is preparing a 3.2.0 release soon
