### ISSUE TITLE
No module named utilsextension

### ISSUE THREAD

**Issue by zhilongjia** [PyTables/PyTables#395]
when import tables (3.1.1) in python 2.7 after install it successfully, there is an error. 

located in **init**.py
---> 82 from tables.utilsextension import (
     83     get_pytables_version, get_hdf5_version, blosc_compressor_list,
     84     blosc_compcode_to_compname_ as blosc_compcode_to_compname,

ImportError: No module named utilsextension

It seems due to the utilsextension and utilsExtension problems.

**Comment by behen** [comment]
Hey guys! I'm having the same problem but I don't understand the answer. What does it mean to change to another directory? I have the folder tables-3.2.0 which I put into the interpreters list and then try to import it, which doesn't work.

**Comment by andreabedini** [comment]
@behen pytables has some c python extensions that have to be compiled first. If you use OS X or linux, I'd suggest you install pytables using python's package installer `pip install tables`. If you are on windows you might need to use conda.

**Comment by behen** [comment]
I have tried that already but get the following error :(


Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_privatefolder/tables
Storing debug log for failure in /home/privatefolder/.pip/pip.log

**Comment by andreabedini** [comment]
@behen can you make a [gist](https://gist.github.com/) with the debug log in /home/privatefolder/.pip/pip.log ?

**Comment by behen** [comment]
Sry I'm a complete beginner...
I hope this is what you asked for: 

https://gist.github.com/behen/04a2911f870bc4cc0e48/download#

**Comment by andreabedini** [comment]
@behen the relevant part is `ERROR:: Could not find a local HDF5 installation`, PyTables extends on top of the HDF5 library. Make sure you have that installed first.

**Comment by SarahRQazi** [comment]
I have successful install tables. Here is the log.
```
Collecting tables
  Downloading https://files.pythonhosted.org/packages/d5/5e/0463e9a2ae44838e36ca81dfe8a6e056b15cc15be77e7f8feae116f02ec7/tables-3.5.2-cp37-cp37m-manylinux1_x86_64.whl (4.3MB)
    100% |████████████████████████████████| 4.3MB 3.4MB/s
Requirement already satisfied: numpy>=1.9.3 in /home/hpcc/.linuxbrew/lib/python3.7/site-packages (from tables) (1.16.1)
Collecting mock>=2.0 (from tables)
  Downloading https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /home/hpcc/.linuxbrew/lib/python3.7/site-packages (from tables) (1.12.0)
Collecting numexpr>=2.6.2 (from tables)
  Downloading https://files.pythonhosted.org/packages/2c/69/274c2b81b9bdf7783150461c8982f23248dc917402ed4c6f8aa4b90bb98e/numexpr-2.7.0-cp37-cp37m-manylinux1_x86_64.whl (162kB)
    100% |████████████████████████████████| 163kB 10.9MB/s
Installing collected packages: mock, numexpr, tables
Successfully installed mock-3.0.5 numexpr-2.7.0 tables-3.5.2
```
But when I run program which require tables it again gives me error.
```
Traceback (most recent call last):
  File "conifer.py", line 31, in <module>
    import conifer_functions as cf
  File "/home/hpcc/tools/conifer_v0.2.2/conifer_functions.py", line 28, in <module>
    from tables import *
ImportError: No module named tables
```
 So what should I do to resolve this?

**Comment by tomkooij** [comment]
@SarahRQazi : You are experiencing import problems that are outside of the scope of pytables. Something is wrong with your python installation and/or `venv`.

We cannot help. I suggest you try anaconda / miniconda and/or start with a fresh python installation.
