### ISSUE TITLE
PyTables & Python 3.4.1: Umlaut in StringCol raising TypeError

### ISSUE THREAD

**Issue by andi1984** [PyTables/PyTables#396]
Hi,

I want to store some german words (including umlauts) into a StringCol. Unfortunately any umlaut inside the text is raising a ``TypeError: invalid type (<class 'str'>) for column note``.

Isn't it possible to store umlauts inside a StringCol? Or how can I fix this issue? The strings are read out from a csv file via csv.reader.

**Comment by FrancescAlted** [comment]
Nope.  `StringCol` only supports pure ascii codification.  Sorry about that.  In case you are interested in implementing full support for Unicode, maybe a new `UnicodeCol` would be nice to have.  PR are very welcome.  Closing.
