### ISSUE TITLE
Cannot create a table in an existing file..

### ISSUE THREAD

**Issue by guziy** [PyTables/PyTables#398]
Hi:

Could you please help me debug this problem. I have created a file with pytables and was trying to modify it in append mode, but something went wrong and now I am not able to create the table and get the exception below. I will probably recreate the file completely, but if there is a quick solution, it would save me lots of time:

<pre>
6 Traceback (most recent call last):
  7   File "src/crcm5/analyse_hdf/do_export_to_hdf_guillimin_ITFS.py", line 164, in <module>
  8     main()
  9   File "src/crcm5/analyse_hdf/do_export_to_hdf_guillimin_ITFS.py", line 142, in main
 10     dm.export_to_hdf(var_list = var_names, file_path= hdf_file_path, mode="a")
 11   File "/gs/project/ugh-612-aa/huziy/PythonProjects/RPN/src/crcm5/model_data.py", line 977, in export_to_hdf
 12     filters=tb.Filters(complevel=5))
 13   File "/gs/project/ugh-612-aa/huziy/virtualenvs/default-py2.7/lib/python2.7/site-packages/tables/file.py", line 1067, in create_table
 14     chunkshape=chunkshape, byteorder=byteorder)
 15   File "/gs/project/ugh-612-aa/huziy/virtualenvs/default-py2.7/lib/python2.7/site-packages/tables/table.py", line 867, in __init__
 16     byteorder, _log)
 17   File "/gs/project/ugh-612-aa/huziy/virtualenvs/default-py2.7/lib/python2.7/site-packages/tables/leaf.py", line 262, in __init__
 18     super(Leaf, self).__init__(parentnode, name, _log)
 19   File "/gs/project/ugh-612-aa/huziy/virtualenvs/default-py2.7/lib/python2.7/site-packages/tables/node.py", line 269, in __init__
 20     self._v_objectid = self._g_create()
 21   File "/gs/project/ugh-612-aa/huziy/virtualenvs/default-py2.7/lib/python2.7/site-packages/tables/table.py", line 1019, in _g_create
 22     self._v_new_title, self.filters.complib or '', obversion)
 23   File "tableextension.pyx", line 212, in tables.tableextension.Table._create_table (tables/tableextension.c:3079)
 24 tables.exceptions.HDF5ExtError: Problems creating the table
</pre>

Thanks

**Comment by FrancescAlted** [comment]
Are you still having this problem?  If so, can you send a minimal sample code showing the problem?

**Comment by guziy** [comment]
No,

I have recreated the file and do not use indexing. Everything works now.... I did not have time to play with it then, so no self contained example ....
