### ISSUE TITLE
pytables import throws floating point error

### ISSUE THREAD

**Issue by cekees** [PyTables/PyTables#403]
I was trapping floating point errors in a larger application and found that 'import tables' throws a floating point tables. In particular, tables.idxutils. I'm running python2.7 and  https://pypi.python.org/packages/source/t/tables/tables-2.4.0.tar.gz. The floating point exception doesn't seem to cause any real errors.

**Comment by FrancescAlted** [comment]
So as there is not a better suggestion on how to fix this and apparently this is not very harmful, I am going to close the ticket, but feel free to re-open it in case you find a way to workaround this.

**Comment by andreabedini** [comment]
I might to check this at some point so I'll assign myself.
