### ISSUE TITLE
table.where query does not seem to be able to find rows...

### ISSUE THREAD

**Issue by guziy** [PyTables/PyTables#409]
Hi:

I am creating a big table but I cannot find the rows which are supposed to be there using ```table.where```. But ```table.get_where_list()``` does find the rows in question (see the screenshot, **Note that there is no output as a result of the loop in table.where**). 

![screen shot 2014-12-08 at 17 58 36](https://cloud.githubusercontent.com/assets/900941/5349065/df8c3dca-7f03-11e4-8c41-1b14faf5a40b.png)

I was trying to reproduce it with smaller dummy files but no luck... Even when I select a table using ptrepack, the problem goes away... 

Not indexing columns also seems to fix the problem, except in this case querying is very slow....

**Comment by alexfields** [comment]
Possibly related to #319, pydata/pandas#8265, and pydata/pandas#9676

**Comment by FrancescAlted** [comment]
This has been hopefully fixed.  See #319 for details.
