### ISSUE TITLE
Problem with cArray and BLOSC (Could not wait on barrier (init))

### ISSUE THREAD

**Issue by lucapinello** [PyTables/PyTables#411]
I have a huge matrix stored in a carray with Float32 atom type and blosc compression:

/matrix_computed (CArray(1236248, 1236248), shuffle, blosc(1)) ''

Often when I try to load submatrices using the slicing notation (for example m[5000:10000,5000:10000]) I get the following error and everything freezes:

Could not wait on barrier (init)

I suspect this is due to the BLOSC threading implementation  since when using max_blosc_threads=1 the problem doesn't occur.

Is this a known bug?

Thanks!

Luca

**Comment by esc** [comment]
@avalentino did you merge using ``subtree-merge-blosc.sh``?

**Comment by avalentino** [comment]
@esc no, Blosc 1.5.1 has been merged manually.
Version 1.5.2 instead has been merged using the script.
It is not clear to me what went wrong with version 1.5.1 but the script didn't work correctly.

**Comment by esc** [comment]
Okay, I came here because I saw:

```
Could not wait on barrier (init)
```

While running some tests using a debug build of python trying to debug a segfault using python-blosc.

I then read in this thread, that upgrading c-blosc might help, so I tried to upgrade using the subtree-merge-blosc.sh script and that failed badly. I am still working on the details, but it wasn't a problem with running it from non-root directory.

**Comment by esc** [comment]
However I recently used the script in bcolz to upgrade to blosc 1.5.2 and I *think* it worked correctly, at least the ``blosc.h`` claims to be correct and a recursive diff of the ``c-blosc`` subdirectory with a clone pointing to the ``v1.5.2`` tag reports they are identical.

**Comment by avalentino** [comment]
Is it possible that there is something strange in `c-blosc` tag 1.5.1 that confuses the script?

**Comment by esc** [comment]
No, I just manually merged v1.5.0 and then used the script to merge v1.5.1 and v1.5.0...

**Comment by esc** [comment]
@avalentino I'll be keeping an eye on it, best to watch the behaviour closely in future and cc me in case you run into any weird issues. I might have a few workarounds up my sleeve.

**Comment by avalentino** [comment]
@esc OK, thanks

**Comment by FrancescAlted** [comment]
I have decided to downgrade to Blosc 1.4.1 for PyTables 3.2.0.  The reason for that is that, starting with blosc 1.5.0, there is not a global lock any longer, so this create troubles when using PyTables in multithreaded environments.  Until a lock is created inside PyTables when calling blosc, going back to 1.4.1 is the easiest approach.

**Comment by esc** [comment]
hrmpf!

**Comment by FrancescAlted** [comment]
Is that a +1?

**Comment by esc** [comment]
Yes a :+1: but with regrets.

**Comment by FrancescAlted** [comment]
Anyone wanting to see a newer version of blosc in PyTables will only have to implement a lock inside PyTables and we are done!
