### ISSUE TITLE
Can't remove a group from a file

### ISSUE THREAD

**Issue by guziy** [PyTables/PyTables#416]
Can someone tell  me how to fix this?

<pre>
In [3]: h.remove_node("/daily_climatology")
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-3-e9c8af0e279c> in <module>()
----> 1 h.remove_node("/daily_climatology")

/skynet3_rech1/huziy/python_virtualenvs/tutorial/lib/python2.7/site-packages/tables/file.pyc in remove_node(self, where, name, recursive)
   1787
   1788         obj = self.get_node(where, name=name)
-> 1789         obj._f_remove(recursive)
   1790
   1791     removeNode = previous_api(remove_node)

/skynet3_rech1/huziy/python_virtualenvs/tutorial/lib/python2.7/site-packages/tables/node.pyc in _f_remove(self, recursive, force)
    561             self._g_remove_and_log(recursive, force)
    562         else:
--> 563             self._g_remove(recursive, force)
    564
    565     def _g_remove_and_log(self, recursive, force):

/skynet3_rech1/huziy/python_virtualenvs/tutorial/lib/python2.7/site-packages/tables/group.pyc in _g_remove(self, recursive, force)
    934
    935         # Remove the node itself from the hierarchy.
--> 936         super(Group, self)._g_remove(recursive, force)
    937
    938     def _f_copy(self, newparent=None, newname=None,

/skynet3_rech1/huziy/python_virtualenvs/tutorial/lib/python2.7/site-packages/tables/node.pyc in _g_remove(self, recursive, force)
    541         # hdf5extension operations:
    542         # Remove the node from the HDF5 hierarchy.
--> 543         self._g_delete(parent)
    544
    545     def _f_remove(self, recursive=False, force=False):

/skynet3_rech1/huziy/python_virtualenvs/tutorial/lib/python2.7/site-packages/tables/hdf5extension.so in tables.hdf5extension.Node._g_delete (tables/hdf5extension.c:8577)()

HDF5ExtError: HDF5 error back trace

  File "H5L.c", line 609, in H5Ldelete
    unable to delete link
  File "H5L.c", line 2344, in H5L_delete
    can't unlink object
  File "H5Gtraverse.c", line 861, in H5G_traverse
    internal path traversal failed
  File "H5Gtraverse.c", line 641, in H5G_traverse_real
    traversal operator failed
  File "H5L.c", line 2301, in H5L_delete_cb
    unable to remove link from group
  File "H5Gobj.c", line 1020, in H5G_obj_remove
    can't remove object
  File "H5Gstab.c", line 386, in H5G__stab_remove
    unable to remove entry
  File "H5B.c", line 1676, in H5B_remove
    unable to remove entry from B-tree
  File "H5B.c", line 1402, in H5B_remove_helper
    key not found in leaf node
  File "H5Gnode.c", line 872, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1617, in H5O_link
    unable to adjust object link count
  File "H5O.c", line 1500, in H5O_link_oh
    link count would be negative

End of HDF5 error back trace

problems deleting the node ``/daily_climatology``
</pre>

**Comment by FrancescAlted** [comment]
Uh, no idea.  Maybe a corrupted h5 file?  Can you send self-contained example reproducing the problem?

**Comment by guziy** [comment]
Hi Francesc:

Sorry I could not reproduce it with a smaller, and this one was 100s GB, I am not sure if it is still around... Do you think it is best to close the issue?

Cheers

**Comment by FrancescAlted** [comment]
If the file is not available and issue cannot be reproduced, then yes, it is better to close this.  Feel free to open another issue in case you get into problems again.

**Comment by joseortiz3** [comment]
If this helps anyone, I encountered this error after I interrupted writing to an HDF file. The key and its data in the file became impossible to remove. The rest of the file and the other keys still worked.
