### ISSUE TITLE
Sourceforge mailing list still in docs

### ISSUE THREAD

**Issue by taldcroft** [PyTables/PyTables#420]
Both the [sphinx docs](http://pytables.github.io/FAQ.html?highlight=mailing) and the [pytables.org docs](http://www.pytables.org/moin/FAQ#I.27mhavingproblems.HowcanIgetsupport.3F) provide the old sourceforge mailing list as the contact point for support.  I gather this is no longer the case after #81.  It would be good to fix this to avoid users (like me) needlessly going through the process to join the old sourceforge group to post a question.

**Comment by FrancescAlted** [comment]
You are right.  As always, a PR would be very welcome!

**Comment by avalentino** [comment]
Docs in the source repo should be fixed now.

@FrancescAlted I still have problems to update the wiki at http://www.pytables.org/moin/.
Probably we should just shut it down.

**Comment by FrancescAlted** [comment]
@avalentino Yes, I think you are right.  The box where the pytables.org site is hosted is really old (running Ubuntu Hardy 8.04 :P) and after being the target of MoinMoin attacks  recently, it seriously need an upgrade, which is going to take time (if it happens at all).

So, I decided to shutdown www.pytables.org for the time being (the site is still available in xano.pytables.org, just in case someone wants to copy something to the pytables.github.io site).  Tell me if you need something else and sorry for not being able to properly continue maintaining www.pytables.org.

**Comment by sbesson** [comment]
So with the wiki being turned off, is https://pytables.github.io/downloads.html the definitive page to link at the downloads or is it better to link at SourceForge?

**Comment by FrancescAlted** [comment]
Yes, the link you sent is the canonical one for downloads.

**Comment by sbesson** [comment]
Thanks @FrancescAlted, we will update our documentation to point at it.

**Comment by avalentino** [comment]
> So, I decided to shutdown www.pytables.org for the time being (the site is still available in xano.pytables.org, just in case someone wants to copy something to the pytables.github.io site). Tell me if you need something else and sorry for not being able to properly continue maintaining www.pytables.org.

Thanks @FrancescAlted.
If I remember well most of the material should already be in the the sphinx docs. I will give a look.
Do you think it is possible to set up some form of redirection from www.pytables.org to https://pytables.github.io?

**Comment by andreabedini** [comment]
you can move `pytables.github.io` directly to `www.pytables.org`, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/. `pytables.github.io` will keep working and redirect to the new name `www.pytables.org`.

**Comment by avalentino** [comment]
> you can move pytables.github.io directly to www.pytables.org, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/. pytables.github.io will keep working and redirect to the new name www.pytables.org.

easy! thanks @andreabedini !

@FrancescAlted is it OK for you?

**Comment by FrancescAlted** [comment]
Sure thing.  Just tell me if you need action on my side.

**Comment by avalentino** [comment]
> Sure thing. Just tell me if you need action on my side.

yes, looking at this https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/ it seems that it is necessary to update some setting with your DNS provider.

**Comment by FrancescAlted** [comment]
I have transferred the pytables.org domain to the NumFOCUS, so I am not the responsible of it anymore.   As @scopatz is in NumFOCUS board, he might be able to get in contact the proper person to take the necessary actions.

**Comment by andreabedini** [comment]
if you need help I have done this _so many_ times

**Comment by andreabedini** [comment]
@FrancescAlted I noticed the old website is still available at http://www2.pytables.org/ redirected from http://pytables.org/ which is linked from the github pytables organisation profile.

**Comment by FrancescAlted** [comment]
Fixed.  Now http://www2.pytables.org/ is not available anymore.  Thanks!

**Comment by FrancescAlted** [comment]
I added a redirection so that www.pytables.org -> pytables.github.io. This is a temporary solution though.

**Comment by FrancescAlted** [comment]
Also, I posted a request for a more permanent solution to the NumFocus mailing list:
https://groups.google.com/forum/#!topic/numfocus/cilcv0hUilc

**Comment by andreabedini** [comment]
@FrancescAlted could you update me on what's going on with the website? the DNS hasn't changed and at the moment we are _delocalised_ between pytables.github.io and www.pytables.org

**Comment by FrancescAlted** [comment]
I am currently trying to make the CNAME www.pytables.org -> pytables.github.io to happen, but talking with NumFocus is taking time and I don't know if that could enter for 3.2.0, so moving to "Next Tasks".

**Comment by FrancescAlted** [comment]
Finally, the CNAME www.pytables.org -> pytables.github.io seems active.  Please tell me in case you have problems.  Closing.

**Comment by joshmoore** [comment]
Chrome/OSX reports:
```
This webpage has a redirect loop
ERR_TOO_MANY_REDIRECTS
```

**Comment by FrancescAlted** [comment]
You DNS probably needs some time to refresh.  Please try again in a few minutes and if nothing changes, tell me again.

**Comment by joshmoore** [comment]
www.pytables.org now works, thanks.
pytables.org is:
```
This webpage is not available
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by sbesson** [comment]
Seconding @joshmoore comment, you may also want to update the description of https://github.com/PyTables/pytables.github.com to point at http://www.pytables.org/ instead of http://pytables.org/ to match the CNAME.

**Comment by FrancescAlted** [comment]
Now I have added pytables.org -> www.pytables.org, so this would be enough.
