### ISSUE TITLE
cannot import name blosc_get_complib_info_

### ISSUE THREAD

**Issue by lixinfan** [PyTables/PyTables#421]
HI, 

I was stuck by an "import tables" error for a couple of days and couldn't figure out any useful solutions.  The symptom is as follows: 

 In [1]: import tables
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-389ecae14f10> in <module>()
----> 1 import tables

/usr/local/lib/python2.7/dist-packages/tables/__init__.pyc in <module>()
     80 
     81 # Necessary imports to get versions stored on the cython extension
---> 82 from tables.utilsextension import (
     83     get_pytables_version, get_hdf5_version, blosc_compressor_list,
     84     blosc_compcode_to_compname_ as blosc_compcode_to_compname,

ImportError: cannot import name blosc_get_complib_info_

===========================================
Seems this error has something to do with a warning message during installation of PyTables (versions 2.4.0 / 3.0.0 / 3.1.1):
 
sudo python setup.py build_ext --inplace
* Using Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
* Found numpy 1.9.1 package installed.
* Found numexpr 2.2.2 package installed.
* Found Cython 0.21.1 package installed.
* Found HDF5 headers at ``/usr/include``, library at ``/usr/lib``.
* Found LZO 2 headers at ``/usr/include``, library at ``/usr/lib``.
* Skipping detection of LZO 1 since LZO 2 has already been found.
* Found bzip2 headers at ``/usr/include``, the library is located in the standard system search dirs.
* Found blosc headers at ``/usr/local/include``, library at ``/usr/local/lib``.
.. WARNING:: Could not find the blosc runtime.
   The blosc shared library was *not* found in the default library
   paths. In case of runtime problems, please remember to install it.
running build_ext

===============================================
However, I double-checked that libblosc.so is indeed installed there (/usr/local/lib) and my LD_LIBRARY_PATH seems ok too. (="/opt/ros/fuerte/lib:/opt/ROOT/v5-34/lib:/usr/local/cuda-6.5/lib64:/usr/local/lib").    

So I couldn't figure out a) why "import tables" failed and b) why libblosc.so was not found during installation of PyTables.  Any assistance you may render are appreciated. Thanks in advance.

**Comment by FrancescAlted** [comment]
No idea.  Is this still happening to you or have you found a solution?  Also, it seems that you have blosc installed previously to PyTables.  Could you try removing your blosc library so that setup.py would try to use the included blosc instead?  My guess is that the blosc version in your system is a bit old.

**Comment by lixinfan** [comment]
Yes, the problem is solved after re-installing some old libraries including blosc.   Thanks for the suggestion.

**Comment by FrancescAlted** [comment]
Great.  Closing.
