### ISSUE TITLE
Set Appveyor?

### ISSUE THREAD

**Issue by andreabedini** [PyTables/PyTables#424]
Hi there,

could anyone with windows skills set up continuous integration with [Appveyor](http://www.appveyor.com/) ? I don't think I have touched windows since '98 and even then I never compiled anything on it. But if somebody sets it up I can make sure I don't break something on win.

Also, I don't know what's people's workflow on window, use anaconda? whatever the typical setup is, we should try to cover it in our CI.

**Comment by andreabedini** [comment]
these two repositories can be of help

- [python-appveyor-demo](https://github.com/ogrisel/python-appveyor-demo)
- [python-appveyor-conda-example](https://github.com/rmcgibbo/python-appveyor-conda-example)

**Comment by joshmoore** [comment]
Hi @andreabedini. Thanks for the reminder. I had recently seen Appveyor and wanted to give it a try. The timing is great because the [OME](http://github.com/openmicroscopy)-supported Windows build has just broken due to our migration. I'll look into extracting that configuration to an appveyor build.

cc: @sbesson

**Comment by andreabedini** [comment]
Hi @joshmoore,
how do people use PyTables on Windows? Through conda binary packages? Who builds (and how) those packages? Can we build them? (with Travis CI and Appveyor for example). In short, what's our current level of support for Windows? If it was for me I'd declare the Window platform unsupported :smiling_imp: Thanks for taking on this!

**Comment by joshmoore** [comment]
> how do people use PyTables on Windows? Through conda binary packages? 

Dunno, though I'd be very interested in hearing.

> Who builds (and how) those packages? Can we build them? (with Travis CI and Appveyor for example). 

As far as I understand, ContinuumIO/conda/pydata/et al. have a non-public repo where the PyTables recipes for conda are kept. These builds then go to the `anaconda`-owner binstar package: https://binstar.org/anaconda/pytables

I've never seen the files, so I can't integrate them into travis/appveyor. My plan will initially be to just migrate the OME build to appveyor and see where we end up. In general, I would like to see the conda recipe being tested for each PR.

> In short, what's our current level of support for Windows? If it was for me I'd declare the Window platform unsupported.

Heh. I'll leave changes in the support status for others to debate. OME offered to provide a Windows build of PyTables to improve the coverage somewhat. If appveyor can be used to handle this per PR, it'd be significantly better, though I'm not sure if the "heavy" test configuration will be able to run to completion.

**Comment by andreabedini** [comment]
> As far as I understand, ContinuumIO/conda/pydata/et al. have a non-public repo where the PyTables recipes for conda are kept. These builds then go to the anaconda-owner binstar package: https://binstar.org/anaconda/pytables

Am I the only one that find worrying that someone else is distributing closed-source binaries of PyTables?

**Comment by joshmoore** [comment]
> Am I the only one that find worrying that someone else is distributing closed-source binaries of PyTables?

@PyTables/maintainers : any comments?

**Comment by avalentino** [comment]
> Am I the only one that find worrying that someone else is distributing closed-source binaries of PyTables?

PyTables in Anaconda is not the only case of third party binary distribution.
IMO it is fine as long as people keep contirbuting patches back to the main project.

In any case the PyTables does allow (source and) binary distribution even as part of a closed source SW AFAIK.

**Comment by andreabedini** [comment]
I understand it's perfectly acceptable given the licence terms, I only consider it a big lack of transparency.

**Comment by andreabedini** [comment]
closing this in light of #426
