### ISSUE TITLE
ValueError use for field not found exemptions in Table class

### ISSUE THREAD

**Issue by c-wilson** [PyTables/PyTables#428]
I propose that the requesting a non-existant field from a Table raise something other than a ValueError exemption (ie a KeyError or something similar).

For example: 
<code> foo = file.root.a_table[:]['non-existant-field']

raises
<code>ValueError: field named non-existant-field not found

This would make it easier to catch field-not-found errors in a try/except block, which often have a different meaning to programs than the ubiquitous ValueError. For example it might be useful to gracefully catch a field not found error while raising ValueErrors.

Thanks, I won't be offended if there is disagreement and this is closed.

**Comment by andreabedini** [comment]
:+1:

**Comment by FrancescAlted** [comment]
I am also +1 on this.  Would you mind to provide a pull request?

**Comment by c-wilson** [comment]
Ok, so I looked into this a bit, and I think that is actually not a pyTables issue at all. Rather, it looks like pyTables is returning a numpy.ndarray with all of the rows in the table and numpy is raising the ValueError for the field not existing.

I'm thinking that I can either raise this issue with numpy or subclass ndarray with a different exemption implementation. The latter is probably going to create a mess later on. What do you think?

**Comment by andreabedini** [comment]
I'd say open an issue on numpy then

**Comment by FrancescAlted** [comment]
For what is worth, and in my opinion, NumPy really needs a much better error classification.  Closing this one.
