### ISSUE TITLE
"contains" where operator for strings

### ISSUE THREAD

**Issue by chriddyp** [PyTables/PyTables#430]
Hi all, just getting started with PyTables. From what I understand, the "`where`" operator uses `Numexpr`. 

From Numexpr's [list of supported functions](https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide#supported-functions) there is the `contains` operator:

```
 *contains(str, str): bool* -- returns True for every string in `op1` that contains `op2`
```

is this supported in PyTables? I tried an example in Pandas:

```
>>> pd.read_hdf('data.h5','atable', where=('op1 contains op2')).head()
SyntaxError: invalid syntax
```

**Comment by gdementen** [comment]
I have no idea if it is supposed to work, but contains is a function, not an operator, so you should try:
>>> pd.read_hdf('data.h5','atable', where='contains(op1, op2)').head()

**Comment by FrancescAlted** [comment]
Yes, @gdementen is correct, and the above should work.
