### ISSUE TITLE
Bad links in Readme file

### ISSUE THREAD

**Issue by cayetanobv** [PyTables/PyTables#431]
There are a couple of bad links in the README file:
- (Line 5) :URL: http://www.pytables.org/
- (Line 99) http://www.pytables.org/moin/HowToUse).

Proposed changes:
- (Line 5) :URL: http://pytables.github.io
- (Line 99) http://pytables.github.io/usersguide/index.html).

Thanks for your great work!

Cayetano Benavent

**Comment by avalentino** [comment]
Thanks @cayetanobv I fixed the link to the docs.

@scopatz for the home page URL it would be nice to  keep pytables.org but we need to redirect it to a valid page (http://pytables.github.io). Do you think it is possible?

See also #420:

> I have transferred the pytables.org domain to the NumFOCUS, so I am not the responsible of it anymore. As @scopatz is in NumFOCUS board, he might be able to get in contact the proper person to take the necessary actions.

**Comment by andreabedini** [comment]
what's the status with http://www.pytables.org/ at the moment it says 'it works!'

**Comment by andreabedini** [comment]
I thought we were going to host pytables.org on github pages as discussed in #420

**Comment by avalentino** [comment]
Yes, all the material is currently hosted on github.io.
Just I would like to maintain the domain name and make it point tho github.io pages.
I suppose it is a matter of configuring the DNS. Isn't it?

**Comment by andreabedini** [comment]
yes, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

basically `www.pytables.org` needs to be a cname for `pytables.github.io`, then you add a file CNAME in the repo as the instructions say and it's done.

**Comment by cayetanobv** [comment]
Thanks @avalentino @andreabedini  for the answer! I'm very pleased to help this project.

Cayetano Benavent

**Comment by FrancescAlted** [comment]
I added a redirection so that www.pytables.org -> pytables.github.io.  This is a temporary solution though.

**Comment by andreabedini** [comment]
:+1:

**Comment by avalentino** [comment]
OK, I'm closing this issue.
We should probably file a specific issue for a definitive solution.
I don't know if it is better to create a PyTables issue assigner do @scopatz or file an issue to numfocus directly (not clear in which way)
