### ISSUE TITLE
c-blosc calls need a thread lock

### ISSUE THREAD

**Issue by FrancescAlted** [PyTables/PyTables#437]
Starting with blosc 1.5.0, there is not a global lock inside blosc any longer, so this create troubles when using PyTables in multithreaded environments. Until a lock is created inside PyTables when calling blosc, going back to 1.4.1 is the easiest approach (see #411, #412).

In the future, and in order to be able to use newer versions of blosc, PyTables will need to acquire its own lock before calling blosc functions.

**Comment by FrancescAlted** [comment]
See also #448 .

**Comment by FrancescAlted** [comment]
See #448 too.

**Comment by jack-pappas** [comment]
Does PyTables really need a lock for blosc calls?

It seems to me like the responsibility for thread-safety protections (for concurrent blosc usage) should fall to the code calling into blosc. In this case, that's not PyTables, but the blosc HDF5 filter / plugin; PyTables only consumes blosc via the H5Z APIs so it shouldn't have to worry about implementation details of the filter.

**Comment by FrancescAlted** [comment]
Yes, I think you are right.  Will move this issue to Blosc/hdf5 repo then.

**Comment by andreabedini** [comment]
good point thanks @jack-pappas
