### ISSUE TITLE
Cannot install PyTables

### ISSUE THREAD

**Issue by arcys** [PyTables/PyTables#446]
Hi,
Just tried to install PyTables using pip and found the following errors (in CentOS 7.1.1503):
Please advice, thank you very much!!

>h5cc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> echo $PATH
/home/carol/bin/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/carol/.local/bin:/home/carol/bin:/home/carol/.local/bin:/home/carol/bin:/opt/hdf5/latest/bin
> export HDF5_DIR=/opt/hdf5/latest/bin
> pip install tables
Downloading/unpacking tables
  Downloading tables-3.1.1.tar.gz (6.7MB): 6.7MB downloaded
  Running setup.py (path:/tmp/pip-build-WXFmKd/tables/setup.py) egg_info for package tables
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 2.7.5 (default, Jun 17 2014, 18:11:42)
    * Found numpy 1.7.1 package installed.
    * Found numexpr 2.4.4.dev0 package installed.
    * Found Cython 0.19 package installed.
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    Complete output from command python setup.py egg_info:
    /usr/bin/ld: cannot find -lhdf5

collect2: error: ld returned 1 exit status

* Using Python 2.7.5 (default, Jun 17 2014, 18:11:42)

* Found numpy 1.7.1 package installed.

* Found numexpr 2.4.4.dev0 package installed.

* Found Cython 0.19 package installed.

/usr/bin/ld: cannot find -lhdf5

collect2: error: ld returned 1 exit status

.. ERROR:: Could not find a local HDF5 installation.

   You may need to explicitly state where your local HDF5 headers and

   library can be found by setting the ``HDF5_DIR`` environment

   variable or by using the ``--hdf5`` command-line option.

**Comment by andreabedini** [comment]
Hi @arcys, it should be export HDF5_DIR=/opt/hdf5/latest`

**Comment by andreabedini** [comment]
feel free to reopen the issue if it still doesn't work.
