### ISSUE TITLE
Table access fails for row index > 2^31 with Python 2.x

### ISSUE THREAD

**Issue by DavidLP** [PyTables/PyTables#447]
_Description_
Due to the wrong use of xrange in the [table class](https://github.com/PyTables/PyTables/blob/develop/tables/table.py), the access (write and read) for larger tables fails with Python 2.x.

_Example_
```
import tables as tb
import numpy as np
array = np.zeros(3000000000, dtype=[('data', np.bool)])
with tb.open_file("test.h5", "w") as out_file_h5:
    table = out_file_h5.create_table(out_file_h5.root, name='Foo', description=array.dtype)
    table.append(array)
```

_Error_
OverflowError: Python int too large to convert to C long

_Explanation_
Xrange is used to determine the number of rows (e.g.: [here](https://github.com/PyTables/PyTables/blob/develop/tables/table.py#L1832)):
nrows = len(xrange(start, stop, step))
 
But xrange is [known](http://stackoverflow.com/questions/1482480/xrange2100-overflowerror-long-int-too-large-to-convert-to-int?rq=1) to not work for large numbers under Python 2.x. 

_Solution_
All occurences of the nrow calculation should be changed to
nrows = len(xrange(0, stop - start, step))

The result is the same and the speed comparable. 

_Additionaly_
A test case for larger files seems to be missing. If it helps I can provide a patch.

**Comment by FrancescAlted** [comment]
Excellent. A test case would be great. Looking forward to add this to forthcoming 3.2.0.

Enviat des del meu iPhone

El 03/05/2015, a les 13:48, D.-L.Pohl <notifications@github.com> va escriure:

**Comment by FrancescAlted** [comment]
Fixed in df34795.  If you want to provide a PR with a test case (probably for the hard suite), you are still welcome!

**Comment by andreabedini** [comment]
did the fix ever work for you @DavidLP ? on the current version I get an exception running your test code

```
  File "tables/tableextension.pyx", line 470, in tables.tableextension.Table._append_records (tables/tableextension.c:6321)
OverflowError: value too large to convert to int
```

because `Table._append_records` expects an `int`.

**Comment by andreabedini** [comment]
nah, I reverted @df34795 and fixed `Table._append_records` to accept a large enough type (e.g. `hsize_t`) and this problem seems to disappear.

**Comment by andreabedini** [comment]
Pretty sure `xrange` wasn't the culprit, also because 3000000000 fits into a int64 and `len(xrange(3000000000))` works just fine on a 64bit arch.

**Comment by FrancescAlted** [comment]
Agreed, https://github.com/PyTables/PyTables/commit/df34795 seems the correct fix.  Thank you for looking into this the correct way.
