### ISSUE TITLE
'Other material' section missing from the website

### ISSUE THREAD

**Issue by andreabedini** [PyTables/PyTables#453]
Many document linked from http://www.pytables.org/other_material.html are missing, it seems the a directory http://www.pytables.org/docs did get moved to GitHub. @FrancescAlted do you have a copy of those documents and could you commit them to a folder called docs in the website repository?

**Comment by avalentino** [comment]
Good catch @andreabedini.
We can also use sf.net to store large sized material.

**Comment by andreabedini** [comment]
I'd recommend keeping everything in the same place. GitHub is fine, they have just introduced a git large files extension.

**Comment by andreabedini** [comment]
bingo http://web.archive.org/web/20150202222057/http://www.pytables.org/docs/PUG-Austin-2012-v3.pdf :)

**Comment by andreabedini** [comment]
I got all the files back, where should I put them? is the website generated from the main repo? @FrancescAlted @avalentino

**Comment by avalentino** [comment]
The website si in the https://github.com/PyTables/pytables.github.com.git repository.
Contents are mainly generated using sphinx in the main PyTables repository and then manually moved to the site repository.
IMO we have 3 options to store the "Other material":

* use sf.net file area an link for the main potables site
* store it in a dedicated folder in the website repository root
* store it in the git repo of the website in the _download folder (already existing)

**Comment by andreabedini** [comment]
I can just make a docs folder to keep the old URL (important for search engines and bookmarks) but I don't know if I need to create it on the website repo or on the main repo.

We should drop sf.net entirely and keep releases on github (1 service is better than 2, sf.net is full of ads, and github has plenty of integrations).

**Comment by andreabedini** [comment]
actually aren't the releases uploaded to pypi? we don't need anythings else

**Comment by avalentino** [comment]
> I can just make a docs folder to keep the old URL (important for search engines and bookmarks) but I don't know if I need to create it on the website repo or on the main repo.

I'm absolutely -10 for uploading (potentially large) binary files on the main repo.
The only allowed exceptions IMO are files necessary for unit testing.

> We should drop sf.net entirely and keep releases on github (1 service is better than 2, sf.net is full of ads, and github has plenty of integrations).

on sf.net we also upload the HTML and PDF documentation. I don't know if these packages can he uploaded on pypi.
Also please note that, while the HTML doc is also included in the source distribution, the PDF doc is only available on sf.net at the moment.

**Comment by andreabedini** [comment]
> I'm absolutely -10 for uploading (potentially large) binary files on the main repo.

Website can be on a different repo.
 
> on sf.net we also upload the HTML and PDF documentation. I don't know if these packages can he uploaded on pypi.

HTML and PDF downloads are provided by readthedocs too see discussion at #460
