### ISSUE TITLE
PyTables fails to install when placed as its own dependency in install_requires (setuptools)

### ISSUE THREAD

**Issue by EricR86** [PyTables/PyTables#454]
Although `pip install 'tables>=3.2'` works fine, when 'tables>=3.2' is placed in the 'install_requires' portion of the setup function from setuptools, PyTables fails to install properly. Note that this works if PyTables is the *only* dependency.

The error and relevant lines are posted below:
```shell
 File "/tmp/easy_install-Td0dEY/numexpr-2.4.3/setup.py", line 62, in setup_package
ImportError: No module named numpy.distutils.core
```

So for some odd reason when PyTables is installed itself as a dependency it breaks the numexpr installation.

Again this with an `install_requires` that looks like this:

```python
 install_requires = ["tables>=3.2"] 
```

I'm aware this may or may not directly relate to PyTables specifically.

**Comment by EricR86** [comment]
A simple way to reproduce this problem is to clone the sample Python Packaging User Guide package here:
https://github.com/pypa/sampleproject

And change the `install_requires` parameter in the setup function to use 'tables>=3.2' instead. Then run python setup.py install from the sameproject directory.

**Comment by andreabedini** [comment]
@EricR86 I had not time to have a look a this yet but thanks for reporting the issue! Do you have any idea of what's going on here? I wonder why the error happens in numexpr setup.py rather than in pytables. What is you put numexpr in `install_requires` rather than pytables?

**Comment by EricR86** [comment]
It fails as well. I'm investigating it a little and I'll probably report the issue on numexpr as well (and reference it here).

The issue is a little confusing since PyTables uses numexpr as a dependency and doesn't have this issue. But for the trivial example where numexpr is the only dependency (say in the sampleproject example above) - it does.

**Comment by andreabedini** [comment]
With your analysis you discovered it's a numexpr bug. It still works when you install pytables because apparently numpy gets installed by our setup.py before numexpr setup is executed. Python packaging is hard! Thank for checking this out @EricR86!
