### ISSUE TITLE
indexesextension.keysort() seg faults under 3.2.0 but not 3.1.1

### ISSUE THREAD

**Issue by bastianl** [PyTables/PyTables#455]
Note that indexextension.keysort() is called from pandas when appending data to HDFStore.  This is where this bug was originally discovered. pydata/pandas#10180

Consider the case where chunks of data are appended.  Each chunk is
continuous as group_a, group_b, and group_c. If these are appended in the
specific order of group_a, then group_c, then group_b and the size of the
group is 162 a seg fault occurs as shown in the code below.

Also note that this pattern continues above 162 for any even n, that is
n=162, 164, 166, ...
```
import numpy as np
from tables import indexesextension


def run(n):
    # build three continuous regions of size n
    d1 = list(range(0, n))
    d2 = list(range(n, 2 * n))
    d3 = list(range(2 * n, 3 * n))

    # build indexed in out of order
    arr = np.array(d1 + d3 + d2)
    idx = np.array(range(3 * n))
    indexesextension.keysort(arr, idx)


for k in range(1, 1000):
    print(k)
    run(k)
```

**Comment by andreabedini** [comment]
This is bad (and most likely my fault). I'll check this asap

**Comment by andreabedini** [comment]
I found the problem.

I am simply running out of stack space in the C implementation of quick sort, the constant [`PYA_QS_STACK `](https://github.com/PyTables/PyTables/blob/master/tables/indexesextension.pyx#L145) is just not enough. I wonder why this doesn't happen with the old code as they are identical (compare [old](https://github.com/PyTables/PyTables/blob/9026fde30192a31a2b3a292f26c081e7ad16ab7d/src/idx-opt.c#L823) vs [new](https://github.com/PyTables/PyTables/blob/master/tables/indexesextension.pyx#L224)).

Maybe I did something silly writing the new version. Can anybody spot the problem?

**Comment by alin-luminoso** [comment]
You seem to have reversed a test when porting: compare https://github.com/PyTables/PyTables/blob/v.3.1.1/src/idx-opt.c#L724, https://github.com/PyTables/PyTables/blob/master/tables/indexesextension.pyx#L302 .

**Comment by alin-luminoso** [comment]
(If I understand the algorithm correctly, the constant should only need to satisfy `PYA_QS_STACK > log2(size)`, up to some constant factors I don't want to bother computing.  So it really cannot be that your constant is too small given its current value of `100`!)

**Comment by andreabedini** [comment]
oh :hankey: ! thanks for finding the problem @alin-luminoso. I wouldn't have found it had I reread the code a thousand times!

**Comment by alin-luminoso** [comment]
No problem!  Any chance of a bugfix release?  :-)

**Comment by andreabedini** [comment]
@alin-luminoso oh yeah, I don't have much time at the moment but it's definitely something I want to do as soon as I can.

**Comment by andreabedini** [comment]
@alin-luminoso release done, please test!

**Comment by bastianl** [comment]
seems to work on 3.2.1 -- thanks!

**Comment by andreabedini** [comment]
thank you for the detailed report @bastianl !
