### ISSUE TITLE
Add write support to FileNode

### ISSUE THREAD

**Issue by joshmoore** [PyTables/PyTables#46]
It would be nice that the `FileNode` module supported in-place writing (i.e. modification) of data, besides read-only and read-append.  Implementing it should not be very difficult, by using `EArray.__setitem__()`.  However, it is a problem that `EArray` objects do not allow truncation, to better simulate RW files.

**Comment by FrancescAlted** [comment]
This is quite old, so closing.  In case anybody wants that, we will be glad to accept a PR.
