### ISSUE TITLE
Split website and documentation

### ISSUE THREAD

**Issue by andreabedini** [PyTables/PyTables#460]
I think the situation is not optimal.

We have a website, hosted here on github in a separated repository. The website includes the documentation and is itself generated with sphinx from the main repo. This means that any change of the website is mixed with the release process, as it is not clear from what branch the website should be generated from. If we generate the website at every release from the master branch, then where should we commit general website updates?

I think there is a case for moving the documentation off the website to an external service like readthedocs.org. Actually @avalentino has already set up http://pytables.readthedocs.org and works beautifully. We could already save a lot of time by using that rather than github pages (that we need to build manually).

**Comment by avalentino** [comment]
> I think there is a case for moving the documentation off the website to an external service like readthedocs.org. Actually @avalentino has already set up http://pytables.readthedocs.org and works beautifully. We could already save a lot of time by using that rather than github pages (that we need to build manually).

The reference manual in readthedocs.org is broken.
It is necessary to build the pytables package in order to be able to generate the documentation correctly.
The only way to have the complete doc in rtd.org is to perform a manual upload AFAIK.

Probably we should drop readthedocs totally.

**Comment by andreabedini** [comment]
> It is necessary to build the pytables package in order to be able to generate the documentation correctly.

Why? do other project have the same issue? can we simplify the way do things?

> Probably we should drop readthedocs totally.

ok

**Comment by avalentino** [comment]
>> It is necessary to build the pytables package in order to be able to generate the documentation correctly.

> Why? do other project have the same issue? can we simplify the way do things?

If I remember well the problem is that HDF5 is not installed on RTD so it is not possible to build pytables and hence the documentation.
I don't know if things are changed since the last time I checked.

**Comment by andreabedini** [comment]
Hello @PyTables/maintainers,

We need a website because we have website-like content we don't want to include in the main repo (pdfs). We also need an online user manual as well. The two have very different life-lines. In the current setup it is uncomfortable updating the website any time there is substantial change between develop and the latest release.

I propose we split the documentation from the website. There are some technical issues about hosting the documentation on readthedocs but I believe they can be overcome. pythonhosted is an alternative. See my original post above for few extra reasons I think this would be a improvement.

I have played with a landing page for PyTables that you can find here 

https://github.com/andreabedini/new-pytables-website-test 

I hate writing so there's not much there and it can be improved. I will add the new donation button soon too. The _Contact_ is still pristine from the template. We will acknowledge the designer Xiaoying Riley on the footer.

Let me know what you think.

**Comment by FrancescAlted** [comment]
I personally find this pretty nice!  Once we add the actual logo and play a bit with colors this could be a really cool landing page for PyTables.  Thanks for looking into this!

**Comment by avalentino** [comment]
Yes, very nice indeed.
Regarding the problem of building the doc on rtf,org we could probably try to build the doc on troves and upload it on rtd.org automatically.
I don'y know if it is possible in practice but it could be an option

**Comment by scopatz** [comment]
+1 to the the new page.  I agree with @FrancescAlted that the colors could be massaged a bit.

**Comment by scopatz** [comment]
Great other than that!
