### ISSUE TITLE
AttributeSet: the ``/`` character is not allowed in object names: '/a/b'

### ISSUE THREAD

**Issue by mythsmith** [PyTables/PyTables#462]
It is not possible to set an attribute name containing a slash character:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/tables/attributeset.py", line 537, in __setitem__
    self.__setattr__(name, value)
  File "/usr/lib/python2.7/dist-packages/tables/attributeset.py", line 436, in __setattr__
    check_name_validity(name)
  File "/usr/lib/python2.7/dist-packages/tables/path.py", line 93, in check_name_validity
    "in object names: %r" % name)
ValueError: the ``/`` character is not allowed in object names: '/a/b'

But, if you create a node having such an attribute with another tool (hdfview), you will be able to read it:
>>> f.root.a._v_attrs
/a._v_attrs (AttributeSet), 5 attributes:
   [/a/b/c := array([''], 
      dtype='|S1'),
    CLASS := 'GROUP',
    TITLE := '',
    VERSION := '1.0',
    a := 1]

I see no need to block "/" characters in attribute names.

**Comment by avalentino** [comment]
Hi Daniele, nice patch.
Can you please add a small unit test and submit a PR?

**Comment by andreabedini** [comment]
as long as HDF5 accepts slashes in attributes names, we should do too.

**Comment by mythsmith** [comment]
I'm sorry I'm a beginner on github. Just have patience, I'll shortly come up with pull request (and test cases).

**Comment by andreabedini** [comment]
@mythsmith take you time Daniele, no rush :)

**Comment by andreabedini** [comment]
closed by #464
