### ISSUE TITLE
Read array created with pytable file

### ISSUE THREAD

**Issue by adwien** [PyTables/PyTables#470]
Hi,
I use pytables to create array thanks to next way:
    hdf5 =  openFile(name_of_the_file, mode = "w", title = 'titre')
    hdf5.createGroup('/','matricegroupe')
    matrice = zeros((n,n))
    hdf5.createArray('/matricegroupe','matrice1',matrice)
    hdf5.close()
And i would like to read the array (to use and change it after). For this i start like this:
     hdf5 =  openFile(name_of_the_file, mode = "a", title = 'titre')
But after, i didn't find the easy way to read the array named 'matrice1' in the hdf5 to use it after .
Somebody can give me some advices?
thank you

**Comment by andreabedini** [comment]
`hdf5.root.matricegroupe.matrice1` ?
