### ISSUE TITLE
Error running examples/objecttree.py using Python 3 (but not with Python 2)

### ISSUE THREAD

**Issue by rdhyee** [PyTables/PyTables#474]
As a PyTables newbie, I've been going through the tutorial at http://www.pytables.org/usersguide/introduction.html.  When I ran the  [objecttree.py example](https://github.com/PyTables/PyTables/blob/develop/examples/objecttree.py), I got the following traceback:

```
Traceback (most recent call last):
  File "objecttree.py", line 22, in <module>
    root, "array1", ["string", "array"], "String array")
  File "/global/home/users/ryee/miniconda/envs/myenv3/lib/python3.4/site-packages/tables/file.py", line 1152, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/global/home/users/ryee/miniconda/envs/myenv3/lib/python3.4/site-packages/tables/array.py", line 187, in __init__
    byteorder, _log)
  File "/global/home/users/ryee/miniconda/envs/myenv3/lib/python3.4/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/global/home/users/ryee/miniconda/envs/myenv3/lib/python3.4/site-packages/tables/node.py", line 267, in __init__
    self._v_objectid = self._g_create()
  File "/global/home/users/ryee/miniconda/envs/myenv3/lib/python3.4/site-packages/tables/array.py", line 204, in _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arrays
```

Here's the output from tables.print_versions():
```
>>> tables.print_versions()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.0
HDF5 version:        1.8.15-patch1
NumPy version:       1.9.2
Numexpr version:     2.4.3 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.06 (Aug 12 2011)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Cython version:      0.22.1
Python version:      3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform:            Linux-2.6.32-504.1.3.el6.x86_64-x86_64-with-redhat-6.6-Carbon
Byte-ordering:       little
Detected cores:      20
Default encoding:    utf-8
Default FS encoding: ascii
Default locale:      (None, None)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

When I ran with Python 2, the program completed successfully.  Here's the output of `tables.print_versions()`:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.0
HDF5 version:        1.8.15-patch1
NumPy version:       1.9.2
Numexpr version:     2.4.3 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.06 (Aug 12 2011)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Cython version:      0.22.1
Python version:      2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform:            Linux-2.6.32-504.1.3.el6.x86_64-x86_64-with-redhat-6.6-Carbon
Byte-ordering:       little
Detected cores:      20
Default encoding:    ascii
Default FS encoding: ANSI_X3.4-1968
Default locale:      (None, None)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

This discrepancy brings up a general question: is `PyTables` supposed to run equally as well on Python 3 as it does on Python 2?

**Comment by rdhyee** [comment]
From https://twitter.com/physics_codes/status/621450769452003332: 

> That is what I meant.  PyTables works fine in py3k. But the PyTables examples have a breakage.

**Comment by andreabedini** [comment]
thanks for the report @rdhyee

**Comment by andreabedini** [comment]
It should be fixed in b7c143054a5d63f1ebda512f470d667de5ebc764. Bug fix release soon.

**Comment by rdhyee** [comment]
Thanks @andreabedini for the fix. I'll be on the look out for other examples that don't work in Python 3 (unless you've already done a check for Python 2/3 compatibility issues.)

**Comment by rdhyee** [comment]
Will this fix will propagate to http://www.pytables.org/usersguide/introduction.html ?

**Comment by andreabedini** [comment]
that would be fantastic @rdhyee! I checked few, I know some don't work.

**Comment by andreabedini** [comment]
> Will this fix will propagate to http://www.pytables.org/usersguide/introduction.html ?

at some point yes :) but very slowly :(

**Comment by FrancescAlted** [comment]
@rdhyee You can always accelerate improvements by providing pull requests: https://help.github.com/articles/using-pull-requests/

**Comment by hexatonics** [comment]
@FrancesAlted it's a year later, and this  example code from the beginning of the tutorial still will not run in Python3.  I would like to follow your suggestion and provide a pull request with a fix, but since I'm a PyTables newbie, the trouble is, I don't actually know what's causing the error and how to fix it.  Using Google to find "TypeError: Array objects cannot currently deal with void, unicode or object arrays" & Pytables is not informative.  Could you give me a hint on what to read to understand this error so I can fix it?  Thanks :)

**Comment by FrancescAlted** [comment]
@hexatonics What I'd do is to see where the error is thrown in the code and then try to understand what is causing the error.  Then, I'd create a small test unit for that and try to improve things until the error disappears.  If you are stuck on this, please ask again.
