### ISSUE TITLE
setup.py  tables install fails

### ISSUE THREAD

**Issue by xishazgh** [PyTables/PyTables#480]
Hi PyTables team,

I want to install Pytables using setup.py, but I get some error below . Could anyone can help me and  apologies in advance if I am overlooking something simple.

sudo python setup.py build_ext --inplace --hdf5=/usr/local/hdf5 --lzo=/usr/local/lzo --bzip2=/usr/local/bzip2 --blosc=/usr/local/blosc
* Using Python 2.7.5+ (default, Feb 27 2014, 19:37:08)
* USE_PKGCONFIG: False
* Found HDF5 headers at ``/usr/local/hdf5/include``, library at ``/usr/local/hdf5/lib``.
.. WARNING:: Could not find the HDF5 runtime.
   The HDF5 shared library was *not* found in the default library
   paths. In case of runtime problems, please remember to install it.
* Found LZO 2 headers at ``/usr/local/lzo/include``, library at ``/usr /local/lzo/lib``.
.. WARNING:: Could not find the LZO 2 runtime.
   The LZO 2 shared library was *not* found in the default library
   paths. In case of runtime problems, please remember to install it.
* Skipping detection of LZO 1 since LZO 2 has already been found.
* Found bzip2 headers at ``/usr/local/bzip2/include``, library at ``/usr/local/bzip2/lib``.
.. WARNING:: Could not find the bzip2 runtime.
   The bzip2 shared library was *not* found in the default library
   paths. In case of runtime problems, please remember to install it.
* Found blosc headers at ``/usr/local/blosc/include``, library at ``/usr/local/blosc/lib``.
.. WARNING:: Could not find the blosc runtime.
   The blosc shared library was *not* found in the default library
   paths. In case of runtime problems, please remember to install it.
running build_ext
building 'tables._comp_lzo' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNDEBUG=1 -DHAVE_LZO2_LIB=1 -DHAVE_BZ2_LIB=1 -DHAVE_BLOSC_LIB=1 -Ic-blosc/hdf5 -I/usr/local/hdf5/include -I/usr/local/lzo/include -I/usr/local/bzip2/include -I/usr/local/blosc/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c tables/_comp_lzo.c -o build/temp.linux-x86_64-2.7/tables/_comp_lzo.o -Isrc -DH5Acreate_vers=2 -DH5Aiterate_vers=2 -DH5Dcreate_vers=2 -DH5Dopen_vers=2 -DH5Eclear_vers=2 -DH5Eprint_vers=2 -DH5Epush_vers=2 -DH5Eset_auto_vers=2 -DH5Eget_auto_vers=2 -DH5Ewalk_vers=2 -DH5E_auto_t_vers=2 -DH5Gcreate_vers=2 -DH5Gopen_vers=2 -DH5Pget_filter_vers=2 -DH5Pget_filter_by_id_vers=2 -DH5Tarray_create_vers=2 -DH5Tget_array_dims_vers=2 -DH5Z_class_t_vers=2
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNDEBUG=1 -DHAVE_LZO2_LIB=1 -DHAVE_BZ2_LIB=1 -DHAVE_BLOSC_LIB=1 -Ic-blosc/hdf5 -I/usr/local/hdf5/include -I/usr/local/lzo/include -I/usr/local/bzip2/include -I/usr/local/blosc/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/H5Zlzo.c -o build/temp.linux-x86_64-2.7/src/H5Zlzo.o -Isrc -DH5Acreate_vers=2 -DH5Aiterate_vers=2 -DH5Dcreate_vers=2 -DH5Dopen_vers=2 -DH5Eclear_vers=2 -DH5Eprint_vers=2 -DH5Epush_vers=2 -DH5Eset_auto_vers=2 -DH5Eget_auto_vers=2 -DH5Ewalk_vers=2 -DH5E_auto_t_vers=2 -DH5Gcreate_vers=2 -DH5Gopen_vers=2 -DH5Pget_filter_vers=2 -DH5Pget_filter_by_id_vers=2 -DH5Tarray_create_vers=2 -DH5Tget_array_dims_vers=2 -DH5Z_class_t_vers=2
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/tables/_comp_lzo.o build/temp.linux-x86_64-2.7/src/H5Zlzo.o -L/usr/local/hdf5/lib -L/usr/local/lzo/lib -L/usr/local/bzip2/lib -L/usr/local/blosc/lib -lhdf5 -llzo2 -o build/lib.linux-x86_64-2.7/tables/_comp_lzo.so
/usr/bin/ld: /usr/local/lzo/lib/liblzo2.a(lzo1x_1.o): relocation R_X86_64_PC32 against undefined symbol `memset@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by scopatz** [comment]
Maybe you need to install blosc?

**Comment by andreabedini** [comment]
@xishazgh you got some linking problems there.

```
relocation R_X86_64_PC32 against undefined symbol `memset@@GLIBC_2.2.5' can not be used when making a shared object
```

 I doubt it's a PyTables issue. Most likely your setup is broken. Especially double check liblzo2.
