### ISSUE TITLE
Bad permissions of egg-info when installing trough setuptools

### ISSUE THREAD

**Issue by aginiewicz** [PyTables/PyTables#488]
See https://bugs.archlinux.org/task/45975 for reference. For some reason when installing on Arch Linux permissions are wrong (files from under egg-info do not have read permissions). For now I've used chmod in install package, but it worked before PyTables 3.2.1.

**Comment by scopatz** [comment]
Hmmm. Thanks for reporting @aginiewicz

**Comment by andreabedini** [comment]
hi @aginiewicz, this might be a bug in setuptools which AFAICT is what creates tables-3.2.1-py3.4.egg-info. We don't touch permissions at all. I found this https://bugs.archlinux.org/task/30020 which seems to be the same problem with another python package. I am not very familiar with Arch Linux, how do you build your python packages? does a simple (user mode) `pip install table` work?

**Comment by aginiewicz** [comment]
Hello, to build on Arch Linux we use just upstream tools. This is PKGBUILD for python-pytables: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-pytables it is split package (building 4 packages - 2 architectures and 2 python versions).

It's just bash script:

- first prepare is called to create copy of source directory for building python 2 version.
- then build function is called which basically runs "python setup.py build"
- then two package functions are called, which basically do "python setup.py install --prefix=/usr --root="$pkgdir" --optimize=1"

This PKGBUILD include my quick'n'dirty fix (chmod) to avoid this problem.

About other bug you mentioned, it was reported for dateutils 2.1, but fixed upstream for dateutils 2.3 (unfortunately I don't know how or when exactly, wasn't following that issue, so I don't know if it was dateutils change or setuptools change). As you can see with package version bump: https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/python-dateutil&id=301971592cff34762d4903af4b81f7d2995af664 - chmod was removed. Btw, same issue about dateutils was reported to FreeBSD (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=176803), MacPorts (https://trac.macports.org/ticket/43187) and some other distributions, so I don't think it is Arch Linux related issue. Also, at the same time, there was only reports related to dateutils, not hundreds of other packages, so I'm not sure if setuptools is only reason either.

**Comment by aginiewicz** [comment]
Btw, sorry for misleading topic - it was late when I posted the issue, and I was thinking about few things at the same time. Changed the topic to reflect actual issue.

**Comment by andreabedini** [comment]
@aginiewicz thanks for the detailed info!

**Comment by andreabedini** [comment]
@aginiewicz The dateutil bug report is telling

> Modern installers normalize permissions (pip does) but easy_install or setup.py install doesn't. Meaning tools relying on easy_install or setup.py (such as FPM) may end up with insufficient permissions to run the code as a non-root user.

I couldn't find any related changes on their github repo (perhaps I didn't look carefully enough).

I did some tests and `python setup.py install` simply respects the standard umask. With what umask is the build script running?

**Comment by aginiewicz** [comment]
I'm pretty sure, that it runs with 022 - especially, that for all other packages I maintain it works. I guess it's tarball hosted on PyPi that's at fault. I've made fresh download of two archives, for 3.2.0 and 3.2.1, and this is the difference. I believe dateutils "fixed it" by just uploading another tarball into PyPi.

````
[giniu@raven3 tmp]$ LANG=C ls -al tables-3.2.0/tables.egg-info
total 52
drwxr-xr-x  2 giniu giniu   180 May  6 18:10 .
drwxr-xr-x 12 giniu giniu   480 May  6 18:10 ..
-rw-r--r--  1 giniu giniu  1410 May  6 18:10 PKG-INFO
-rw-r--r--  1 giniu giniu 25846 May  6 18:10 SOURCES.txt
-rw-r--r--  1 giniu giniu     1 May  6 18:10 dependency_links.txt
-rw-r--r--  1 giniu giniu   167 May  6 18:10 entry_points.txt
-rw-r--r--  1 giniu giniu     1 Apr 21 13:42 not-zip-safe
-rw-r--r--  1 giniu giniu    26 May  6 18:10 requires.txt
-rw-r--r--  1 giniu giniu     7 May  6 18:10 top_level.txt
[giniu@raven3 tmp]$ LANG=C ls -al tables-3.2.1/tables.egg-info
total 56
drwx------  2 giniu giniu   200 Aug  4 02:24 .
drwx------ 12 giniu giniu   480 Aug  4 02:24 ..
-rw-------  1 giniu giniu  1410 Aug  4 02:24 PKG-INFO
-rw-------  1 giniu giniu 25871 Aug  4 02:24 SOURCES.txt
-rw-------  1 giniu giniu     1 Aug  4 02:24 dependency_links.txt
-rw-------  1 giniu giniu   167 Aug  4 02:24 entry_points.txt
-rw-------  1 giniu giniu     1 Aug  4 02:24 not-zip-safe
-rw-------  1 giniu giniu    47 Aug  4 02:24 pbr.json
-rw-------  1 giniu giniu    26 Aug  4 02:24 requires.txt
-rw-------  1 giniu giniu     7 Aug  4 02:24 top_level.txt
````

**Comment by andreabedini** [comment]
@aginiewicz yes, I later noticed that too, I build the sdist with umask 077. I have to say I find the whole thing a bit fragile because it's not written anywhere that the tarball should have specific permissions (indeed pip resets them). Anyhow I think I can easily replace the tarball on pypi without much drama.

**Comment by FrancescAlted** [comment]
Hmm, that's tricky.  Maybe it is a good time to make a point in the [Release Procedure](https://github.com/PyTables/PyTables/wiki/Release-Procedure) so as to avoid problems in the future?

**Comment by andreabedini** [comment]
I thought about this for a bit. My conclusion is that it's distros' fault :-)

It's written nowhere that a python source distribution should guarantee some file permissions. Indeed `pip` resets the permissions when installing.

One would think that `python setup.py install` resets the permissions but it doesn't. This should be brought up to the @pypa.

Packagers should either:

1. use `pip install .`
2. set the desired permissions themselves

**Comment by FrancescAlted** [comment]
Ok, if this is a problem with distro's, many other people will have been bitten too, so I would expect a quick fix soon.  But that not prevents from reporting ourselves :)

**Comment by andreabedini** [comment]
I will close this since there's nothing to fix beside uploading a new package on PyPI which I have already done.
