### ISSUE TITLE
Error while creating Index in Pytables

### ISSUE THREAD

**Issue by supriyom083** [PyTables/PyTables#497]
Hi Team,
I am facing severe issue while creating index in pytables.
I have attached a python script and a sample HDF5 file to recreate the issue.
This is quite a strange issue.
Step 1.
Run the script as is it will crash the python Interpreter.
Step 2.
Change the index creation line to "tbl.cols.person_wid.createIndex()" this will work fine.

I am getting blosc decompression error in step 1.

I am unable to understand what went wrong in step 1 and same code works fine for step 2.

Could you please help me to get rid of this issue.

Please let me know how to share sample HDF5 file and code to reproduce this issue.

Thanks
Supriya

**Comment by FrancescAlted** [comment]
Sorry, but I don't see the attachment.  Maybe a good idea would be to create a Gist (https://gist.github.com/) and reference the URL in this ticket.

**Comment by supriyom083** [comment]
I have dropped a mail in pytables@googlemail.com

**Comment by supriyom083** [comment]
I have dropped a mail with subject "Error while creating Index in Pytables"
in pytable@googlemail.com

**Comment by FrancescAlted** [comment]
I don't know the `pytable@googlemail.com` address.  Please, do file the example in a Gist as suggested or include the code directly in this ticket.

**Comment by supriyom083** [comment]
import tables as tb
import time
import numpy as np
import pybloom as pb
h5file=tb.open_file("d:/tutorial11.h5", mode = "a")
tbl=h5file.root.grp1.table_example
print(time.time())
tbl.cols.row_wid.createIndex()
print(time.time())
print(tbl)
i=0
while True :
    cond='(row_wid>100 )'# & (row_wid <= ' + str((i+1)*10000000*1) +')'
    print (cond)
    t=[x['person_wid'] for x in tbl.where(cond)]
    #for j in range(len(t)):
    # f.add(t[j])
     #continue
     #pbf.insert(t[j])
    #print(t[0])
    print(len(t))
    i+=1
    if i== 1 :
     break
 
tbl.close()
h5file.close()
print h5file
---------------------------------------------------
structure of file 
 class data_row (tb.IsDescription):
             
             person_wid =tb.Int64Col()
             row_wid =tb.Int32Col()
             gender_wid =tb.Int64Col()
             nationality_wid =tb.Int64Col()
             education_level_wid =tb.Int64Col()
             education_status_wid =tb.Int64Col()
             org_wid =tb.Int64Col()
             job_position_wid =tb.Int64Col()
             job_city_wid =tb.Int64Col()
             industry_sector_wid =tb.Int64Col()
             salary =tb.Int64Col()
             disability_flag= tb.StringCol(1)
             hist_curr_flag = tb.StringCol(1)
             attribute1 = tb.StringCol(10)
             attribute2 = tb.StringCol(10)
             attribute3 = tb.StringCol(10)
             attribute4 = tb.StringCol(10)
             attribute5 = tb.StringCol(10)
             etl_batch_id  =tb.StringCol(10)
             w_insert_dt =tb.StringCol(15)
             w_update_dt =tb.StringCol(15)
             hash_value =tb.Int64Col()
and filer
fil=tb.Filters(complib='blosc',complevel=5)
Hope this will help you to recreate the issue.
If you required HDF5 generated in my system,I can share the same so that you can reproduce the same,File size is 12 Mb.If you provide a share location or mail I can share the same.

Thanks

**Comment by supriyom083** [comment]
Fault module indexesextension.pyd

**Comment by dejlek** [comment]
I have an issue with the same module and we are trying to make reproducable error...

Here is the backtrace: http://codepad.org/r4mO9YAc

Basically we can reproduce the same crash eveyr time we run the script with the same parameters. However, problem is that we can't give the input files to PyTables developers because we are not allowed to share them. :( I hope my colleagues will be successful at creating a mockup which reproduces the problem, so we can find out what is going on...

**Comment by andreabedini** [comment]
yes! a backtrace! now I know where the problem is :) will fix this soon

**Comment by andreabedini** [comment]
@supriyom083 can you check if the branch https://github.com/PyTables/PyTables/tree/hotfix/3.2.2 solves you problem?

You can install it with

    pip install git+https://github.com/PyTables/PyTables@hotfix/3.2.2

**Comment by supriyom083** [comment]
Sorry to Inform you,that problem is still there

**Comment by andreabedini** [comment]
sorry to hear that @supriyom083, without a backtrace there's little I can do ...
