### ISSUE TITLE
Script crashes when appending records to a table.

### ISSUE THREAD

**Issue by dejlek** [PyTables/PyTables#498]
The script is writing couple thousands of (processed) records, appending to a table.

Here is the backtrace: http://codepad.org/r4mO9YAc

Basically we can reproduce the same crash every time we run the script with the same parameters. However, problem is that we can't give the input files to PyTables developers because we are not allowed to share them. :( I hope my colleagues will be successful at creating a mockup which reproduces the problem, so we can find out what is going on...

I will update the issue once I have more data.

**Comment by andreabedini** [comment]
@dejlek can you check if the branch https://github.com/PyTables/PyTables/tree/hotfix/3.2.2 solves you problem?

**Comment by dejlek** [comment]
@andreabedini, looks like the branch solves the problem! :+1: 
Do you by any chance have any idea when will this be merged into the master and released? :)

**Comment by andreabedini** [comment]
@dejlek yes, I plan to release 3.2.2 early next week.

**Comment by dejlek** [comment]
Looks like the SIGSEGV still sporadically happens. Not as often as before. So I am afraid the problem is still there. :(

**Comment by andreabedini** [comment]
@dejlek same backtrace?

**Comment by dejlek** [comment]
Nope, different. I will make a separate issue for it as it segfaults at different place. I will update the comment here when I am done.

**Comment by andreabedini** [comment]
Moving on to the other report then, thanks @dejlek
