### ISSUE TITLE
Not clear how to open file from a memory image

### ISSUE THREAD

**Issue by tobgu** [PyTables/PyTables#510]
I want to open a file using driver_core_backing_store=0 to avoid that it is ever written to disk. Then I want to fetch the memory image and store it in a database without having to write it to the local disk.

This is described here http://www.pytables.org/cookbook/inmemory_hdf5_files.html#memory-images-of-hdf5-files. So far so good. I don't think the documentation is clear on how to open a file from a memory image though. It just states that "The ìmage string can be passed around and can also be used to initialize a new HDF55 file descriptor". Then an example follows that (as far as I can understand) doesn't do this but opens a file like normal.

This ticket is a request for clarification of the documentation on this point. Or an explanation in case I've missed something fundamental.

Thank you!

**Comment by avalentino** [comment]
The documentation source has been already updated (see https://github.com/PyTables/PyTables/blob/develop/doc/source/cookbook/inmemory_hdf5_files.rst).
We will update the online HTML doc ASAP.

**Comment by tobgu** [comment]
OK, great, thanks!

**Comment by avalentino** [comment]
I have just realized that the fix is still not in the stable release. The updated doc will be uploaded with the next stable version.

**Comment by tobgu** [comment]
But the functionality is there as described, right?

**Comment by avalentino** [comment]
yes
