### ISSUE TITLE
Attempting to copy and sort a very large table (~40 GB) fails

### ISSUE THREAD

**Issue by 153957** [PyTables/PyTables#516]
**What I want to do**
I have a file containing one table with almost 1 Giga row and 11 columns (mostly float32).
That table also has a cs_index for one of those columns, and the file has a couple of attributes on the root group.

**How it should do it**
The function used to copy and sort the table can be seen here (the top of that file contains the table description):
https://github.com/HiSPARC/sapphire/blob/82eaa1c67/sapphire/corsika/store_corsika_data.py#L160-L172

**What happens**
I'm not certain what precisely happened. I started the script to create a sorted copy of the large file. It started to do a lot of reading from my HDD (in and output to the same HDD). Hardly any RAM was used. And it was constantly reading, hardly writing anything to output. Before it crashed it was reading continuously for about 4 days at 120 MB/s, so about 42 TB was read (for a file only 40 GB). However, hardly anything was written, only a couple GB. Here is the Disk Activity for the time that it was running (blue is reading):
![disk_activity](https://cloud.githubusercontent.com/assets/1433682/11286170/cd252586-8f13-11e5-88fa-47fd3cd6c81e.png)
After 4 days my computer crashed (not certain if it was caused by this, this was at the top of the Panic Report: `panic(cpu 8 caller 0xffffff80197d3934): "VM_PAGE_QUEUES_REMOVE: unmarked page on Q"@/SourceCache/xnu/xnu-2782.40.9/osfmk/vm/vm_resident.c:4890`). It should never have taken (more than) 4 days to begin with..

**What does work**
The same file structure, and copy and sort method have also been used for many (>50k) smaller files (from several KB to some GB), for which the process worked without issue.

**Conda env**

```
numpy     1.9.3    py27_0
pytables  3.2.2    np19py27_0
python    2.7.10   2  
hdf5      1.8.15.1 2  
```

I would have expected the copy and sort operation to be relatively fast, since a cs_index exists it _merely_ needs to do a lot of (semi-)random reads (which it was not doing given the read speed). It could have used a lot of RAM to cache chunks, but RAM usage did not increase significantly (many GB of RAM available).

**Comment by 153957** [comment]
It worked 'ok' for a 16 GB file, but it took 25 hours, which seems excessive.

**Comment by 153957** [comment]
We realised that currently PyTables was reading semi-random chunks of data from which it needed only single rows. Because it reads singles rows in the 'correct' order, but those were in random places in the source file. @tomkooij has implemented a merge-sort algorithm for PyTables which first sorts big chunks of sequential data in memory, writes those to disc, and then merge sorts those parts, reading as necessary from the already sorted parts. This speeds up sorting for files which can not be kept entirely in memory. We are testing this algorithm on the large files which were nearly impossible to sort before. (This method is slower for files which can be sorted in memory, we have not put to much effort into determining the exact crossover point were one is faster than the other.)

Would PyTables be interested in this implementation, either to incorporated into PyTables or as an example for the documentation?

**Comment by FrancescAlted** [comment]
Definitely.  If you can provide us with some figures about the efficiency of the new method for disk operation, that would be really nice.  PyTables is all about out-of-core, so even if this slows-down by some extent in-memory sorting, I think this would definitely be a great addition.  Thanks!

**Comment by tomkooij** [comment]
Copy and sort using CSIndex is slow because it basically reads the entire table row by row and out-of-order (random reads). In the worst case scenario each chunk is read from disk for each row in the chunk. Caching does not help. This can be hardly be improved by optimizing chunksize and increasing cache (within realistic limits). 

As @153957 explaines above, our solution is to read a big part of the table sequentially into memory from disk. Sort it in memory (using ```numpy.ndarray.sort```) and store it in a temporary table. Once all parts are sorted, we merge the temporary tables using ```heapq.merge```. This is the basic out-of-core mergesort (Knuth, vol 3, chapter 5.4). As it only reads sequentially from disk, it is much faster. The ~40GB table described above sorts in a few hours.

Implementing this in PyTables is non-trivial. But perhaps we can "merge" our mergesort into ptrepack.

**Comment by 153957** [comment]
Note that this also requires extra disk space for the temporary file, implemented such that one will be created automatically, unless one is provided, This is also quite important, since not everyone has enough free space on their /tmp partition. And the temporary data can not be stored in the final file, because the freed space will not be reclaimed after removing the temporary data.

**Comment by FrancescAlted** [comment]
I see, yes that makes sense.  Are you using SSD's for doing the sort?  Modern SSD disks (specially those with the PCIe interface) have latencies that can be as little as 10 us, that is, 1000x less than HDD's, so I'd say that using SSDs would be perfect for sorting tasks (then you can move the files to slower HDDs).

If you are already using a fast SSD and still you need more speed, then perhaps an additional utility for PyTables would make sense.  What about ptsort?

**Comment by 153957** [comment]
My original test in the first post was done on a single SSD if I recall correctly, otherwise on a RAID0 of two HDD. For the most part we are now using a 12-disk RAID6 array (HDD). The current infrastructure does not allow us to easily add (PCIe) SSDs to the mix. I agree that it would be a good location for source and temporary files, however, the idea of the mergesort is trying to make the reads and writes large sequential blocks.

**Comment by FrancescAlted** [comment]
Well, a good SSD attached to a SATA2 port or USB3 should be an interesting option.  I'd recommend using a Samsung  850 Evo (or Pro if you can afford it).  It happens that I have a 850 Pro in my laptop, so I can make a test for you if you are interested.

**Comment by 153957** [comment]
We do have access to SSDs, I have a 840 EVO on a SATA II port, a MacBook Air with internal SSD and a SM951 with PCIe adapter arriving soon. However, those are not directly connected to our server containing the datasets on which we are working, but I could use them for benchmarks.
