### ISSUE TITLE
Too large constant (<type 'dict'> 390)

### ISSUE THREAD

**Issue by marcjofre** [PyTables/PyTables#520]
Hi all,

Using nuitka compiler in debug mode (--debug). A warning is found for a too large dictionary:

WARNING:Too large constant (<type 
'dict'> 390) encountered at D:\WinPytho
n-64bit-2.7.6.3\python-2.7.6.amd64\Lib\site-packages\tables\_past.py:63.

**Comment by 153957** [comment]
`tables_past.py`? What file is that? It does not seem to exist in the PyTables repository.
Which version of PyTables do you have?

**Comment by marcjofre** [comment]
Thanks for the fast reply and information. I now have updated to tables 3.2.2.

I re-check this issue.

In Windows:
Download whl files (best for your machine) from: http://www.lfd.uci.edu/~gohlke/pythonlibs/
h5py-2.5.0-cp27-none-win_amd64.whl
tables-3.2.2-cp27-none-win_amd64.whl

In the folder containing h5py-2.5.0-cp27-none-win_amd64.whl:

pip install h5py-2.5.0-cp27-none-win_amd64.whl

In the folder containing tables-3.2.2-cp27-none-win_amd64.whl:

pip install tables-3.2.2-cp27-none-win_amd64.whl

**Comment by marcjofre** [comment]
This issue does not appear in tables 3.2.2.

Thanks for the fast help
