### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by tttthomasssss** [PyTables/PyTables#521]
I am on OS X 10.9 and have numpy 1.10.4, numexpr 2.4.6 and hdf5 1.8.16, I have installed hdf5 via brew, hence my hdf5 directory is `/usr/local/Cellar/hdf5`. I have created an env var `HDF5_DIR=/usr/local/Cellar/hdf5` and have tried the following (within a virtualenv):

`pip install tables`
`pip install --install-option="--hdf5=/usr/local/Cellar/hdf5" tables`

both of which fail with the same error:
```
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
```

**Comment by avalentino** [comment]
Hi @tttthomasssss,
unfortunately I have not the possibility to setup a brew environment in this moment.
If I remember well brew installs all headers and libraries (or links them) in `/usr/local` (`bin`, `lib`, etc.) directly.
If this is correct, you should be able to install tables without specify ing any `HDF5_DIR` or `--hdf5` parameters.

Did you already tried it?

**Comment by tttthomasssss** [comment]
Hi @avalentino, removing the env var did indeed help, however i had to manually install the latest version of c-blosc.

But all good and installed now - I'll close the issue; thanks very much for your help!
