### ISSUE TITLE
Filters crashes differently in python 2 vs 3 depending on use of complib in unicode or bytes 

### ISSUE THREAD

**Issue by ssolari** [PyTables/PyTables#522]
I'm trying to write code that is compatible across python 2 and 3. 

In Filters, complib requires a bytes string in python 2 and unicode in python 3?  This makes uniform compatibility a bit tricky.  Any way to unify this, or what is the best way to handle? 

Here is a simple example that raises exceptions differently depending on python 2 or python 3.  Using anaconda for packages.  Tested with python 2.7.9(tables 3.2.0) and python 3.5.0(tables 3.2.2).

    from __future__ import absolute_import, division, print_function, unicode_literals
    from builtins import *
    import tables as tb
    import sys
    PY_VER = sys.version[0]

    if PY_VER == '2':
        filters_bytes = tb.Filters(complevel=5, complib=b'blosc') # pass
        filters_unicode = tb.Filters(complevel=5, complib='blosc') # exception
    elif PY_VER == '3':
        filters_unicode = tb.Filters(complevel=5, complib='blosc') # pass
        filters_bytes = tb.Filters(complevel=5, complib=b'blosc') # exception

**Comment by andreabedini** [comment]
Hi @ssolari, thanks for reporting this.

>  This makes uniform compatibility a bit tricky. Any way to unify this, or what is the best way to handle?

Clearly it's not the best way. Consistent handling of strings in PyTables is in desperate need of some love. It would be great if you could put some thought into this and propose some changes. I can definitely help you through (if you need help at all).

I'd say parameters should alway be strings, not bytes.

**Comment by ssolari** [comment]
@andreabedini thanks for the quick response.
My current work around is when passing a string to complib I perform a check if its python 2 and if so I encode the variable.  I agree parameters should not be bytes so this enables a user to always initialize with string syntax.  Ex:

    complib_var = 'blosc'
    if PY_VER == '2':
        complib_var = complib_var.encode()
    filters = tb.Filters(complevel=5, complib=complib_var)

In python 2 it doesn't matter if the string has already been encoded, the .encode() will not throw an exception in python 2 (compared to python 3), so this guarantees python 2 will always work.   Python 3 will only have a problem if complib_var is initialized as bytes which shouldn't be allowed anyway.   

Maybe its simple enough to do the exact same check within the Filters object on complib.  If so, this would fix this particular problem to the outside user and may provide a possible simple solution for other functions if they have the same problem.

**Comment by avalentino** [comment]
Hi @ssolari 
> if PY_VER == '2':
>    filters_bytes = tb.Filters(complevel=5, complib=b'blosc') # pass
>    filters_unicode = tb.Filters(complevel=5, complib='blosc') # exception

this feels quite strange to me since the two lines should be totally equivalent in Python 2.
I would expect some issue if you use ```complib=u'blosc'```

**Comment by ssolari** [comment]
Sorry for the crazy delay, somehow I didn't have forwarding on or didn't see the response.

you are correct that simply writing complib='blosc' works in both python 2 and python 3 by default, however, the reason my example fails is the use of _future__ and import builtins *.  Note this is the recommended way of writing code in python to be compatible with both 2 and 3:
http://python-future.org/quickstart.html#if-you-are-writing-code-from-scratch
With the future module as above:

  - b'blosc' is 'str' in python 2 
  - 'blosc' is 'unicode' in python 2
  - b'blosc' is 'bytes' in python 3
  - 'blosc' is 'str' in python 3

This is admittedly a nightmare.  Type checking becomes really nasty and seems to be better avoided. In pytables, it seems the utilsextension.which_lib_version is specified to handle a 'str' so that this breaks when in python 2 the name is passed as 'unicode'.   

I don't know the best solution here since this is down in the Cython realm, which I'm not as familiar with.   While painful, the long term solution is to probably follow the future module suggestions and get pytables compatible with that.

**Comment by ssolari** [comment]
http://python-future.org/compatible_idioms.html#strings-and-bytes

**Comment by andreabedini** [comment]
I forgot to mention that the branch develop contains #493 which merges
Py2/Py3 support into the same code base. It uses six rather than the
more featured python-future. I am sorry but at the moment I don't have
the time to look more into this.

**Comment by ssolari** [comment]
@andreabedini thanks.  Seems that if support for 2.4 and 2.5 is needed then six is the way to go over future, but will probably not be able to fix the issue here as they handle strings slightly differently.
http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six

Given the use of six, this issue is fine being handled by the original work around I suggested, so I'm going to close.
