### ISSUE TITLE
Overwriting a node does not remove the data from the file

### ISSUE THREAD

**Issue by rthouvenin** [PyTables/PyTables#524]
I am in a use case where I want to replace a node (table or array) with another one (that is based on the first one). What I do is I create the second node, put the data in there, and then overwrite the first node. I have tried to either force-rename the second node to the name of the first one, or remove the first node and then rename the second.

In both case, from the file size it looks like the data of the first node is not removed from the file. It is still there, somehow invisible. `ptdump` does not show it.

Here is some code showing what I mean:
```
import tables
import numpy
import os

fp = tables.open_file('data.h5', mode='w')
arr = fp.create_array(fp.root, 'array1', atom=tables.IntAtom(), shape=(1000, 100))
data = numpy.random.randint(0, 255, (1000, 100))
arr[:] = data
fp.flush()

fileinfo = os.stat('data.h5')
print('File size 1: %d' % fileinfo.st_size)

arr = fp.create_array(fp.root, 'array2', atom=tables.IntAtom(), shape=(100, 10))
data = numpy.random.randint(0, 255, (100, 10))
arr[:] = data
fp.close()

fileinfo = os.stat('data.h5')
print('File size 1+2: %d' % fileinfo.st_size)

fp = tables.open_file('data.h5', mode='a')
fp.remove_node(fp.root, 'array2')
fp.close()

fileinfo = os.stat('data.h5')
print('File size 1+2-2: %d' % fileinfo.st_size)

fp = tables.open_file('data.h5', mode='a')
arr = fp.create_array(fp.root, 'array3', atom=tables.IntAtom(), shape=(100, 10))
data = numpy.random.randint(0, 255, (100, 10))
arr[:] = data
fp.flush()

fileinfo = os.stat('data.h5')
print('File size 1+3: %d' % fileinfo.st_size)

fp.remove_node(fp.root, 'array1')
fp.flush()
arr.move(newname='array1', overwrite=True)
fp.close()

fileinfo = os.stat('data.h5')
print('File size 1+3-1: %d' % fileinfo.st_size)
```

On my computer this displays:
```
File size 1: 404192
File size 1+2: 408192
File size 1+2-2: 404192
File size 1+3: 410240
File size 1+3-1: 410240   <-- This should be about 4000...
```

I have tried various combinations of `File.remove_node()`, `Node.remove()`, `Node._f_rename()`, etc. with always the same result.
I am on Linux with Python 2.7 and Pytables 3.1.1

**Comment by rthouvenin** [comment]
My bad, I probably didn't use the right search keywords yesterday, but today I found this question on the group: https://groups.google.com/forum/#!topic/pytables-users/pr8sYZCbB7g

So this seems to be working as designed...
While the answer mentions that adding new data may re-use the wasted space, my tests and the [HDF5 docs](http://www.hdfgroup.org/HDF5/doc/UG/HDF5_Users_Guide-Responsive%20HTML5/index.html#t=HDF5_Users_Guide%2FDatasets%2FHDF5_Datasets.htm) seem to say the space cannot be reclaimed at all, the only way is to create a new file.

**Comment by andreabedini** [comment]
Don't forget we have tools such ptrepack or h5repack.

**Comment by rthouvenin** [comment]
Thanks Andrea for reminding!
In my case this happens in a webapp, therefore it has to be done in an automated way. So after an operation that generates a lot of wasted space I use `tables.File.copy_file()` (or `tables.copy_file()`) and `shutil.move()` to copy the file over itself. In case this helps anyone :)
