### ISSUE TITLE
Library not loaded: /usr/local/lib/libhdf5.9.dylib

### ISSUE THREAD

**Issue by HackerMD** [PyTables/PyTables#526]
After upgrading `HDF5` via homebrew (from version 1.8.14 to 1.8.16_1), I can no longer import `pyTables`.

```
----> 1 import tables

/Users/mdh/Envs/tmlibrary/lib/python2.7/site-packages/tables/__init__.py in <module>()
     80 
     81 # Necessary imports to get versions stored on the cython extension
---> 82 from tables.utilsextension import (
     83     get_pytables_version, get_hdf5_version, blosc_compressor_list,
     84     blosc_compcode_to_compname_ as blosc_compcode_to_compname,

ImportError: dlopen(/Users/mdh/Envs/tmlibrary/lib/python2.7/site-packages/tables/utilsextension.so, 2): Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /Users/mdh/Envs/tmlibrary/lib/python2.7/site-packages/tables/utilsextension.so
  Reason: image not found
```

There is a file `/usr/local/lib/libhdf5.10.dylib`, which is not picked up.

I've tried setting `HDF5_DIR` and reinstalling `pyTables` as specified in the manual, but that didn't help either.

Any idea?

**Comment by avalentino** [comment]
If my understanding i correct the change in the dylib version indicates an ABI change.
You should re-build/install pytables in order to get it working with the new hdf5 version.

**Comment by HackerMD** [comment]
I did `pip uninstall tables` and then `pip install tables`. Same error.

**Comment by avalentino** [comment]
Can you please post the build log?

**Comment by HackerMD** [comment]
Upon running `pip install tables -v` I realised that the wheel got cached. After removing the cached wheel link, *pyTables* got re-build upon re-installation. Import works now. Sorry for the inconvenience! It's kinda obvious, but maybe you can add it to the documentation.

**Comment by andreabedini** [comment]
We should add a note in the README about pip caching wheels.

**Comment by loicnassi** [comment]
Hi all, 
I have the same issue as in the first message. I'd like to have more information on:

> Upon running `pip install tables -v` I realised that the wheel got cached. After removing the cached wheel link, _pyTables_ got re-build upon re-installation. Import works now. Sorry for the inconvenience! It's kinda obvious, but maybe you can add it to the documentation.

In order to do the same
