### ISSUE TITLE
Anaconda pytables requires numexpr 2.4*

### ISSUE THREAD

**Issue by MSeifert04** [PyTables/PyTables#527]
It seems like ``pytables`` does not accept a new version of ``numexpr`` (v 2.5) and resulted on my installation in some dependency conflicts. Probably this is somehow ``Anaconda-build`` related but I don't know if/how I can check this.

I encountered the problem and issued it at the [conda-issues](https://github.com/conda/conda/issues/2052#issuecomment-193272443) but it seems more pytables or anaconda related. Feel free to close it again if I'm wrong in posting it here.

**Comment by FrancescAlted** [comment]
Uh, there is nothing in PyTables that requires numexpr 2.4*, and in fact, I can run PyTables tests cleanly using numexpr 2.5.  I would say this is an Anaconda issue, so I will close this.  Please feel free to reopen in case I am wrong.
