### ISSUE TITLE
Library not loaded: /usr/local/lib/libhdf5.9.dylib

### ISSUE THREAD

**Issue by Wzongan** [PyTables/PyTables#528]
Hi, 
Thank you for developing and maintaining PyTables. It's an awesome library. 

Recently, I found I cannot `import tables` on my Mac after once `brew upgrade`. 
Here's what I've got: 

```
import tables as tb 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-57032f570037> in <module>()
----> 1 import tables as tb

/usr/local/lib/python2.7/site-packages/tables/__init__.py in <module>()
 80 
 81 # Necessary imports to get versions stored on the cython extension
 ---> 82 from tables.utilsextension import (
 83     get_pytables_version, get_hdf5_version, blosc_compressor_list,
 84     blosc_compcode_to_compname_ as blosc_compcode_to_compname,

 ImportError: dlopen(/usr/local/lib/python2.7/site-packages/tables/utilsextension.so, 2): Library not loaded: /usr/local/lib/libhdf5.9.dylib
 Referenced from: /usr/local/lib/python2.7/site-packages/tables/utilsextension.so
 Reason: image not found
```

I found that instead of having **libhdf5.9.dylib** in the directory, I have **libhdf5.10.dylib** now.
I can uninstall and install hdf5 without a problem and I also tried to reinstall tables.
I have updated the PyTables to the latest stable version with `pip install tables --upgrade`. 

Could anyone help me ? Thank you !

**Comment by Wzongan** [comment]
Problem solved by installing the developing version from GitHub.

**Comment by avalentino** [comment]
@Wzongan yes, after an update of HDF5 you need to re-build PyTables
