### ISSUE TITLE
Setting cache slots parameter less than 10 never removes items from the cache

### ISSUE THREAD

**Issue by grahamrjuk** [PyTables/PyTables#529]
If I set a cache slots parameters to a value less than 10 - for example ```COND_CACHE_SLOTS``` - the number of items the ```NailedDict``` decides to remove is 0 (integer value of 10% of the parameter).

The cache then grows forever.

It is possible that such a small cache is not considered sensible but I don't see any documentation saying there is a minimum.

Suggest making the calculation of the number to remove always remove 1 cache entry, instead of none, or set a minimum cache slots of 10.

**Comment by FrancescAlted** [comment]
Good point.  I am +1 on always removing 1 cache entry at least and +0 for a minimum cache slots.  Would you mind providing a PR?

**Comment by FrancescAlted** [comment]
Fixed in #530.
