### ISSUE TITLE
Test failure: Checking rename_node (over Groups without children) ... Segmentation fault

### ISSUE THREAD

**Issue by cbaines** [PyTables/PyTables#532]
I am running the tests as of this commit 76736ee55850e37eab9ddde78bef7f8a0b3351a1 on a up to date Debian Sid machine. The same test also fails in the Debian CI system [1], which gives precise version information about everything in the environment.

This issue also causes the Debian package to fail to build from source, for which there is an issue here [2].

Let me know if I can do anything to help debug this :)

1: https://ci.debian.net/packages/p/pytables/unstable/amd64/
2: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818501

```
test10_goto (tables.tests.test_do_undo.PersistenceTestCase)
Checking mark names (goto) ... ok
test10_gotoint (tables.tests.test_do_undo.PersistenceTestCase)
Checking mark sequential ids (goto) ... ok
test11_contiguous (tables.tests.test_do_undo.PersistenceTestCase)
Creating contiguous marks ... ok
test12_keepMark (tables.tests.test_do_undo.PersistenceTestCase)
Ensuring the mark is kept after an UNDO operation ... ok
test13_severalEnableDisable (tables.tests.test_do_undo.PersistenceTestCase)
Checking that successive enable/disable Undo works ... ok
test00 (tables.tests.test_do_undo.CreateArrayTestCase)
Checking one action. ... ok
test01 (tables.tests.test_do_undo.CreateArrayTestCase)
Checking two actions. ... ok
test02 (tables.tests.test_do_undo.CreateArrayTestCase)
Checking three actions. ... ok
test03 (tables.tests.test_do_undo.CreateArrayTestCase)
Checking three actions in different depth levels. ... ok
test00 (tables.tests.test_do_undo.CreateGroupTestCase)
Checking one action. ... ok
test01 (tables.tests.test_do_undo.CreateGroupTestCase)
Checking two actions. ... ok
test02 (tables.tests.test_do_undo.CreateGroupTestCase)
Checking three actions. ... ok
test03 (tables.tests.test_do_undo.CreateGroupTestCase)
Checking three actions in different depth levels. ... ok
test00 (tables.tests.test_do_undo.RenameNodeTestCase)
Checking rename_node (over Groups without children) ... [1]    24311 segmentation fault  env PYTHONPATH=. python2.7 tables/tests/test_all.py -vvv
```

**Comment by andreabedini** [comment]
hi @cbaines thanks for reporting this. Any chance you can get a stack trace? you probably need to run `gdb --args python -m tables.tests.test_do_undo` or something similar.

**Comment by cbaines** [comment]
I have attached [backtrace.txt](https://github.com/PyTables/PyTables/files/179470/backtrace.txt).

Let me know if I can generate a more useful backtrace somehow? I have tried running with python2.7-dbg, but I get this error (I think this is in numpy? but I have the python-numpy-dbg package installed):
```
/usr/bin/python2.7-dbg: tables/utilsextension.so: undefined symbol: Py_InitModule4_64
```

**Comment by cbaines** [comment]
Found some help to get a better backtrace. Ended up building with:
```
CFLAGS="-ggdb" CXXFLAGS="-ggdb" python2.7-dbg setup.py build --debug
```

[backtrace2.txt](https://github.com/PyTables/PyTables/files/179568/backtrace2.txt)

**Comment by andreabedini** [comment]
Good work @cbaines, much appreciated. I hope I will have time to have a look soon.

**Comment by detrout** [comment]
I'm affected by this bug on Debian as well. It seems to have something to do with indexes.

the following test modules segfault

tests_do_undo, tests_index_backcompat, test_indexes, test_indexvalues, test_nestedtypes, test_numpy, test_queries

I went looking with prints in the test_do_undo and test_indexes and eventually it crashes In node.py:265 at the self._g_new in this block. I wrapped it with a print before and after it, and if it segfaults I never see the print following _g_node. However there are many situations where the call does work. I'm not sure whats different.

        try:
            # hdf5extension operations:
            #   Update node attributes.
            self._g_new(parentnode, name, init=True)
            #   Create or open the node and get its object ID.
            if new:
                self._v_objectid = self._g_create()
            else:
                self._v_objectid = self._g_open()

**Comment by detrout** [comment]
I got closer to the problem, the segfault in test_indexes and test_do_undo is at this piece of the cython code. The cython debugger macros aren't working for me.

Debian is shipping cython version 0.23.4+git4-g7eed8d8-1 and libhdf5 1.8.16+docs-6

Are you allowed to call __Pyx_DECREF on a null pointer?

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x00007fffee8926bf in __pyx_pf_6tables_13hdf5extension_4Node__g_new (
    __pyx_v_self=__pyx_v_self@entry=0x7fffed6f3d58, 
    __pyx_v_where=<IndexesTableG(_v_file=<File(format_version='2.1', _open_count=1, isopen=1, _node_manager=<NodeManager(registry=<WeakValueDictionary(_iterating=set(), _pending_removals=[], _remove=<function at remote 0x7ffff6c35338>, data={'/agroup/anarray1': <KeyedRef at remote 0x7fffed724f38>, '/agroup/agroup3': <KeyedRef at remote 0x7fffed724960>, '/array': <KeyedRef at remote 0x7fffed7249e8>, '/': <KeyedRef at remote 0x7fffed724eb0>, '/_i_table': <KeyedRef at remote 0x7fffed724c08>, '/agroup/anarray2': <KeyedRef at remote 0x7fffed724e28>, '/agroup': <KeyedRef at remote 0x7fffed724c90>, '/anarray': <KeyedRef at remote 0x7fffed724a70>, '/_i_table/var1': <KeyedRef at remote 0x7fffed6d7300>, '/agroup2': <KeyedRef at remote 0x7fffed724d18>, '/table': <KeyedRef at remote 0x7fffed724da0>}) at remote 0x7fffed6c7190>, node_factory=<method at remote 0x7ffff7e30218>, cache=<tables.lrucacheextension.NodeCache at remote 0x7fffed725f58>) at remote 0x7ffff6356ef8>, _v_objectid=16777216, root_uep='/', mode='w', _isPTFile=True, root=<Roo...(truncated), __pyx_v_name='var1', 
    __pyx_v_init=<optimized out>) at tables/hdf5extension.c:10040
10040     __Pyx_DECREF(__pyx_v_self->name);
(gdb) p __pyx_v_self->name
$8 = 0x0
(gdb) p *__pyx_v_self
$10 = {
  ob_base = {
    _ob_next = 0x7fffed6f69f8, 
    _ob_prev = 0x7ffff18044b8, 
    ob_refcnt = 10, 
    ob_type = 0x1190168
  }, 
  name = 0x0, 
  parent_id = 0
}
```

**Comment by detrout** [comment]
In cases where __pyx_pf_6tables_13hdf5extension_4Node__g_new executes successfully __pyx_v_self->name = None in the case where it crashes __pyx_v_self->name = 0x0

**Comment by detrout** [comment]
With the patch:
Ran 5814 tests in 177.105s

OK (skipped=178)

No segfaults.
