### ISSUE TITLE
setup.py breaks at not being able to find "-l-lpython2.7"

### ISSUE THREAD

**Issue by chaobin** [PyTables/PyTables#586]
The build fails at an obvious error for not being able to find "-l-lpython2.7".

This is the result of a python-config file (asked by USE_PKGCONFIG in setup.py) that returns the "--libs" as ones with "-l" prefixes in it. Not sure if this happens to anyone else, but it did with my environment where the cpython is a custom build, which however I don't think should be too much different from non-custom build. So I think that using python-config to get libraries for linking will fail for everyone here.

The fix I used was quick one, by prep-pending a line before "utilsExtension_libs = LIBS + ADDLIBS" that cleans the LIBS so that library names in it doesn't have the "-l" prefix.

**Comment by avalentino** [comment]
Python 2.7 is no longer supported
