### ISSUE TITLE
Testing against HDF5 1.10 was not merged

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#591]
2bbfa36 was not merged in the PR for HDF5 1.10 support. 
This commit updated `appveyor.yml` to more readable syntax and adds testing against HDF5 v1.10 (as well as keep testing against 1.8.x).

I have opened this issue, because I just noticed the appveyor script is still "old syntax".  I'll provide a PR with the commit etc once time permits.

**Comment by avalentino** [comment]
Sorry @tomkooij .
Should be fixed in a3558635cf304e3ff0b2e5fec84f729350be8bc2
