### ISSUE TITLE
SWMR support with HDF5 1.10?

### ISSUE THREAD

**Issue by ssolari** [PyTables/PyTables#596]
Will the Single Write Multiple Read functionality be supported in Pytables with the 1.10 release? #582

**Comment by avalentino** [comment]
@ssolari no sorry no SWMR in PR #582. It is just a fix to allow people to build the current version of pytables with HDF5 1.10. It do

**Comment by slidenerd** [comment]
Has this been updated to support multiple readers?

**Comment by stephencostiniano** [comment]
Do SWMR Support is available

**Comment by tomkooij** [comment]
SWMR is currently not supported
