### ISSUE TITLE
PyTables 2.4.0 thinks numpy 1.12.0 is older than 1.4.1

### ISSUE THREAD

**Issue by prehensilecode** [PyTables/PyTables#601]
I have to use PyTables 2.x for GroopM.

Anyway:
- Python 2.7.13
- numpy 1.12.0
- numexpr 2.6.2
- wheel 0.29.0
- setuptools 34.2.0

Trying to build from source: python setup.py bdist_wheel

    `.. ERROR:: You need numpy 1.4.1 or greater to run PyTables!`

**Comment by prehensilecode** [comment]
Sorry, I couldn't find the appropriate branch to check out to submit a pull request. Here's a fix to do a proper version comparison.

`--- setup.py.orig       2012-07-20 16:03:50.000000000 -0400
+++ setup.py    2017-02-22 10:56:13.558487862 -0500
@@ -49,6 +49,14 @@
 if not (sys.version_info[0] >= 2 and sys.version_info[1] >= 4):
     exit_with_error("You need Python 2.4 or greater to install PyTables!")
 
+# Version comparison 
+# cribbed from: https://zxq9.com/archives/797
+def ver_tuple(z):
+    return tuple([int(x) for x in z.split('.') if x.isdigit()])
+
+def ver_cmp(a, b):
+    return cmp(ver_tuple(a), ver_tuple(b))
+
 # Check for required Python packages
 def check_import(pkgname, pkgver):
     try:
@@ -58,7 +66,7 @@
                 "You need %(pkgname)s %(pkgver)s or greater to run PyTables!"
                 % {'pkgname': pkgname, 'pkgver': pkgver} )
     else:
-        if mod.__version__ < pkgver:
+        if ver_cmp(mod.__version__, pkgver) < 0:
             exit_with_error(
                 "You need %(pkgname)s %(pkgver)s or greater to run PyTables!"
                 % {'pkgname': pkgname, 'pkgver': pkgver} )`

**Comment by tomkooij** [comment]
Thanks for reporting. And thanks for the fix, but PyTables 2.x is no longer supported. Current version is 3.3.0, but the API changed in 3.x and the old API was removed in 3.3.0.

You can use 3.2.x if you need a PyTables version that supports numpy>=1.8.
