### ISSUE TITLE
Python 3.6 wheel

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [PyTables/PyTables#602]
Please provide py3.6 wheel on PyPI, the source installation is taking too much time and troubles.

**Comment by tomkooij** [comment]
+1
The requirements should all be available. 

I started the 3.6 builds on appveyor and travis. If succesful, I will try to upload them ASAP. If something breaks, it may take longer :-)

**Comment by tomkooij** [comment]
I uploaded the win32 and x64 windows wheels to PyPI.

Unfortunately the builds failed for Linux and OSX. Working on it.

**Comment by tomkooij** [comment]
All wheels are on: http://wheels.scipy.org/ and Mac OSX wheel will be on PyPI soon.
