### ISSUE TITLE
multithread read hdf5 leads python crash!

### ISSUE THREAD

**Issue by yaniszhang** [PyTables/PyTables#603]
I'm using pandas which reading hdf file with pytables
multithread reading hdf file in 'r' mode
like this
with ThreadPoolExecutor(max_workers=10) as exe:
      with HDFStore("file.h5", "r") as hdf:
               exe(hdf_select, *arg)
python crash
but multiprocess with ProcessPoolExecutor is ok 
anybody know why?

window 7 python 3.5 64bit pytables 3.3

**Comment by tomkooij** [comment]
PyTables and/or the HDF5 library are not thread safe:
http://www.pytables.org/latest/cookbook/threading.html

**Comment by lafrech** [comment]
The docs read

> **Warning HDFStore is not-threadsafe for writing.** The underlying PyTables only supports concurrent reads (via threading or processes). If you need reading and writing at the same time, you need to serialize these operations in a single thread in a single process. You will corrupt your data otherwise. See the (GH2397) for more information. 

Should it be fixed to say that even read operations are not thread-safe?

**Comment by jsancho-gpl** [comment]
I cannot find that paragraph to fix it. Can you provide a link?

**Comment by lafrech** [comment]
Here it is: https://pandas.pydata.org/pandas-docs/stable/io.html#caveats

Thanks.

**Comment by jsancho-gpl** [comment]
I'm sorry, but that is Pandas documentation and we don't have access to their repository. Pandas uses PyTables for accessing to HDF files. I've redirected the issue to Pandas team.

**Comment by lafrech** [comment]
Oh right. Facepalm. I stumbled here while investigating that Pandas/PyTables thread-safety issue and didn't notice it was pytables bugtracker.

Sorry for the noise. And thanks for [redirecting](https://github.com/pandas-dev/pandas/issues/21100).
