### ISSUE TITLE
py-cpuinfo not working on ARM64

### ISSUE THREAD

**Issue by issamu2k** [PyTables/PyTables#604]
Please, update py-cpuinfo to latest version 3.0.0.
This version in project is broken for ARM64 cpus.

**Comment by tomkooij** [comment]
We will get rid of the vendored `cpuinfo.py` and make `py-cpuinfo` a dependency for the 3.4 release.

In the meantime you can delete `cpuinfo.py` in the pytables root folder and `pip install py-cpuinfo`
