### ISSUE TITLE
No PEP8 checking (and many PEP8 errors)

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#612]
TLDR: We need a PEP8 code quality checks in CI.

Release 3.4.0 is broken because of a failure in `ptrepack`. But even with testing `ptrepack -h` on CI systems it remains broken because of a `NameError` exception. Fixed in `v3.4.1`.

This could have been spotted by `flake8`.

I have no time at the moment, but it would be very nice to have to add `flake8` to tests and fix the current PEP8 failures. 

This would be a great project for a new contributor!

**Comment by avalentino** [comment]
+1
