### ISSUE TITLE
PDF docs build fails

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#613]
`make dist` fails on the LaTeX pdf docs:

```
! Package inputenc Error: Unicode char ℏ (U+210F)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
```

I haven't been able to build `usersguide.pdf` for `v3.4.1`.

**Comment by andreabedini** [comment]
I can confirm, we seem to be using `pdflatex` which doesn't support unicode. I suggest to not block the release on this, it's inessential. Also readthedocs automatically produces a pdf too, so we can fix it there.

**Comment by tomkooij** [comment]
Yep, I've gone ahead and released. (But upload.pypi.org is down...)

**Comment by tomkooij** [comment]
@andreabedini : Can you add readthedocs workflow to the release procedure in the wiki?

**Comment by andreabedini** [comment]
@tomkooij will do, but it am not sure it works just yet ...
