### ISSUE TITLE
illegal instruction in Array.read_array

### ISSUE THREAD

**Issue by robnagler** [PyTables/PyTables#626]
For full discuss see radiasoft/jupyter.radiasoft.org#8 with [the code and input](https://github.com/radiasoft/jupyter.radiasoft.org/files/959602/plot_losses.zip). We use Docker so you can pull (large) image versions where the error does and doesn't occur. The code fails with tables==3.4.1 and 3.4.2 with an illegal instruction.

The Docker image does not fail on Docker running under VM (VirtualBox or HyperKit running on Mac with 2.5 GHz Intel Core i7), but does happen on a bare metal Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz. I don't think this has anything to do with Docker, but thought you should know.

**Comment by tomkooij** [comment]
Thanks for reporting.

Important for investigating:
**Can you elaborate how pytables was built/installed?** From the issue I gather it is install using `pip`. Built from the sdist or wheel?
**Can you post the output of** `tables.print_versions()`?

If this  is an illegal instruction (even on a fairly recent 2013 Ivy Bridge E5-2650 v2) using our pre built wheels this needs fixing.

Between v3.3.0 and v.3.4.1 there are no changes to `hf5extensions::_read_array()`. We changed the way we build manylinux wheels between v3.4.1 and v3.4.2, but 3.4.1 is failing as well.

I will be away for a few days, but I think I have a machine that reproduces this with a manylinux wheel (`python -m tables.tests.test_all` fails with illegal instruction on an Haswell CPU E5-2680 v3). I'll have a look.

**Comment by tomkooij** [comment]
There is at least a problem:
`libhdf5extension.so` from the py27 3.4.2 manylinux wheel is full of AVX instructions. 

Altough I get an `Illegal Instruction` on a 2014 Haswell CPU E5-2680 v3 as well which supports AVX. It seems this is being compiled with too specific CPU features compiled in. (This explains why it does work on an i7).

**Comment by robnagler** [comment]
Installed with a wheel (I think), because there's a tables-3.4.2.dist-info directory. 

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.4.2
HDF5 version:        1.8.18
NumPy version:       1.9.3
Numexpr version:     2.6.2 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.09 (Feb 04 2015)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.11.3 (2017-03-09)
Blosc compressors:   blosclz (1.0.5), lz4 (1.7.5), lz4hc (1.7.5), snappy (1.1.1), zlib (1.2.8), zstd (1.1.3)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.25.2
Python version:      2.7.10 (default, Mar 31 2017, 16:10:36)
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]
Platform:            Linux-4.9.13-moby-x86_64-with-fedora-21-Twenty_One
Byte-ordering:       little
Detected cores:      4
Default encoding:    ascii
Default FS encoding: UTF-8
Default locale:      (en_US, UTF-8)
```

**Comment by tomkooij** [comment]
@robnagler: Thanks, I'm pretty sure we are building `manylinux` wheels with AVX2 support/opcodes, which should not happen. 

I'll be away for the next few days, but I'll try to fix this (and build generic x86_64 wheels) when I get back.

**Comment by tomkooij** [comment]
I'm quite sure this is a wheel building issue: reported in #627. Closing this.
