### ISSUE TITLE
3.4.0 Release Notes

### ISSUE THREAD

**Issue by llchan** [PyTables/PyTables#629]
It looks like they were written for the 3.4.0 release, but deleted on the way to 3.4.1.

**Comment by tomkooij** [comment]
@llchan : Nice spot. You're right. I'll re-add them.

**Comment by tomkooij** [comment]
Fixed in 3047c26814e229c988bd065e74e2df39d64e3ce2

http://www.pytables.org/release-notes/RELEASE_NOTES_v3.4.x.html
