### ISSUE TITLE
Windows wheel in PyPi (at least) for py3.6 amd64 is broken

### ISSUE THREAD

**Issue by ankostis** [PyTables/PyTables#635]
According to Gohlke in winpython/winpython#543 the wheel you have distributed in PyPi at least for the version I have checked (Windows, py3.6, amd64) is missing `zlib.dll` and cannot work.

**Comment by tomkooij** [comment]
Thanks for reporting. 

I'll have a look.

**Comment by sakra** [comment]
32-bit version (win32) is broken as well.

**Comment by tomkooij** [comment]
@sakra: Yes, all windows wheels lack `zlib1.dll` and are broken (if used outside of a conda env).

I've fixed wheel building, however numpy 1.13.x seems to break pytables 3.4.2...

**Comment by tomkooij** [comment]
Numpy 1.13.1 will fix this, so I'll wait until that is release and rebuild the wheels.

If somebody is really keen on wheels and/or needs them in a hurry I can provide them, but I'm confident there are enough alternatives and this can wait.

**Comment by tomkooij** [comment]
wheels (with zlib.dll included) uploaded to PyPI. Closing.
