### ISSUE TITLE
DataTypeWarning for unsupported user attribute that is of None type

### ISSUE THREAD

**Issue by weiji14** [PyTables/PyTables#647]
Reposting this from https://github.com/pandas-dev/pandas/issues/17661

#### Code Sample

```python
import os
import pandas as pd
h5file = os.path.join(os.getcwd(), "GLAH12_634_1102_001_0071_0_01_0001.H5")
tables.is_hdf5_file(h5file)
pd.read_hdf(h5file, key='/Data_40HZ/Geolocation/d_lon')
```
#### Problem description

pandas.read_hdf fails when the HDF5 file has a node with a user defined attribute that is of `None` type. Below is the capture from ViTables of the problematic user attribute.

![screenshot at 2017-09-25 13 36 12](https://user-images.githubusercontent.com/23487320/30788307-a7a83d96-a1f6-11e7-93a8-63377a485879.png)

Links to the code error points to:
- [pytables.py](https://github.com/pandas-dev/pandas/blob/3a7f956c30528736beaae5784f509a76d892e229/pandas/io/pytables.py#L728)
- [attributeset.py](https://github.com/PyTables/PyTables/blob/c71a525d5a8d643a57091a4f3ed51ddccd6b8f9a/tables/attributeset.py#L299)

```
/home/atom/.local/lib/python3.5/site-packages/tables/attributeset.py:299: DataTypeWarning: Unsupported type for attribute 'DIMENSION_LIST' in node 'd_lon'. Offending HDF5 class: 9
  value = self._g_getattr(self._v_node, name)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-73d62d05a23a> in <module>()
----> 1 pd.read_hdf(h5file, key='/Data_40HZ/Geolocation/d_lon')

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    370                                      'contains multiple datasets.')
    371             key = candidate_only_group._v_pathname
--> 372         return store.select(key, auto_close=auto_close, **kwargs)
    373     except:
    374         # if there is an error, close the store

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    726         # create the storer and axes
    727         where = _ensure_term(where, scope_level=1)
--> 728         s = self._create_storer(group)
    729         s.infer_axes()
    730 

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in _create_storer(self, group, format, value, append, **kwargs)
   1220                 else:
   1221                     raise TypeError(
-> 1222                         "cannot create a storer if the object is not existing "
   1223                         "nor a value are passed")
   1224             else:

TypeError: cannot create a storer if the object is not existing nor a value are passed
```

#### Expected Output
HDF5 file loads into a pandas DataFrame without any errors. Or there should be a way to bypass/ignore the problematic user attribute since it is a metadata issue only.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-96-generic
machine: x86_64
processor: 
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 36.5.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: 0.9.6
IPython: 6.2.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

#### Attached HDF5 file:
[GLAH12_634_1102_001_0071_0_01_0001.H5.zip](https://github.com/pandas-dev/pandas/files/1327908/GLAH12_634_1102_001_0071_0_01_0001.H5.zip)

**Comment by tomkooij** [comment]
Thanks for the extensive report.

Unfortunately, I think PyTables handles this as it should: It's unsupported. The actual code is in `hdf5extension.pyx`: 

https://github.com/PyTables/PyTables/blob/cea3ff8d10262dc8bd431f809716451a446e2cc4/tables/hdf5extension.pyx#L786-L790

`h5py` seems to handles the attached file somewhat better, as it has more types implemented. 

I don't think there is a bug to fix. This will need implementation of the type in PyTables and/or pandas/io/pytables.py.

**Comment by weiji14** [comment]
So there is no setting or way that can bypass or ignore this error? Where would I need to look into if I were to try and implement this `None` type into PyTables.

**Comment by tomkooij** [comment]
@weiji14 I'm guessing (without investigating too much) that you should be able to fix this on the pandas side, by ignoring the `None` type (which is caused by an unsupported type)

About implementing this (yes, please!), look at `_g_getattr` in `hdf5extension.pyx`:

https://github.com/PyTables/PyTables/blob/develop/tables/hdf5extension.pyx#L715-L721

You might want to take a sneak peak at `h5py`:
I think the unimplemented type is an `H5R_OBJECT` (but please check!)

http://api.h5py.org/h5r.html
https://github.com/h5py/h5py/blob/e611b7ca47e49d83e908d0368d2d9ced224a9de0/h5py/h5r.pyx#L145

**Comment by Git-Goud** [comment]
> So there is no setting or way that can bypass or ignore this error? Where would I need to look into if I were to try and implement this `None` type into PyTables.

Hi Weiji14,
Were you able to get pass this error? If so do you mind if I ask you how exactly?
Thank you,

**Comment by weiji14** [comment]
Hi @Git-Goud, to be honest, I can't remember since this was 5 years ago :sweat_smile: I've mostly ended up using `xarray` for reading HDF5 now, e.g. with [`xarray.open_dataset(..., engine="h5netcdf")`](https://docs.xarray.dev/en/v2022.11.0/generated/xarray.open_dataset.html). If you're working with very nested data structures, I can also recommend `xarray-datatree`'s [`datatree.open_datatree`](https://xarray-datatree.readthedocs.io/en/latest/generated/datatree.open_datatree.html).
