### ISSUE TITLE
PyTables interpretation of relative path in ExternalLink inconsistant with HDF5

### ISSUE THREAD

**Issue by heroxbd** [PyTables/PyTables#648]
In `tables/link.py`, relative path of external link is interpretated against the directory of the present file.
```
if not os.path.isabs(filename):
    # Resolve the external link with respect to the this
    # file's directory.  See #306.
    base_directory = os.path.dirname(self._v_file.filename)
    filename = os.path.join(base_directory, filename)
```
However, the [HDF5 reference manual](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5L.html#Link-CreateExternal) specifies that the path relative to **current working directory** is also searched for if the above logic fails.

**Comment by tomkooij** [comment]
This may be true, but I honestly wonder if this is a bug, or just something we won't implement. It will probably be superseded by pytables 4 (on top of h5py) anyway.

If it is, please provide a small scripts that demonstrates the failure.

 Better yet, provide a PR with a fix and a regression test. :)

**Comment by heroxbd** [comment]
Cool.  I have found a workaround for this. And let's wait for pytable 4 :)
