### ISSUE TITLE
Filename as pathlib.Path (Python 3.4+)

### ISSUE THREAD

**Issue by eumiro** [PyTables/PyTables#657]
Python 3.4+ has [pathlib.Path](https://docs.python.org/3/library/pathlib.html), a standard library for object oriented filesystem paths. Storing a filename as `Path('/path/to/file.h5')` offers more flexibility and `Path('/path/to').glob('*.h5')` generates `pathlib.Path` objects that could be passed to `tables.open_file`, which currently supports `filename` as `str` only, so one has to write `tables.open_file(str(path_obj))`.

Does it make sense  to extend `tables.open_file` to support `pathlib.Path` as well?

(as a bonus, support `pathlib.Path` also for internal h5 paths, such as `h5file.get_node(pathlib.Path('/a/b/c'))`)

**Comment by FrancescAlted** [comment]
Hi.  Your proposal makes a lot of sense to me.  Interested in providing a PR?

**Comment by tomkooij** [comment]
Might be already implemented by #640

**Comment by eumiro** [comment]
Couldn't see #640 before, thank you for pointing out.
