### ISSUE TITLE
create_table works, but there seems to be no way to modify a scalar

### ISSUE THREAD

**Issue by jason-s** [PyTables/PyTables#659]
https://stackoverflow.com/questions/47837286/modifiying-a-scalar-value-using-pytables

```
h5 = pt.open_file(filename,'r+')
h5.create_array(h5.root.some_group, 'Inom', np.array(Inom), 'Nominal current')
```

I can do

```
h5.root.some_group.Inom.read()
```

but there is no `write` method, and any attempt to write using `[]` fails with an `IndexError:  Too many indices for object '/some_group/Inom'`

**Comment by jsancho-gpl** [comment]
It's possible to modify array elements but there is no way to modify a scalar value. You have to remove it and create it again.
