### ISSUE TITLE
GCC problem

### ISSUE THREAD

**Issue by Blues5** [PyTables/PyTables#671]
I'm trying to train the model from https://github.com/iacercalixto/MultimodalNMT
Error I'm getting is-

File "train_mm.py", line 22, in <module>
    import tables
  File "/home/blues/anaconda3/lib/python3.6/site-packages/tables/__init__.py", line 90, in <module>
    from .utilsextension import (
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/blues/anaconda3/lib/python3.6/site-packages/tables/utilsextension.cpython-36m-x86_64-linux-gnu.so)

**Comment by tomkooij** [comment]
Can you post what enviroment you are using? (It looks like anaconda python 3.6, but I need more info)

``` 
>>> import tables
>>> tables.print_versions()
```

**Comment by tomkooij** [comment]
Looks like you are missing the above lib that is required by the pre-built packages.

This stackoverflow (askubuntu) answer should fix this: https://askubuntu.com/a/582910

Please let us know it this fixes your problem, thanks!

**Comment by Blues5** [comment]
thanks for the help! I re-installed Python and its working fine now.
