### ISSUE TITLE
Fix for #177 still appears broken for frozen apps

### ISSUE THREAD

**Issue by jwiggins** [PyTables/PyTables#675]
The relevant PyInstaller issue is here: https://github.com/pyinstaller/pyinstaller/issues/3407

I believe the original suggestion in #177 to skip the `find_library` checks in https://github.com/PyTables/PyTables/blob/develop/tables/__init__.py#L26-L86 would be better for frozen apps. Ideally, testing on an un-frozen version should have already established that the HDF5 library is correctly installed.

PyInstaller _is_ doing some monkey patching which interacts badly with PyTables, which I pointed out in the above linked issue. Again, just skipping the check when `sys.frozen` is `True` would bypass the problem.

**Comment by tomkooij** [comment]
@jwiggins : Let's just fix this. Can you provide a PR with that original fix from #177 implemented (again)? LGTM.

**Comment by jwiggins** [comment]
@tomkooij Done!
