### ISSUE TITLE
is there any out-of-core way to do sum for each row of array?

### ISSUE THREAD

**Issue by braindevices** [PyTables/PyTables#678]
say we have a 2D EArray `A` we can use `tb.Expr("sum(A,1)")` I guess. But If we have N-D EArray with shape `(M0, M1...Mn)` How can I do the sum out-of-core over each row to obtain 1-D array with shape `(M0,)` ?
For an array can be fit into memory, we can of course read and reshape the EArray to 2D with shape `(M0, M1*...Mn)`. However, in most cases, we will have super large array can only located on disk for pytables users.

**Comment by jsancho-gpl** [comment]
Hi. Pytables doesn't support numexpr completely, because some operations are really hard to accomplish due to the high volume of data. In this case, there is no way to calculate separate sums by axis.
