### ISSUE TITLE
No wheels for version 3.4.3

### ISSUE THREAD

**Issue by rnestler** [PyTables/PyTables#683]
I just noticed that tables 3.4.3 got released without any wheels but only with the source package (https://pypi.org/project/tables/3.4.3/#files).
Is this intentional or will the wheels follow?

**Comment by rnestler** [comment]
Ah I just saw in https://github.com/PyTables/PyTables/pull/681 that wheels are still on the todo list. So they will probably follow.

**Comment by rnestler** [comment]
Ah I just saw in https://github.com/PyTables/PyTables/pull/681 that wheels are still on the todo list. So they will probably follow.

**Comment by jordansamuels** [comment]
Is this the cause that while 3.4.2 worked fine, `pip install tables` now gets:

```
 /usr/bin/ld: cannot find -lhdf5
```

?

**Comment by tomkooij** [comment]
We will try to get the wheels up today or tomorrow

**Comment by tomkooij** [comment]
Wheels are on pypi! Closing.
