### ISSUE TITLE
Python 3.7 wheel files

### ISSUE THREAD

**Issue by gokceneraslan** [PyTables/PyTables#704]
Any plans to compile python 3.7 wheel files? People who used pytables without libhdf5 are having compilation problems now, since py3.7 wheel file is missing e.g. https://github.com/PyTables/PyTables/issues/702.

**Comment by mimischi** [comment]
Any update on this? Don't want to explicitly add it as a hard dependency, because `pytables` is also only pulled in from another dependency of ours.

**Comment by FrancescAlted** [comment]
No sorry.  Currently PyTables is out of funds for doing this sort of maintenance work.  If you would like to improve things about this, you might want to consider donating to the project via [NumFOCUS](https://numfocus.org/).

**Comment by nonZero** [comment]
AFAIK appveyor has a free tier for open source projects allowing free and automatic builds: <https://packaging.python.org/guides/supporting-windows-using-appveyor/>.
Can I help setting this up for pytables?

**Comment by nonZero** [comment]
brrr... Strangly it is not as simple as I thought... 
https://github.com/matthew-brett/multibuild/issues/217

**Comment by tomkooij** [comment]
I have uploaded the Windows python 3.7 wheels to PyPI.

Sadly, the ManyLinux and MacOSX wheels fail to build.

**Comment by nonZero** [comment]
@tomkooij I believe you can still copy the artifacts built on travis.ci.

**Comment by nonZero** [comment]
Does this help: https://github.com/nonZero/pytables-wheels/tree/linux_osx_py37 ?

**Comment by nonZero** [comment]
Upgrading numpy works for linux in this commit: https://travis-ci.org/nonZero/pytables-wheels/builds/468916665
It does not work for OSX.

**Comment by nonZero** [comment]
> @nonZero: I'm having some trouble with the wheels. But I'm guessing this is my local installation, as the wheels pass the tests on AppVeyor.

Are you testing with the same numpy version?

**Comment by tomkooij** [comment]
> Are you testing with the same numpy version?

Yes. But the wheel seems to be missing the HDF5 library.

**Comment by clbarnes** [comment]
Here's a minimal repo with a travis build demonstrating the problem: https://github.com/clbarnes/pytables_travis

What is the actual solution here? Obviously it would be nice if the wheels were built and uploaded from CI, but until then, what concrete steps should a pytables user follow?

**Comment by coulanuk** [comment]
FYI the following work-around will install pytables with Python 3.7 on Ubuntu 18.04; this allows pandas to call read_hdf() etc.  NB libhdf5-dev is installed first.

sudo -H env CPPFLAGS=-I/usr/include/hdf5/serial \
LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial pip3 install --upgrade tables

**Comment by Peque** [comment]
Any updates on this matter? :innocent:

**Comment by yetudada** [comment]
I would also like to check in on this one. What can we do to help?

**Comment by jetuk** [comment]
It's my understanding that this will become a lot easier once `manylinux2010` is rolled out. That is quite close to happening. I will try to test whether `pytables` / HDF install correctly on the proposed environment. 

See this issue for more details: https://github.com/pypa/manylinux/issues/179

**Comment by FrancescAlted** [comment]
[Wheel files for Python 3.7 have been uploaded to PyPI](https://pypi.org/project/tables/#files).  Closing.

**Comment by nathanielatom** [comment]
May I ask if the process for building wheels has been simplified and/or automated? Is this likely to recur for python 3.8? (Will we have to re-invent the wheel? ok sorry, couldn't resist ;)

I'm creating an installation script, and I'm wondering whether it's sufficient to use `setup.py` to just install the wheels from pypi with `install_requires` or whether it should explicitly install hdf5 and compile from source.

Thanks! The wheels are highly appreciated.
