### ISSUE TITLE
H5Rdereference API change in HDF5 head

### ISSUE THREAD

**Issue by schwehr** [PyTables/PyTables#708]
In `utilsextension.pyx`:
```py
refobj_id = H5Rdereference(dataset_id, H5R_OBJECT, &refbuf[i])
```

Should (I think...) become
```py
refobj_id = H5Rdereference(dataset_id, H5P_DEFAULT, H5R_OBJECT, &refbuf[i])
```

HDF5:

```c
hid_t H5Rdereference(hid_t id, H5R_type_t ref_type, const void *_ref)
```
becomes
```c
hid_t H5Rdereference(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *_ref)
```

**Comment by ztnark** [comment]
@schwehr Did you find a solution to this issue?

**Comment by schwehr** [comment]
I edited the file as described above and it might be working...  I'm not sure if anyone is using that code path.  It builds and none of the users of pytablers in the system are complaining :|  There are a lot of people using pytables in it, but I don't know much about what they do.

**Comment by FrancescAlted** [comment]
The `H5Rdereference` signature changed in HDF5 1.10, but PyTables only supports the HDF 1.8 API, so the `hid_t H5Rdereference( hid_t obj_id, H5R_type_t ref_type, void *ref )` is the one to be used.  In which situations is this posing a problem to you?  Please offer details of your environment (HDF5 version= conda? OS? are you compiling by yourself and if so how?).

**Comment by schwehr** [comment]
My build is internal to Google built with bazel.  It's a custom linux with numpy 1.13.3, HDF5 close to 1.10 ( @ 807187e2f200e63adb4918dd475d47546c8588e9 ).  pytables 3.4.4

**Comment by FrancescAlted** [comment]
Uh, I am afraid that we still need more info if we want to debug the root of the problem.  Could you please provide some detailed steps for get PyTables installed on your system?  A sequence of the command lines used would be great.

**Comment by schwehr** [comment]
This was really just a note about one part of what it takes to build pytables with hdf5 head.

I can't really share the really custom env.  But here are some of the tweaks from the build of py/tables

    "-Wno-incompatible-pointer-types",
    "-Wno-maybe-uninitialized",
    "-Wno-self-assign",
    "-Wno-switch",
    "-Wno-tautological-compare",
    "-Wno-unused-function",
    "-fno-strict-aliasing",
    "-DNDEBUG",

And hdf5:

    "-DH5_HAVE_THREADSAFE",
    "-DH5_HAVE_PTHREAD_H",
    "-DNDEBUG",
    "-D_LARGEFILE64_SOURCE",
    "-Wno-format",
    "-Wno-implicit-function-declaration",
    "-Wno-incompatible-pointer-types",
    "-Wno-incompatible-pointer-types-discards-qualifiers",
    "-Wno-non-literal-null-conversion",
    "-Wno-self-assign",
    "-Wno-sometimes-uninitialized",
    "-Wno-unused-label",
    "-Wno-unused-variable",

And from H5config.h:

```
/* Define to the full name and version of this package. */
#define PACKAGE_STRING "HDF5 1.11.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "hdf5"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.11.2"
```

**Comment by FrancescAlted** [comment]
I think HDF5 1.11.x is mainly used for development and should be used for production.  I am going to close this, but if it keeps crashing using 1.8.x or 1.10.x (i.e. the stable HDF5 versions), please re-open this.

**Comment by schwehr** [comment]
Was never a crash.  I just won't build

**Comment by schwehr** [comment]
And I try to follow "live at head"
