### ISSUE TITLE
pandas Importerror for pytables > 3.4.2

### ISSUE THREAD

**Issue by mullenkamp** [PyTables/PyTables#713]
Something changed in pytables from 3.4.2 to 3.4.3 to cause an import error when used in conjunction with Pandas:

```
ImportError: HDFStore requires PyTables, "DLL load failed: The specified module could not be found." problem importing
```

This the associated reference issue at pandas:
https://github.com/pandas-dev/pandas/issues/23773

Thanks.

**Comment by FrancescAlted** [comment]
I tried to reproduce your problem, but current pandas (0.24.1) seems to work well with current pytables (3.4.4).  I am closing this, but feel free to re-open it if you continue experiencing problems.

**Comment by ajennings6767** [comment]
I am having similar issues, despite having the distributions you indicated above:

![image](https://user-images.githubusercontent.com/30580411/55883928-2d404a00-5b75-11e9-8949-544e5ad997f5.png)

Any thoughts?
