### ISSUE TITLE
Hdf5.dll is outdated

### ISSUE THREAD

**Issue by dickreuter** [PyTables/PyTables#715]
The current version of hdf5.dll is outdated in pytables. As a result, pytables cannot be imported at the same time as the hdf5 module.

**Comment by tomkooij** [comment]
@dickreuter : Can you be more specific? Are you referring to wheels from PyPI? (What are you installing).

Thanks to a user contributing, we should have new wheels up very soon!

**Comment by tomkooij** [comment]
If you install pytabels from the `conda-forge` channel: please report it over at github.com:conda-forge/pytables-feedstock. Make sure you post the output of `conda info` and `conda list` and preferably post a very short piece of code that shows the failure. (In this case two imports, i guess)

If this is from the `defaults` channel. Please report it over at the anaconda folks. (Not sure where exactly).

**Comment by tacaswell** [comment]
xref https://github.com/h5py/h5py/issues/1142

**Comment by stefanoborini** [comment]
Confirm same problem on windows. The problem used to be solved in 2008 by h5py

https://github.com/h5py/h5py/issues/16

by renaming the libraries, so that you could have both in the same address space, but today the libs are still back to the old name hdf5.dll. Of course you can still have conflicts at the code level, but that solution might work again. Ideas?

**Comment by tomkooij** [comment]
The only real solution is to rename the vendored `hdf5.dll` as stated above. If not: Welcome to DLL Hell.

There are currently no plans to start renaming hdf5.dll for our wheels. But PRs are welcome.

**Comment by stefanoborini** [comment]
@tomkooij what is the reason why the rename was undone?

**Comment by tomkooij** [comment]
@stefanoborini : I'm not sure why the rename was undone on the h5py side. But AFAIK pytables wheelbuilders have never renamed the vendored DLLs.

I'll be glad to support the renaming of vendored wheels, it's just a pain to do automatically. I have no time to set it up. (There is a tool a bit similar to patchelf/auditwheel: https://github.com/njsmith/machomachomangler that might fix this)

**Comment by tomkooij** [comment]
@stefanoborini : I checked: @cgohlke builds the h5py windows wheels. I'll see if it it possible to use *the same* hdf5.dll for pytables wheels. Renaming dlls in our vendored wheels is not trivial.
