### ISSUE TITLE
ValueError: cannot set WRITABLE flag to true of this array

### ISSUE THREAD

**Issue by zimmermm** [PyTables/PyTables#717]
Not sure where I have to report this bug.

Loading a pickled pandas.DataFrame (some columns contain text) via pandas.HDFStore works perfectly fine with numpy 1.15.1 but fails with numpy 1.16.0. The stacktrace finally points to:
``File "tables\hdf5extension.pyx", line 2155, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array
``

Minimal code:
```
import pandas, numpy
df = pandas.DataFrame({'Numbers': numpy.array([1.0, 2.0, 3.0]), 'Text': numpy.array(['Oh', 'hello', 'world'])})
store = pandas.HDFStore("test.h5")
store.put("/test", df)
store.get("/test")
```

I report this from a windows machine, running python 3.7 with numpy+mkl.

**Comment by avalentino** [comment]
Hi @zimmermm, thank you for reporting.
This particular issue should be fixed in master (see f6b64c942fb91e6c261fa455969a38482c22beeb).
I'm closing the issue, but please test your use case against master and reopen if you still have problems.

**Comment by avalentino** [comment]
+1

**Comment by bilalkamoon** [comment]
Hello,
We store gigabytes of data in hdf format, this bug is making our files unreadable. And we can't roll back numpy due to non forward compatibilty. We hope you release the fix as soon as possible.
Thank you for understanding.

**Comment by FrancescAlted** [comment]
Hi.  We are aware of this issue.  My plan is to make a release by the end of the next month (when I think I'll have time for this).  If you want to accelerate things, you can always do a donation to the project via NumFOCUS (https://numfocus.org) and we will try to do our best so as to accelerate things.  Disclaimer: this a project that is mainly run by volunteers on their spare time; thanks for your understanding.

**Comment by elampl** [comment]
!pip install --upgrade tables this helps
