### ISSUE TITLE
Newer versions of zstd (>1.3.4) causes build fail

### ISSUE THREAD

**Issue by taylorsmith-UKY** [PyTables/PyTables#721]
Build fails due to missing struct field. Previously, ZSTD_compressionParameters (defined in zstd.h) contained a field "searchLength", however this was removed after 1.3.4. Pretty sure this can be resolved by updating the version of the source included in PyTables/c-blosc/internal-complibs/

I was able to build succesfully by removing the system zstd library (most recent is 1.3.8) and reinstalling 1.3.1.

**Comment by tomkooij** [comment]
Thanks for reporting. We probably just need to update the internal c-blosc: https://github.com/Blosc/c-blosc
@FrancescAlted

**Comment by FrancescAlted** [comment]
Good point.  It is unfortunate that Zstd changed the ABI during a patchlevel revision (1.3.4).  Expect an update of the internal C-Blosc sources before a new PyTables release (hopefully very soon).

**Comment by FrancescAlted** [comment]
Latest version of blosc has been included in https://github.com/PyTables/PyTables/commit/a5d0152276caf45a4e1ae21ad5623fd843b51f9f.
