### ISSUE TITLE
Python 3.4 wheel for tables-3.5.1

### ISSUE THREAD

**Issue by lissyx** [PyTables/PyTables#727]
It seems there was no wheel for Python 3.4 uploaded on PyPi with the 3.5.1 release, and looking at the release notes I don't see anything mentionning that 3.4 is not supported anymore. Is it just a temporary issue / upload issue, or is 3.4 not supported anymore?

**Comment by FrancescAlted** [comment]
Yes, Python 3.4 reached EOL a few days ago, so I have not bothered to build 3.4 wheels.  Use version pinning in case you need to support old configurations.
