### ISSUE TITLE
Updated NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [PyTables/PyTables#728]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-pytables/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by tomkooij** [comment]
Fixed in 7dc837c
