### ISSUE TITLE
Mock dependency

### ISSUE THREAD

**Issue by kylekeppler** [PyTables/PyTables#729]
Mock was recently added to requirements.txt as a dependency. Setup.py copies requirements.txt to install_requires thus making mock an install time requirement.

The commit shows, and searching the code verifies, that mock is only required for test: https://github.com/PyTables/PyTables/commit/b721f8b19f5e6e48a84bc80ba5c3fd8be95c6b93

Should this really be made an install time requirement? Wouldn't tests_require make more sense?

**Comment by tomkooij** [comment]
`test_require` does make sense *but* if you want to run:

```
python -m tables.tests.test_all
```

After installing the package from source/wheel/conda/etc then you will still need `mock`.

So I figure `mock` might be a runtime dependency. (We want to be able to run the test suite for every install)

I'm not sure which is best. I feel having mock as a runtime dependency is not a big burden.

**Comment by tomkooij** [comment]
Superseded by conda-forge/pytables-feedstock#50

**Comment by danieljacobs1** [comment]
According to https://pypi.org/project/mock/

> mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.

It doesn't look like PyTables supports that old a Python version (the PSF doesn't!), so that sounds like the `mock` dependency can be removed?

**Comment by avalentino** [comment]
+1

**Comment by danieljacobs1** [comment]
And Python 2.7 support has already been dropped https://github.com/PyTables/PyTables/pull/747

**Comment by tomkooij** [comment]
Will do

**Comment by tomkooij** [comment]
Fixed in #759
