### ISSUE TITLE
Reading HDF5 file change the file modification time

### ISSUE THREAD

**Issue by j-muller** [PyTables/PyTables#731]
Dear all,

It seems that starting from the last PyTables version (3.5.1), reading a HDF5 file with the default flags (`mode='a'`) will automatically change the file modification time.
Here is an example:

```
In [1]: import pandas as pd

In [2]: !stat /tmp/foo.h5
  File: ‘/tmp/foo.h5’
  Size: 60440     	Blocks: 120        IO Block: 4096   regular file
...
Access: 2019-03-27 02:44:45.030154807 +0000
Modify: 2019-03-27 02:44:45.030154807 +0000
Change: 2019-03-27 02:44:45.030154807 +0000
 Birth: -

In [3]: df = pd.read_hdf('/tmp/foo.h5')

In [4]: !stat /tmp/foo.h5
  File: ‘/tmp/foo.h5’
  Size: 60440     	Blocks: 120        IO Block: 4096   regular file
...
Access: 2019-03-27 02:45:25.419324127 +0000
Modify: 2019-03-27 02:45:25.436323775 +0000
Change: 2019-03-27 02:45:25.436323775 +0000
 Birth: -

In [5]: exit
```

This issue does not appear when using `pd.read_hdf(..., mode='r')`, but it can be quite confusing in many cases.

Is it intended?

**Comment by NewbiZ** [comment]
Agree that this is an annoying issue. Opening a file (even for writing) should not actually touch it if no writing takes place in the end.

**Comment by gavincyi** [comment]
The same issue experienced here when no byte written on the file changes the modification time.

With mode 'a', the mtime is changed even no change is made.

```
In [22]: !stat array1.h5                                                 
  File: ‘array1.h5’
  Size: 2054            Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d    Inode: 403698      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2004/   gchan)   Gid: ( 2000/      it)
Context: unconfined_u:object_r:user_tmp_t:s0
Access: 2019-03-27 03:11:08.408907778 +0000
Modify: 2019-03-27 03:12:48.004661336 +0000
Change: 2019-03-27 03:12:48.004661336 +0000
 Birth: -

In [23]: tables.open_file("array1.h5", mode="a").close()                 

In [24]: !stat array1.h5                                                 
  File: ‘array1.h5’
  Size: 2054            Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d    Inode: 403698      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2004/   gchan)   Gid: ( 2000/      it)
Context: unconfined_u:object_r:user_tmp_t:s0
Access: 2019-03-27 03:11:08.408907778 +0000
Modify: 2019-03-27 03:16:45.854508309 +0000
Change: 2019-03-27 03:16:45.854508309 +0000
 Birth: -
```

**Comment by FrancescAlted** [comment]
As far as I know, no changes in PyTables 3.5.x should affect the file modification time.  It occurs to me that this could be a change in the latest versions of HDF5.  PyTables wheels are using latest HDF5 1.10.4, so you may want to try linking against HDF5 1.8.x (or install PyTables wheels < 3.5.1) and see if this issue is gone.

**Comment by tomkooij** [comment]
This is probably due to HDF5 1.10 locking files when reading. To be able to implement SWMR (single writer multiple readers) the HDF5 library must lock file even when reading in non-SWMR mode, to prevent a SWMR writer from opening a file for writing when a non-SWMR is reading.
