### ISSUE TITLE
PyTables does not return the first row when using itersorted with a negative step

### ISSUE THREAD

**Issue by laurenceanthony** [PyTables/PyTables#740]
'm using the itersorted method in PyTables. All rows are returned correctly when the step is set to a positive value, but the first row is not returned when using a negative step value. I asked about this on StackOverflow and one reply suggests it could be a bug.

Below is test code that illustrates the problem:

	import tables

        class DBEntry(tables.IsDescription):
		id = tables.Int16Col()

	class Test(object):

		def __init__(self, parent = None):
			pass

		def create_db_entries(self):
			db = tables.open_file("py_db_test.h5", mode = "w", title = "db")
			table = db.create_table('/', 'test', DBEntry, "test")
			entry = table.row
			for i in range(0, 5):
				entry['id'] = i
				entry.append()

			table.flush()
			table.cols.id.create_csindex()
			db.close()

		def get_db_entries(self):
			db = tables.open_file("py_db_test.h5", mode = "r")
			entries = db.root.test
			print('ascending (all rows showing)')
			for row in entries.itersorted('id', start = None, stop = None, step = 1):
				print(row['id'])
			print('decending (missing first row)')
			for row in entries.itersorted('id', start = None, stop = None, step = -1):
				print(row['id'])
			db.close()

	if __name__ == '__main__':
		test = Test()
		test.create_db_entries()
		test.get_db_entries()`

**Comment by tadashigaki** [comment]
I think this issue is caused by below sections.

https://github.com/PyTables/PyTables/blob/0ad9f90060f6a0a30bc9cab0a6a9f4993046daa7/tables/tableextension.pyx#L883

https://github.com/PyTables/PyTables/blob/0ad9f90060f6a0a30bc9cab0a6a9f4993046daa7/tables/tableextension.pyx#L996
