### ISSUE TITLE
Creating a CArray fails when only required parameters supplied

### ISSUE THREAD

**Issue by cristi-neagu** [PyTables/PyTables#741]
Hello,

The following code fails:

```
import numpy
import tables
fileName = 'carray1.h5'
shape = (200, 300)
atom = tables.UInt8Atom()
filters = tables.Filters(complevel=5, complib='zlib')
h5f = tables.open_file(fileName, 'w')
ca = h5f.create_carray(h5f.root, 'carray')
h5f.close() 
```

It is the example given for creating a CArray, with only the required parameters supplied to `create_carray`. It fails with the following error:

```
HDF5ExtError: HDF5 error back trace

  File "C:\ci\hdf5_1545244154871\work\src\H5D.c", line 292, in H5Dopen2
    unable to open dataset
  File "C:\ci\hdf5_1545244154871\work\src\H5Dint.c", line 1205, in H5D__open_name
    not found
  File "C:\ci\hdf5_1545244154871\work\src\H5Gloc.c", line 422, in H5G_loc_find
    can't find object
  File "C:\ci\hdf5_1545244154871\work\src\H5Gtraverse.c", line 851, in H5G_traverse
    internal path traversal failed
  File "C:\ci\hdf5_1545244154871\work\src\H5Gtraverse.c", line 627, in H5G__traverse_real
    traversal operator failed
  File "C:\ci\hdf5_1545244154871\work\src\H5Gloc.c", line 378, in H5G__loc_find_cb
    object 'carray' doesn't exist

End of HDF5 error back trace

Non-existing node ``carray`` under ``/``
```

Since the class declaration looks like this:
`class tables.CArray(parentnode, name, atom=None, shape=None, title='', filters=None, chunkshape=None, byteorder=None, _log=True, track_times=True)`
I would expect that passing only `parentnode` and `name` would not throw an error. It seems that in this case, `create_carray` needs at least `atom` and `shape`. If that is the case, shouldn't those two parameters not have default values? Or, if they do have default values, perhaps the error message should be more suggestive.

**Comment by scopatz** [comment]
Thanks for opening this @cristi-neagu
