### ISSUE TITLE
Missing documentation for creating columns containing arrays

### ISSUE THREAD

**Issue by dreamflasher** [PyTables/PyTables#756]
The documentation here https://www.pytables.org/usersguide/datatypes.html mentions "while the data type of array elements can be set through the use of the Atom class and its descendants". Unfortunately, in the linked documentation there is no mentioning of how to create a column containing arrays.

How do I create a column that can have as a value `np.ndarray([1.0, 0.5])`?

**Comment by dreamflasher** [comment]
I searched for a solution for 4 hours, a bunch of stackoverflows also looking for an answer – it looks like that's what the shape attribute in the column is for. Apparently no Atomic types are needed, but the Column types are sufficient. I'd recommend documenting this and providing an example.

**Comment by tomkooij** [comment]
@dreamflasher: Thanks for pointing this out. As you have noticed, proper documentation can mean a lot to users. Would you be willing and able to provide a PR for the documentation? 

If you can provide a short example, that would be helpful as well. I

**Comment by tomkooij** [comment]
Closed due to inactivity.
