### ISSUE TITLE
ImportError on Python 3.8b4 windows

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#760]
When building pytables on Windows (64bit/MSVC 2019) on Python 3.8beta4 I get an ImportError:

```
 File "d:\py38\venv\lib\site-packages\tables\__init__.py", line 27, in <module>
    from .utilsextension import (
ImportError: DLL load failed while importing utilsextension
```

The wheel provided by @cgohlke works fine... I have diffed master against the wheel, but only some changes in `__init__.py` which are needed anyway for python3.8b4/windows.

I've tried `python setup.py install` and building a wheel and installing the wheel. The utilsextension-*.pyd module is present in the wheel and in `lib\site-packages` after the install.

Ping @cgohlke: Do you have an idea what causes the ImportError? Any extra changes you made to allow the wheel to work?

**Comment by cgohlke** [comment]
Are all the required DLLs (e.g. hdf5.dll, zlib.dll) located next to the `utilsextension-*.pyd` file? Python 3.8 no longer searches the directories specified in the `PATH` environment variable for DLLs.

**Comment by tomkooij** [comment]
@cgohlke: Thanks for pointing that out, that must be the culprit, but...

For both your wheel and the wheel I generated with `python setup.py bdist_wheel` the *.pyd and *.dll files are located in `Lib\site-packages\tables`. Both wheels look exactly the same, but obviously something is different in configuration because my wheel fails on `import tables` with the above `ImportError`

**Comment by tomkooij** [comment]
So, I tinkered some more: It is due to `hdf5.dll` cannot be imported.

When I overwrite the installed `hdf5.dll` by the version from the cgohle wheel, the `ImportError` is gone. (Pytables tests then fails with HDF5 library mismatch, but that's obvious).

So the problem is the link(er) between `hdf5.dll` and the *.pyd. I just upgraded to MSVC 2019, so I hope that is not the issue...

**Comment by tomkooij** [comment]
So I messed up mixing VS2017 and VS2019... (doh!).

After compiling the HDF5 library from source using VS2019 it works fine. 

There's still the issue cgohlke pointed out: Python 3.8 changes the way DLL are loaded. As (not) loading DLLs is probably the number 1 PyTables issue reported by users (at least before we were providing wheels) this is something we need to deal with. I'll created a new issue for that.
