### ISSUE TITLE
Point selection modifies key array

### ISSUE THREAD

**Issue by ghcollin** [PyTables/PyTables#763]
When passing a numpy array as an index, point selection will attempt to modify the given array to correct for negative indices.

Consider the following example:
```python
import os, tempfile, tables, shutil
import numpy as np

test_dir = tempfile.mkdtemp()
test_filename = os.path.join(test_dir, 'test.h5')
test_file = tables.open_file(test_filename, 'w')

test_array = np.ones(100)
test_array_path = '/test_byte_array'
hdf5_array = test_file.create_array(test_file.root, test_array_path[1:], test_array)

coord_list = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
print("Coordinate list:\t\t{}".format(coord_list))
hdf5_array[coord_list]
print("Coordinate list after indexing:\t{}".format(coord_list))

coord_ary = np.array([-5,-4,-3,-2,-1,0,1,2,3,4,5])
print("Coordinate ndarray:\t\t\t{}".format(coord_ary))
hdf5_array[coord_ary]
print("Coordinate ndarray after indexing:\t{}".format(coord_ary))

# Uncomment the following to induce an exception.
#coord_ary_readonly = np.array([3,4])
#coord_ary_readonly.setflags(write=False)
#hdf5_array[coord_ary_readonly]

test_file.close()
shutil.rmtree(test_dir)
```

The output of this example is:
```
Coordinate list:                [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
Coordinate list after indexing: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
Coordinate ndarray:                     [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Coordinate ndarray after indexing:      [95 96 97 98 99  0  1  2  3  4  5]
```

If the third indexing operation is uncommented, the following exception is thrown:
```
Traceback (most recent call last):
  File "array_coords.py", line 25, in <module>
    hdf5_array[coord_ary_readonly]
  File "/usr/local/lib/python3.7/site-packages/tables/array.py", line 666, in __getitem__
    coords = self._point_selection(key)
  File "/usr/local/lib/python3.7/site-packages/tables/leaf.py", line 581, in _point_selection
    coords[idx] = (coords + self.shape)[idx]
ValueError: assignment destination is read-only
```

There are a few issues that I see here
- Pytables modifying the key was unexpected behaviour to me.
- The behaviour is inconsistent between using a list and an ndarray.
- If an ndarray key with negative values is used as an index, then reused for a smaller array, an out of bounds exception will be thrown even though the original key was a valid index for the smaller array.
- A read-only ndarray cannot be used as a key for point selection, even if there are no negative indices present.

Perhaps it would be best for pytables to create a copy of the ndarray key if negative indices are present.

**Comment by tomkooij** [comment]
@ghcollin Thanks for reporting. I agree with your analysis and using a copy of the indexing array should work (although there is a big memory penalty for large indexarrays)

I'll at least document this behaviour for the next release, I'm not sure I can find the time to fix this. 

Are you able and willing to provide a fix / PR? Do you need help with a PR if you have a fix? Thanks!
