### ISSUE TITLE
Bad pattern matching in setup.py

### ISSUE THREAD

**Issue by gma-uw** [PyTables/PyTables#764]
In setup.py, I find the lines:
                if 'H5_VERS_MAJOR' in line:
                    major_version = int(re.split("\s*", line)[2])

the header file it is processing has this #define:
line = "#define H5_VERS_MAJOR	1	/* For major interface/format changes  	     */"
the split re.split("\s*", line) returns:
['', '#', 'd', 'e', 'f', 'i', 'n', 'e', '', 'H', '5', '_', 'V', 'E', 'R', 'S', '_', 'M', 'A', 'J', 'O', 'R', '', '1', '', '/', '*', '', 'F', 'o', 'r', '', 'm', 'a', 'j', 'o', 'r', '', 'i', 'n', 't', 'e', 'r', 'f', 'a', 'c', 'e', '/', 'f', 'o', 'r', 'm', 'a', 't', '', 'c', 'h', 'a', 'n', 'g', 'e', 's', '', '*', '/', '', '']

The correct split expression should be:
re.split("\s+", line), which returns:
['#define', 'H5_VERS_MAJOR', '1', '/*', 'For', 'major', 'interface/format', 'changes', '*/', '']

**Comment by avalentino** [comment]
@gma-uw that line seems to be no longer in the `setup.py`.
Which version of PyTables are you using?
Can you update to a newer version?
