### ISSUE TITLE
Link to custom build of libhdf5

### ISSUE THREAD

**Issue by ZanSara** [PyTables/PyTables#777]
Hello, 

I am trying to use PyTables over a custom build of `libhdf5.so`, which I placed under `/usr/local/hdf5`.

I can build PyTables successfully with `python setup.py install --hdf5=/usr/local/hdf5`, but later on if I try to import it I get this error:
```
$ python
Python 3.6.3 (default, May 31 2019, 13:05:43) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/szan/Projects/hdf5_compile_trials/venv/lib/python3.6/site-packages/tables-3.6.0-py3.6-linux-x86_64.egg/tables/__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory
```
I can fix this error by doing `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/hdf5/lib`, but this is annoying as I have to remember to export the variable every time I want to use PyTables. I woudn't like to pollute my LD_LIBRARY_PATH either by appending the path in my ~/.bashrc. 

Is there a way to tell PyTables, at install time, where to find the library?

**Comment by tomkooij** [comment]
@zansara: I don't think there is a way to "hard code" the library location at install time at this time.

This should be possible using a trick in setup.py... PRs are welcome. :-)

**Comment by ZanSara** [comment]
Ok I will work on this one. Thank you for the pointer!
