### ISSUE TITLE
Does PyTables support hash indexes?

### ISSUE THREAD

**Issue by concretevitamin** [PyTables/PyTables#780]
I'm interested in hash indexes where the target workload is just point(s) lookup: `attr = val`.

At first glance http://www.pytables.org/usersguide/libref/structured_storage.html#tables.Column.create_index seems to be targetting range queries.  What implementation is the current index based on?

**Comment by FrancescAlted** [comment]
You can see the full details on how indexes are implemented in PyTables in this paper: https://www.pytables.org/docs/OPSI-indexes.pdf

**Comment by concretevitamin** [comment]
Thanks.  I only skimmed the PSI part.  It seems to me binary searches are involved on a lookup so not really an O(1) hash index.

I'll close this issue - however, I'd love to see support for this in some future version!
