### ISSUE TITLE
MAX_NUMEXPR_THREADS should honor NUMEXPR_MAX_THREADS environment variable

### ISSUE THREAD

**Issue by adam-azarchs** [PyTables/PyTables#786]
`tables.parameters.MAX_NUMEXPR_THREADS` currently uses a [hard-coded default of 4](https://github.com/PyTables/PyTables/blob/a575bc3/tables/parameters.py#L216). The [numexpr documentation](https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#threadpool-configuration) states that the thread count can be configured with the environment variables `NUMEXPR_MAX_THREADS` and `NUMEXPR_NUM_THREADS`.  Overriding those values with a hard-coded value is surprising to users who expect those environment variables to be honored.

**Comment by tomkooij** [comment]
ping @FrancescAlted

**Comment by FrancescAlted** [comment]
Yes, I think it makes sense to set the `tables.parameters.MAX_NUMEXPR_THREADS` to default to `NUMEXPR_NUM_THREADS` env variable, if set; if not set, then one should do nothing and let numexpr to figure out how many threads should be spawn by default.

Also, please note that `tables.parameters.MAX_NUMEXPR_THREADS`  is actually equivalent to `NUMEXPR_NUM_THREADS` (not `NUMEXPR_MAX_THREADS`)
