### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by shiyi-pan** [PyTables/PyTables#796]
I installed a software named  HiCExplorer ,and pytables >= 3.5 was needed ,but I only found 3.2.0, Is there is an >= 3.5 version  or not ? can you give me an download URL?

**Comment by FrancescAlted** [comment]
Latest PyTables version is 3.6.1.  You can have a look at all the releases here: https://github.com/PyTables/PyTables/releases.

**Comment by shiyi-pan** [comment]
Thank you a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Francesc Alted"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月8日(星期天) 凌晨3:25
收件人:&nbsp;"PyTables/PyTables"<PyTables@noreply.github.com&gt;;
抄送:&nbsp;"梦"<1343213784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PyTables/PyTables] version problem (#796)




Closed #796.

**Comment by shiyi-pan** [comment]
Thank for your help. I found it.&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Francesc Alted"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月8日(星期天) 凌晨3:25
收件人:&nbsp;"PyTables/PyTables"<PyTables@noreply.github.com&gt;;
抄送:&nbsp;"梦"<1343213784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PyTables/PyTables] version problem (#796)




Latest PyTables version is 3.6.1.  You can have a look at all the releases here: https://github.com/PyTables/PyTables/releases.
