### ISSUE TITLE
PyTables user guide Object Tree example fig is broken

### ISSUE THREAD

**Issue by melissawm** [PyTables/PyTables#798]
In Firefox on Linux, if you go to [the User Guide](https://www.pytables.org/usersguide/introduction.html), Figure 2 captioned "Figure 2: A PyTables object tree example." is broken, see attached screenshot:

[Screenshot](https://imgur.com/a/IOT87yJ)

**Comment by avalentino** [comment]
Thanks @melissawm, it should be fixed now
