### ISSUE TITLE
Read file after module renamed

### ISSUE THREAD

**Issue by jamesmyatt** [PyTables/PyTables#800]
I have an HDF5 file created with PyTables. However, when I load it I get the following error:

```
  File "<blah.py>", line X, in run
    df = pd.read_hdf(filename,key = 'dfOpt')
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 428, in read_hdf
    auto_close=auto_close,
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 814, in select
    return it.get_result()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 1829, in get_result
    results = self.func(self.start, self.stop, where)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 798, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 3070, in read
    values = self.read_array(f"block{i}_values", start=_start, stop=_stop)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/pytables.py", line 2725, in read_array
    ret = node[0][start:stop]
  File "/usr/local/lib/python3.6/site-packages/tables/vlarray.py", line 677, in __getitem__
    return self.read(start, stop, step)[0]
  File "/usr/local/lib/python3.6/site-packages/tables/vlarray.py", line 821, in read
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/lib/python3.6/site-packages/tables/vlarray.py", line 821, in <listcomp>
    outlistarr = [atom.fromarray(arr) for arr in listarr]
  File "/usr/local/lib/python3.6/site-packages/tables/atom.py", line 1224, in fromarray
    return pickle.loads(array.tostring())
ModuleNotFoundError: No module named 'YYY'
```

This is caused by having moved/renamed the YYY module. **What's the easiest way to fix this?** Is there a tool to re-write the HDF5 file with the updated module names?

This is what you might do for a simple pickle file: https://stackoverflow.com/questions/40914066/unpickling-objects-after-renaming-a-module

**Comment by avalentino** [comment]
If I understand correctly you are storing objects withe references to Python module in an HDF5 file.
Honestly I think that this use case is not supported.
In general storing python object in an HDF5 file should be used with caution.

I'm closing this issue because I don't think that there is anything that can be done in PyTables.
If I understand correctly it is your one is an issue that you can encounter every time you use pickle.

If you think that there is something specific that could be done in PyTables to to make it easier to workaround the issue please feel free to open a PR.

**Comment by jamesmyatt** [comment]
@avalentino Thanks for looking at this.

Most people are well aware that pickle is not suited for long term storage. It is one of the main reasons why users will choose to store the data frame as HDF5 using PyTables rather than pickle in the first place. The issue is that PyTables chooses silently to use pickle underneath to store any custom objects inside a dataframe. Hence, the apparent guarantee that PyTables provides for loading the data frame is broken in this scenario.

The issue for PyTables is that there's no way for the user to customise the handling of custom classes. (as far as I can tell) All classes that do not have built-in support in PyTables are *always* handled via the default pickle module using the default options (https://github.com/PyTables/PyTables/blob/b2d5a930cea0460656e596cde0962b70be87f1e4/tables/atom.py#L1146). (I might be wrong, I haven't looked very closely).

The main consequence for PyTables is that the *entire* data frame is currently irretrievable if any element was stored with pickle and was affected by a code change that prevents unpickling using the default module with the default settings. So perhaps the simplest stop-gap would be to have an option to have an option here to replace unpickle exceptions with None or pd.NA so that the data frame can at least be partially retrieved.

A better long-term option would be the ability to inject a custom unpickler, such at the one in https://stackoverflow.com/questions/40914066/unpickling-objects-after-renaming-a-module. An even better option would be to be able to customize the ObjectAtom handling entirely. I think that this is as simple as being able to provide a custom dumps method and a custom loads method.

What do you think?

**Comment by jamesmyatt** [comment]
A stop-gap option would also be to disable unpickling too, as in https://github.com/PyTables/PyTables/issues/813

**Comment by avalentino** [comment]
Yes I would be open to a PR for #813 or a new feature to control the behavior of PyTables with unknown objects.
