### ISSUE TITLE
DeprecationWarning tostring() and fasts tests

### ISSUE THREAD

**Issue by TheHaricover** [PyTables/PyTables#814]
I installed PyTables on Arch and set up following the installation part of Readme in GitHub. Everything went smooth.

But when I launched the tests, with `$ python3 -m tables.tests.test_all` the script told me that it would take 4 hours, it only took 5 minutes and there are a lot of lines with the `DeprecationWarning: tostring() is deprecated. Use tobytes() instead.`

At the end, the test wrote:
```
Ran 6355 tests in 261.401s

OK (skipped=14)
```

I think I shouldn't be worried but I'm raising this issue just to be sure that it's exactly the expected behavior (for you, and for me)

If you want more info, feel free to ask.

And as always, thank you for your work !

**Comment by avalentino** [comment]
@TheHaricover thanks for he report.
Luckily it ha been already fixed in master (see #810).
The fix will me in the next release.
