### ISSUE TITLE
Add dtype=object to key = numpy.array(key)

### ISSUE THREAD

**Issue by Alon-Retispec** [PyTables/PyTables#819]
In https://github.com/PyTables/PyTables/blob/master/tables/leaf.py#L542
need to change  `key = numpy.array(key)` to `numpy.array(key, dtype=object)` due to numpy deprecation warning: 

> VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

**Comment by avalentino** [comment]
Thanks @Alon-Retispec , good catch.

I also have had that warning on my radar for a while but never had the time to investigate.
The point is that IMHO flat lists/tuples shall be converted into numpy arrays wit the proper type.
key.dtype is handled few lines after point in the code where the warning is raised.
Using ``object`` would always result in a type error: https://github.com/PyTables/PyTables/blob/6f4a99c9489ed8bedbb680edfbf54494241b08d0/tables/leaf.py#L581

Probably the best solution in that case would be to use the warnings.catch_warnings context manager [1] to explicitly handle the specific case.
Also I'm not sure if we should do it in the ``_point_selection`` method or in the test code.

Do you mind to prepare a PR for this?

[1] https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings
