### ISSUE TITLE
Pypi wheel tables 3.6.1 for Python 3.9 has been compiled with AVX2 instructions triggering SIGILL 

### ISSUE THREAD

**Issue by sgkdev** [PyTables/PyTables#841]
I don't know if it has been done by purpose or not but latest Pypi wheel package **_tables-3.6.1-cp39-cp39-manylinux2010_x86_64.whl_** has been compiled without DISABLE_AVX2.
This cause Python to crash with SIGILL on every system with older CPU not supporting AVX2.

```
Program terminated with signal SIGILL, Illegal instruction.
#0  0x7fe6ca7b4729 in ?? ()
(gdb) x/10i $rip
=> 0x7fe6ca7b4729 <__pyx_pymod_exec_tableextension+2096>:	vinserti128 $0x1,%xmm1,%ymm0,%ymm0
   0x7fe6ca7b472f <__pyx_pymod_exec_tableextension+2102>:	mov    %rax,0x358e72(%rip)        # 0x7fe6cab0d5a8 <__pyx_vtable_6tables_14tableextension_Row+40>
```
AVX2 instructions are present on the Python 3.9 PyPi tables package 3.6.1:
```
root@0e05c09f35a6:/# objdump -d /usr/local/lib/python3.9/site-packages/tables/tableextension.cpython-39-x86_64-linux-gnu.so | grep vinsert | wc -l
523
```
but not on older Python versions (like 3.8) - still tables 3.6.1:
```
root@ba00b39c17c1:/# objdump -d /usr/local/lib/python3.8/site-packages/tables/tableextension.cpython-38-x86_64-linux-gnu.so | grep vinsert | wc -l
0
```

**Comment by avalentino** [comment]
Hi @sgkdev thank toy for reporting.
No it has not been done on purpose, I forgot to switch AVX off.
Unfortunately I cannot replace the wheel in pypi, sorry.

**Comment by zolfariot** [comment]
Confirmed! I am affected on CPU `Intel(R) Xeon(R) CPU E5-2620 v2`.

Working perfectly (tests passed) with:
```
sudo apt install libhdf5-dev
HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/ pip install --no-binary :all: tables
```

**Comment by avalentino** [comment]
This is now fixed (see d2a048b and a609a36)

**Comment by kartlee** [comment]
We have been building pytable from source with custom hdf5. Recently the 3.6.1 libraries built in intel mac fail in M1 chipset. And we had to explicitly pass DISABLE_AVX2=1 while building the package. Can you confirm if this is not done default for 3.6.1? And will be a default setting > 3.6.1 ?

-Karthik

**Comment by avalentino** [comment]
Disabling AVX2 on M1 is correct.
Could you please open a dedicated ticket for this?

**Comment by kartlee** [comment]
Sure thanks. We are also noticing the crash in " Intel(R) Xeon(R) CPU E5345 ". I will open a separate ticket as you mentioned.

**Comment by kartlee** [comment]
I just filed https://github.com/PyTables/PyTables/issues/956
