### ISSUE TITLE
PerformanceWarning on string index

### ISSUE THREAD

**Issue by zequihg50** [PyTables/PyTables#879]
Dear PyTables developers,

I'm creating a table with three columns of type string with length of 750 and 3853792 rows. When I try to read different values, it seems that for the first values PyTables is incredibly fast to locate them (without the index it takes a couple of days to find all different values) but after finding some of them (like 2000 of 7000 different values) it stucks.

This is how I try to find all rows matching specific value:

```
for value in all_different_values_of_col1:
    current = files.read_where('''_variable_dataset == {}'''.format(value), field='col2')
    # do something with current values
```

This is the table created by pytables:

```
/files (Table(3853792,), shuffle, zlib(1)) 'files'
  description := {
  "col1": StringCol(itemsize=750, shape=(), dflt=b'', pos=0),
  "col2": StringCol(itemsize=750, shape=(), dflt=b'', pos=1),
  "col3": StringCol(itemsize=750, shape=(), dflt=b'', pos=2)}
  byteorder := 'irrelevant'
  chunkshape := (233,)
```

I want to extract all the rows where `col1` match a specific value and repeat this operation with several different values, using `Table.read_where()`. To speed up the search, I tried to create an index on `col1`, using `create_index()`. This operation creates the following HDF5 objects:

```
<HDF5 dataset "abounds": shape (1728,), type "|S750">
<HDF5 dataset "bounds": shape (9, 191), type "|S750">
<HDF5 dataset "indices": shape (9, 393216), type "<u4">
<HDF5 dataset "indicesLR": shape (393216,), type "<u4">
<HDF5 dataset "mbounds": shape (1728,), type "|S750">
<HDF5 dataset "mranges": shape (9,), type "|S750">
<HDF5 dataset "ranges": shape (9, 2), type "|S750">
<HDF5 dataset "sorted": shape (9, 393216), type "|S750">
<HDF5 dataset "sortedLR": shape (393409,), type "|S750">
<HDF5 dataset "zbounds": shape (1728,), type "|S750">
```

While creating the index the following warnings appear:

```
.../tables/leaf.py:402: PerformanceWarning: The Leaf ``/_i_files/col1/sorted`` is exceeding the maximum recommended rowsize (104857600 bytes);
be ready to see PyTables asking for *lots* of memory and possibly slow
I/O.  You may want to reduce the rowsize by trimming the value of
dimensions that are orthogonal (and preferably close) to the *main*
dimension of this leave.  Alternatively, in case you have specified a
very small/large chunksize, you may want to increase/decrease it.
  warnings.warn("""\

/.../tables/leaf.py:402: PerformanceWarning: The Leaf ``/sorted`` is exceeding the maximum recommended rowsize (104857600 bytes);
be ready to see PyTables asking for *lots* of memory and possibly slow
I/O.  You may want to reduce the rowsize by trimming the value of
dimensions that are orthogonal (and preferably close) to the *main*
dimension of this leave.  Alternatively, in case you have specified a
very small/large chunksize, you may want to increase/decrease it.
  warnings.warn("""\

.../tables/leaf.py:402: PerformanceWarning: The Leaf ``/sorted2`` is exceeding the maximum recommended rowsize (104857600 bytes);
be ready to see PyTables asking for *lots* of memory and possibly slow
I/O.  You may want to reduce the rowsize by trimming the value of
dimensions that are orthogonal (and preferably close) to the *main*
dimension of this leave.  Alternatively, in case you have specified a
very small/large chunksize, you may want to increase/decrease it.
  warnings.warn("""\
```

The warning seems to be caused by the object `/_i_files/col1/sorted` with shape `<HDF5 dataset "sorted": shape (9, 393216), type "|S750">`.

Is there any parameter that allows to adjust the shape of the object `/_i_files/col1/sorted` in order to get rid of the warning?

```
hdf5                      1.10.4
python                    3.8.5
pytables                  3.6.1
```

Best regards.

**Comment by zequihg50** [comment]
For anyone interested, chunk, slice, block and superblock sizes are computed [here](https://github.com/PyTables/PyTables/blob/beafbd34d31b6326aa7f4642614585396d3c6331/tables/idxutils.py#L106). If the slice size is too big the warnings appear. You can use the `dtype` itemsize to control the maximum size of the slice:

```python
if (slicesize * itemsize) > 104857599:
    slicesize = int(104857599 / itemsize)
```

**Comment by avalentino** [comment]
Dear @zequihg50, sorry for not providing feedback on this issue and thanks for sharing outcomes of your analysis.
Do you think that the solution that you suggest is general enough to be included in the PyTables codebase?
Are you willing to submit a PR for this?

**Comment by zequihg50** [comment]
I have discovered it is not general enough, I'll perform further testing and if I find a general solution I'll make the PR.
