### ISSUE TITLE
tables.table.Column has no attribute tolist,

### ISSUE THREAD

**Issue by baileyji** [PyTables/PyTables#896]
Updated to 3.6.1 and and getting a failure on l 366 of tables.conditions:

>   File "/home/baileyji/.conda/envs/pipeline/lib/python3.7/site-packages/tables/table.py", line 1609, in get_where_list
>     self._where(condition, condvars, start, stop, step)]
>   File "/home/baileyji/.conda/envs/pipeline/lib/python3.7/site-packages/tables/table.py", line 1504, in _where
>     compiled = self._compile_condition(condition, condvars)
>   File "/home/baileyji/.conda/envs/pipeline/lib/python3.7/site-packages/tables/table.py", line 1334, in _compile_condition
>     return compiled.with_replaced_vars(condvars)  # bingo!
>   File "/home/baileyji/.conda/envs/pipeline/lib/python3.7/site-packages/tables/conditions.py", line 366, in with_replaced_vars
>     idxlim = idxlim.tolist()  # convert back to Python
> AttributeError: 'Column' object has no attribute 'tolist'

I'll note that list(idxlim) does indeed work.

**Comment by baileyji** [comment]
After some further debugging this appears to be tied to numexpr evaluations.
```
table.read_where('resID==10015')
```
and
```
resid=10015
table.read_where('resID==resid')
```
work. 

```
resID=10015
table.read_where('resID==resID')
```

does not.

**Comment by avalentino** [comment]
It seems that all works as expected now (including the failure in the third case).
Closing.
