### ISSUE TITLE
Broken links in FAQ

### ISSUE THREAD

**Issue by DFEvans** [PyTables/PyTables#897]
In the FAQ, there are several broken links pointing to pages under "www.pytables.org/moin/" - "FrancescAlted", "ComputingKernel", and "PyTablesPro". From a bit of hunting, it seems that PyTablesPro ceased to exist ~10 years ago, so these links sound like they're very out of date!

At time of writing, it's links 10, 17, and 18 in the list at the bottom of the FAQ: https://www.pytables.org/FAQ.html#id63

**Comment by avalentino** [comment]
@DFEvans thanks for reporting

**Comment by logankilpatrick** [comment]
@avalentino this would be a great candidate "good first issue". Can you clarify if the state of the docs? Some of it looks out of date with link's 404ing. For example, the link at the top of https://github.com/PyTables/PyTables/blob/master/doc/source/FAQ.rst which points to http://www.pytables.org/moin/FAQ 404's. Is that expected?

**Comment by avalentino** [comment]
Fixed in 4bdef2fda.
