### ISSUE TITLE
Higher resolution / vector version of the logo

### ISSUE THREAD

**Issue by maxnoe** [PyTables/PyTables#899]
I'd like to attribute our usage of pytables by including your logo on a poster, however I could only find a very small png (from the documentation page).

Is the logo available as a higher resolution bitmap or ideally in a vector graphics format (eps, pdf, svg)?

**Comment by avalentino** [comment]
@maxnoe sorry for the late reply.
The SVG version of the logo can be found here: https://github.com/PyTables/PyTables/tree/master/doc/source/images
