### ISSUE TITLE
No wheels available for tables 3.6.1 on Python 3.8, platform manylinux1_x86_64

### ISSUE THREAD

**Issue by jgredecka** [PyTables/PyTables#911]
Hi PyTables team,

I'm attempting to download the latest tables version 3.6.1 with Python 3.8.12 on manylinux1_x86_64 using the following command:
```
pip download tables==3.6.1 \
  --no-deps \
  --platform manylinux1_x86_64 \
  --python-version 3.8.12 \
  --implementation cp \
  --abi cp36m \
  --no-cache-dir
```

However this results in the following error:
```
  1 error generated.
  * Using Python 3.8.12 (default, Oct 28 2021, 16:26:38)
  * USE_PKGCONFIG: True
  .. ERROR:: Could not find a local HDF5 installation.
     You may need to explicitly state where your local HDF5 headers and
     library can be found by setting the ``HDF5_DIR`` environment
     variable or by using the ``--hdf5`` command-line option.
```
It looks like while running the `pip download` command no wheels that come with HDF5 are found so instead it downloads from source? E.g.:

```
Collecting tables==3.6.1
  Downloading tables-3.6.1.tar.gz (4.6 MB)
     |████████████████████████████████| 4.6 MB 683 kB/s            
  Preparing metadata (setup.py) ... error
```

When I run the same `pip download` command with Python version 3.6.12 it works fine, i.e. it successfully downloads `tables-3.6.1-cp36-cp36m-manylinux1_x86_64.whl` and I get no errors.

**Comment by avalentino** [comment]
Hi @jgredecka, probably you should use ``--abi=cp38``

**Comment by jgredecka** [comment]
Thank you very much @avalentino for taking a look at this, that was the problem in the end 🙈
