### ISSUE TITLE
Release to support HDF5 1.12.1

### ISSUE THREAD

**Issue by aufdenkampe** [PyTables/PyTables#912]
@avalentino, @tomkooij, @FrancescAlted, it appears that there is a growing need in the PyTables user community for a new release. Here are a few relevant issues:
- #826 
- #823 
- #876
- #887 
- #891 
- #909
- #776 

With the fabulous integration of PyTables with Pandas and Dask, an enormous number of projects depend on PyTables. The lack of a recent release that supports recent versions of Python and HDF5 and ARM64 processors is increasingly blocking the progress of these projects. My sense is that many of these projects will be looking for alternatives to PyTables if a new release does not happen soon.

This is the case for the federally-supported watershed modeling system, [HSPsquared](https://github.com/respec/HSPsquared), which will be used to forecast impacts of climate change, among other things, and therefore needs excellent performance. As I mentioned in https://github.com/PyTables/PyTables/issues/826#issuecomment-912572906, we presently use both Pytables and [h5py](https://github.com/h5py).

h5py has supported [HDF5 v1.12](https://www.hdfgroup.org/2020/03/release-of-hdf5-1-12-0-newsletter-172/) since their v3.0 release in October, 2020, and just released their v3.1 that supports HDF5 v1.12.1 and API updates to access the new HDF5 features. HDF5 v1.12 has substantial performance and other benefits over v1.10, in addition to other benefits such as better handling of datetime and strings. 

We have observed many issues when the two use different versions of HDF5, so we're currently limited by PyTables to HDF5 v1.10.6, even for functions that use h5py. See https://github.com/respec/HSPsquared/issues/36. 

HDF5 v1.12.1 has binaries for ARM-based Macs. ARM64 architecture is increasingly used by cloud providers, because of the substantial better energy to performance ratios (i.e. [AWS graviton](https://aws.amazon.com/pm/ec2-graviton/)). A release with ARM binaries would therefore be very useful, but this is less important than getting a release out as soon as possible that supports HDF5 v1.12.1 and updates other dependencies.

**Comment by aufdenkampe** [comment]
@avalentino, @xmatthias, @logankilpatrick, @FrancescAlted, and others.

Thank you for your responsiveness these requests from the community and your recent flurry of activity! I also appreciate your openness by sharing your [New PyTables release - call for discussion](https://groups.google.com/g/pytables-dev/c/rAcV5Bf8--g) thread.

I can appreciate the challenges of maintaining a public repo without funding, and thank you all for moving forward toward a new release.

**Comment by aufdenkampe** [comment]
@avalentino & @xmatthias, I saw in #930 that providing full support for upgrading to HDF5 v1.12.1 might be challenging for ARM64 architectures, at least for now, due in part to backward compatibility issues with Blosc v1.x.

My view is that full support of ARM64 might be secondary to upgrading to HDF5 v1.12.1 for x86 systems. I think the community might be OK with staging releases, with:
- a minor release very soon for HDF5 v1.12.1 (and all the other great stuff you are doing) for x86; and 
- a major release later this winter that includes full support for ARM64 and x86. 

I wonder what others think?

**Comment by xmatthias** [comment]
I don't disagree with this - and i see it in a similar way. 
blosc will be at a lower version for aarch64 / arm64 - but i think the fact that there are about 10 open issues all asking for wheels, support for newer versions, or wheels for newer python versions highlights the need for a new minor release.

That said - i don't see the "arm" topic as blocker either - however the huge x86 binaries could be - at least until we understand WHY this happens (it might be OK - but i might be bloated for some odd reason).

**Comment by jbrockmendel** [comment]
My experience in debugging #903 suggests a release with a wheel compiled against 1.12.1 may close that issue.
