### ISSUE TITLE
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

### ISSUE THREAD

**Issue by haoxiaodao** [PyTables/PyTables#950]
I have used the following method, but it doesn't work
1.conda install pytables
2.pip install tables
3.pip install --user tables
4.pip install tables==3.6.1
------------------My envs
Python = 3.9.7
pandas = 1.4.1

**Comment by avalentino** [comment]
Dear @haoxiaodao please provide more information about what the errors.
Also please provide more information about your environment: OS, architecture, version and location of all pre-requisite software (see http://www.pytables.org/usersguide/installation.html#prerequisites), etc.

**Comment by avalentino** [comment]
@haoxiaodao did you manage to solve the problem?

**Comment by hjysmi** [comment]
```
C:\ProgramData\Anaconda3\envs\env_38\python.exe F:/workspace/python/demo/demo_01.py 
Traceback (most recent call last):
  File "F:/workspace/python/demo/demo_01.py", line 1, in <module>
    import tables as tb
  File "C:\ProgramData\Anaconda3\envs\env_38\lib\site-packages\tables\__init__.py", line 45, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: DLL load failed while importing utilsextension: 找不到指定的模块
```
```
tables: 3.7.0
python: 3.8.13
os: win10
```
Hi @avalentino 
I have a same issue.

**Comment by avalentino** [comment]
@hjysmi it is still not clear to me haw pytables has been installed.
Please note that
* if you use the conda package than you should probably open an issue in https://github.com/conda-forge/pytables-feedstock
* if you install pytables using pip in a conda environment, please be informed that this specific configuration is not supported by pytables and it is known not to work

**Comment by avalentino** [comment]
Closing this issue due to lack of information.
