### ISSUE TITLE
ValueError: Compression not supported on Fixed format stores

### ISSUE THREAD

**Issue by alexlenail** [PyTables/PyTables#953]
I tried to 
```
    with pd.HDFStore(path, 'w') as out_hdf:
        for key, df in rvals:
            out_hdf.put(key, df, format='fixed', complib='zlib', complevel=6)
```
Is that error message generally accurate: you can't compress fixed format stores at all? Or can I use a different compression algorithm? If so, it may be worth changing the error message.

**Comment by avalentino** [comment]
Could you please include also the error message in your report?
Also, having a complete and working example would surely help.
What is `rvals`?

**Comment by avalentino** [comment]
Dear @alexlenail,
in my understanding the 'fixed' format does not use the PyTables Table structure.
I don't know exactly how data are managed in that case.

Probably you should ask this question to pandas developers.

**Comment by avalentino** [comment]
OK closing.
Please feel free to re-open if you thing that there is something broken on the PyTables side.
