### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [PyTables/PyTables#954]
Looking in https://github.com/PyTables/PyTables/compare/v3.7.0...master I see +80 commits added since last release with substantial number of fixes added.
Do you have any plans to make new release .. soon? 😋

**Comment by MarieHouillon** [comment]
I would also really appreciate it, since it seems that no wheel is available yet on PyPI for arm64 Macs.

**Comment by MarechJ** [comment]
+1 We also need M1 support

**Comment by EwoutH** [comment]
@xmatthias @FrancescAlted @avalentino @matham Hi! Would a new release (soon-ish) be possible? Having Python 3.11 wheels on PyPI and Apple Silicon support would be great!

**Comment by xmatthias** [comment]
i'd be fully supporting this. 

@FrancescAlted @avalentino is there anything we can do to help getting a release ready?

**Comment by FrancescAlted** [comment]
> i'd be fully supporting this.
> 
> @FrancescAlted @avalentino is there anything we can do to help getting a release ready?

Not a big deal, but it would nice if we can enable tests for the mac-arm64 wheels. I tried that in CI, but no success (still, these work well on my MacBook M1).

**Comment by avalentino** [comment]
PyTables v3.8.0 has been released.
