### ISSUE TITLE
Iterator (Table.iterrows) returns duplicated values when used in list comprehension or as type constructor

### ISSUE THREAD

**Issue by illagrenan** [PyTables/PyTables#955]
* Python version: `Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32`
* OS: `Windows 11 21H2`
* Processor: `Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz`
* `tables==3.7.0`

Iterating via `table.iterrows()` produces different results than via `list(table.iterrows())`.

The following code demonstrates this strange behavior. I understand that using `Row.fetch_all_fields()` will return all the data however I would not expect `list(table.iterrows())` to contain the last row duplicated.

```python
# -*- encoding: utf-8 -*-
# ! python3

import logging
from typing import Final

import numpy as np
import tables as tb
from tables import Group, Table

logger: Final = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)


class MyIsDescription(tb.IsDescription):
    my_id = tb.UInt32Col()
    vector = tb.Float32Col(shape=2048)


def main():
    with tb.open_file("example.h5", mode="w") as h5file:
        group: Group = h5file.create_group("/", "demo")
        table: Table = h5file.create_table(group, "mydata", MyIsDescription)

        table: Table = h5file.root.demo.mydata
        row = table.row

        for my_id in range(5):
            row["my_id"] = my_id
            row["vector"] = np.random.rand(2048).astype(np.float32)
            row.append()

            # 0, 1, 2, 3, 4
            print(my_id, end=", ")

    print("")

    with tb.open_file("example.h5", mode="r") as h5file:
        table: Table = h5file.root.demo.mydata

        # WRONG: [4, 4, 4, 4, 4]
        print([r["my_id"] for r in [r for r in table.iterrows()]])

        # WRONG: [4, 4, 4, 4, 4]
        print([r["my_id"] for r in list(table.iterrows())])

        # WRONG: [4, 4, 4, 4, 4]
        print([r["my_id"] for r in [*table.iterrows()]])

        # OK: [0, 1, 2, 3, 4]
        print([r["my_id"] for r in table.iterrows()])

        # OK: [0, 1, 2, 3, 4]
        print([r["my_id"] for r in [r.fetch_all_fields() for r in table.iterrows()]])


if __name__ == "__main__":
    main()
```

**Comment by avalentino** [comment]
Dear @illagrenan sorry for the late replay and thanks for reporting.
I can reproduce the issue. Thanks for clear example.

**Comment by avalentino** [comment]
OK, after some investigation it seems that the current behaviour is the expected one (although is seems counter-intuitive at a first look).
The point is that [`Tables.iterrows()` ](http://www.pytables.org/usersguide/libref/structured_storage.html?highlight=iterrows#tables.Table.iterrows) return updated versions of the same instance of a [`Row`](http://www.pytables.org/usersguide/libref/structured_storage.html?highlight=row#tables.tableextension.Row) object, which is basically a view on the table.
Once the iteration goes on the [`Row`](http://www.pytables.org/usersguide/libref/structured_storage.html?highlight=row#tables.tableextension.Row) object is update to point to a different row of the table and the references collected in previous iterations result to be updated as well.

```python
>>> lst = list(table)
>>> lst[0] is lst[1]
True
```

**Comment by avalentino** [comment]
OK, closing.
Please feel free to re-open if you think that there is still anything to discuss/fix.
