### ISSUE TITLE
Question: What is PyTables? :)

### ISSUE THREAD

**Issue by NeilduToit13** [PyTables/PyTables#958]
I'm really sorry to have to ask such a stupid question, but I've been through the documentation (introduction/FAQ, here and on website) twice now and PyTables really looks like it might be what I'm looking for but... I cannot figure out what it actually is. Some basic facts that I cannot glean from the docs:
1) Is PyTables a database?
2) Does PyTables store data in memory or on disk?
3) Does PyTables run it's own server that you connect to (like MySQL, Mongo, redis etc) or is it a library you use in the same process as your application (like Pandas)?

**Comment by FrancescAlted** [comment]
Hi.  I think for question 1) this applies: http://www.pytables.org/FAQ.html#is-pytables-a-replacement-for-a-relational-database

For 2), in general, PyTables stores on-disk, although it can put files completely in-memory too (see the [H5FD_CORE](https://www.pytables.org/usersguide/parameter_files.html#hdf5-driver-management) driver).

Regarding 3), no, PyTables does not come with any server.  If you need that, my personal recommendation is that you can build your own server very effectively with the [FastAPI framework](https://fastapi.tiangolo.com).

**Comment by NeilduToit13** [comment]
Okay thank you for the pointers.

For 2 and 3, that answers it, thank you.

For 1), that link applies but doesn't really help explain what it is. Saying you still need a relational database is a bit like saying "A foobar is not a replacement for electric trains". What is a foobar? A petrol train? A car? The reasons given for why PyTables does not replace a RDBMS could equally imply that:
a) PyTables is a database, but it is a not a relational database and you should still be using a relational database on the side...
b) PyTables is not a database, it's a <filesystem/compression algorithm/something else>, and you still need a database of some sort on the side, like an RDBMS.

But based on the answer to 2 and 3, it sounds to me like what PyTables really is is some sort of sophisticated filesystem?
Anyway, I think PyTables will help with my usecase, so I'll give it a try and see how it works. Thanks.

**Comment by maxnoe** [comment]
@NeilduToit13  I'll give it a shot for a small definition:

pytables is a python library to work with HDF5 files: https://www.hdfgroup.org/

It uses the C libhdf5 library to enable python programs to read, create and modify hdf5 files.
