### ISSUE TITLE
Using compiler.has_function() without includes specified breaks clang-16

### ISSUE THREAD

**Issue by mgorny** [PyTables/PyTables#984]
The upcoming clang-16 release treats implicit function declarations as fatal errors (see https://discourse.llvm.org/t/configure-script-breakage-with-the-new-werror-implicit-function-declaration/65213). As a result, using `compiler.has_function()` from distutils without explicitly specifying necessary includes results in checks failing incorrectly, e.g.:

```
python3.10 setup.py build -j 1 -j1
/tmp/portage/dev-python/pytables-3.8.0/temp/blosc2_list_compressors2avhs2_r.c:2:5: error: call to undeclared function 'blosc2_list_compressors'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    blosc2_list_compressors();
    ^
1 error generated.
[...]
* Could not find blosc2 headers and library; disabling support for it.
```

(this is with blosc2 library being available)

**Comment by avalentino** [comment]
Please @mgorny review the PR #987.
