### ISSUE TITLE
Please make it possible to use system c-blosc2 installation (without blosc2 Python package)

### ISSUE THREAD

**Issue by mgorny** [PyTables/PyTables#986]
Currently, `setup.py` forces `blosc2` Python package to be installed and forces blosc2 paths from it. Could you please make this optional and us use system-installed blosc2 like other compression libraries?

To confirm that it works, I have used the following hack locally:

```diff
diff --git a/setup.py b/setup.py
index 966be028..2708deb9 100755
--- a/setup.py
+++ b/setup.py
@@ -262,11 +262,11 @@ if __name__ == "__main__":
 
     debug = "--debug" in sys.argv
 
-    blosc2_inc, blosc2_lib = get_blosc2_directories()
+    blosc2_inc, blosc2_lib = "", ""
 
     # Global variables
     lib_dirs = [blosc2_lib]
-    inc_dirs = [Path("hdf5-blosc/src"), Path("hdf5-blosc2/src"), blosc2_inc]
+    inc_dirs = [Path("hdf5-blosc/src"), Path("hdf5-blosc2/src")]
     optional_libs = []
     copy_libs = []
 
```

**Comment by avalentino** [comment]
Dear @mgorny, there is a preliminary patch for this in https://github.com/conda-forge/pytables-feedstock/pull/82/commits/f4b6dcf65e9e1427885cc890a1daa253eb1817b0.
Unfortunately it seem not to work on windows and on non x86 architectures (see https://github.com/conda-forge/pytables-feedstock/pull/82).

Any help is very wellcome.

**Comment by mgorny** [comment]
Yes, that seems close to what I had in mind. It doesn't permit forcing system c-blosc2 if blosc2 is installed but that's a minor problem.

Do you mean that Windows builds don't work against system c-blosc2, or that the change actually causes regression on Windows when using Python blosc2 library? I'm afraid I've never developed for Windows, so I can't help with that much. However, I'd support the change even if it added the option on Linux, while still requiring Python blosc2 on Windows.

**Comment by avalentino** [comment]
The change should enable building pytables with system bloasc2 but the CI build of the conda package fails on windows, aarch64 and ppc64le (https://github.com/conda-forge/pytables-feedstock/pull/82).

**Comment by avalentino** [comment]
Please @mgorny review the PR #987.
