### ISSUE TITLE
Use H5Dchunk_iter rather than H5Dget_chunk_info for Blosc2

### ISSUE THREAD

**Issue by mkitti** [PyTables/PyTables#991]
HDF5 1.14 introduces `H5Dchunk_iter` which provides a more efficient way to iterate over all chunks rather than having $O(N^2)$ scaling where $N$ is the number of chunks. HDF5 1.14 was recently released. The function is being backported and is expected in 1.12.3 and 1.10.10.

Docs: https://docs.hdfgroup.org/hdf5/develop/group___h5_d.html#title6
Original pull request: https://github.com/HDFGroup/hdf5/pull/6

cc: @oscargm98 @FrancescAlted

**Comment by FrancescAlted** [comment]
Thanks @mkitti, that's interesting.  I think the advantage in speed should be more evident when chunks are small, which is not the usual case for Blosc2 chunks, but worth considering for next releases anyway.

**Comment by FrancescAlted** [comment]
For the record, I was curious on the kind of overhead HDF5 is adding to the e.g. [inkernel case](https://www.blosc.org/posts/blosc2-pytables-perf/), and it is really low (< 1%) when using Blosc2:

![image](https://user-images.githubusercontent.com/314521/210977268-a01b5990-7b37-46eb-9327-e34c3676acc3.png)

Note that the time is used mainly on reading from the OS filesystem cache and multithread synching (38% above), blosc2 (27%) and finally numexpr (14%).

Also, even using old plain Blosc filter (where the chunksizes are 72x smaller, and queries perfom ~2x slower too), the HDF5 layer is not adding too much overhead either:
￼
![image](https://user-images.githubusercontent.com/314521/210977511-19ef74f6-fd9c-410d-9371-39a09c9a15e8.png)

￼So, IMO we should not be too pressed in optimizing the HDF5 calls.  Having a much larger chunksize (as Blosc2 allows) is a way better path for getting good perfomance (at least for usual PyTables use cases).

**Comment by mkitti** [comment]
How many chunks are in your typical use case with large chunks? This only became an issue for me when I started to scale up to large multi-terabyte datasets.

**Comment by FrancescAlted** [comment]
In the case of the inkernel queries above for Blosc2, the number is < 100 (3.1 GB / 36 MB).  The point is that this means typically 2 orders of magnitude less than using the typical HDF5 single-partition.

For datasets that do not fit in OS filesystem cache, it would be interesting to try this out.  Which is the typical chunksize that you use for your multi-terabyte datasets?  The access pattern?  And the kind of speed-up that you get?

**Comment by FrancescAlted** [comment]
Finally, I realized the scenario where `H5Dchunk_iter` would be more useful, so I am having another go at this with https://github.com/PyTables/PyTables/pull/999.  Indeed, finding a case with a 5x speed is not something to sneeze at.

**Comment by FrancescAlted** [comment]
Now that #999 is in, we can close this.
