### ISSUE TITLE
Use python's warning system instead of printing to stderr

### ISSUE THREAD

**Issue by maxnoe** [PyTables/PyTables#992]
pytables is a library, as such it is very annoying that warnings are printed to stderr and not using the python standard warnings system.

It makes it much harder to e.g. make tests fail for resource leaks like `Closing remaining open files` which would be trivial if tables would instead of printing to stderr raise a `UnclosedFileWarning` and doing `-Werror::tables.UnclosedFileWarning`

**Comment by avalentino** [comment]
@maxnoe I think that the PyTables (the library) never prints to the stderr/stdout directly.
Could you please provide an example of the issue?

In the tests instead there are many places where the `print` function is used.
But in that case I think that the current approach is OK. Do you agree?

**Comment by avalentino** [comment]
Thanks @maxnoe, just merged your PR.
