### ISSUE TITLE
Documentation `Search` is broken.

### ISSUE THREAD

**Issue by rickhg12hs** [PyTables/PyTables#994]
No matter what terms(s) are used, `Search` never returns anything and only shows the `...` pulsing forever.

I tested it on the latest versions of Google Chrome and Firefox.  Other `readthedocs` (e.g., https://docs.readthedocs.io/en/stable/index.html) search normally in both browsers.

**Comment by avalentino** [comment]
@rickhg12hs thanks for reporting.
I made an attempt to re-upload the sphinx based documentation for which the search function works locally, but apparently there is some other issue.
We will investigate further.

**Comment by FrancescAlted** [comment]
Hey Antonio.  The find mechanism works for me (and it is fast) on the pytables.org site:
![image](https://user-images.githubusercontent.com/314521/216266407-5caa4206-39c5-4d1b-a475-ea0050fba181.png)

**Comment by avalentino** [comment]
Thanks @FrancescAlted 
Now it seems to work also for me, but with a different browser.
Closing

**Comment by FrancescAlted** [comment]
Yeah, probably a local cache issue.

**Comment by FrancescAlted** [comment]
BTW, was that a flaw on my latest release procedure?  What was the way to fix this exactly?

**Comment by avalentino** [comment]
Not sure, I just re-built and re-uploaded the HTML documentation.
As a side note I can say that I used the latest sphinx 6.x to build at the beginning, but I observed the search problem also locally.
Then I re-tried with sphinx 5.3 and it worked fine locally, so I decided to push the documentation.

**Comment by rickhg12hs** [comment]
Yep, works now!  Thanks!
